
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Castomizing(object):
    def setupUi(self, Castomizing):
        Castomizing.setObjectName("Castomizing")
        Castomizing.resize(806, 484)
        self.centralwidget = QtWidgets.QWidget(Castomizing)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 411))
        self.tabWidget.setObjectName("tabWidget")
        self.tabMaterials = QtWidgets.QWidget()
        self.tabMaterials.setObjectName("tabMaterials")
        self.scrollAreaMaterials = QtWidgets.QScrollArea(self.tabMaterials)
        self.scrollAreaMaterials.setGeometry(QtCore.QRect(10, 20, 781, 231))
        self.scrollAreaMaterials.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaMaterials.setWidgetResizable(True)
        self.scrollAreaMaterials.setObjectName("scrollAreaMaterials")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 762, 229))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.frameLineMaterial = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        self.frameLineMaterial.setGeometry(QtCore.QRect(10, 10, 736, 31))
        self.frameLineMaterial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameLineMaterial.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLineMaterial.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameLineMaterial.setObjectName("frameLineMaterial")
        self.lineEditNameMaterial = QtWidgets.QLineEdit(self.frameLineMaterial)
        self.lineEditNameMaterial.setGeometry(QtCore.QRect(0, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditNameMaterial.setFont(font)
        self.lineEditNameMaterial.setObjectName("lineEditNameMaterial")
        self.lineEditDensity = QtWidgets.QLineEdit(self.frameLineMaterial)
        self.lineEditDensity.setGeometry(QtCore.QRect(350, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditDensity.setFont(font)
        self.lineEditDensity.setObjectName("lineEditDensity")
        self.checkBoxSelectMaterial = QtWidgets.QCheckBox(self.frameLineMaterial)
        self.checkBoxSelectMaterial.setGeometry(QtCore.QRect(710, 6, 21, 21))
        self.checkBoxSelectMaterial.setText("")
        self.checkBoxSelectMaterial.setIconSize(QtCore.QSize(20, 20))
        self.checkBoxSelectMaterial.setObjectName("checkBoxSelectMaterial")
        self.lineEditGostMaterial = QtWidgets.QLineEdit(self.frameLineMaterial)
        self.lineEditGostMaterial.setGeometry(QtCore.QRect(120, 0, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditGostMaterial.setFont(font)
        self.lineEditGostMaterial.setObjectName("lineEditGostMaterial")
        self.lineEditLinkToSite = QtWidgets.QLineEdit(self.frameLineMaterial)
        self.lineEditLinkToSite.setGeometry(QtCore.QRect(390, 0, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setUnderline(True)
        self.lineEditLinkToSite.setFont(font)
        self.lineEditLinkToSite.setObjectName("lineEditLinkToSite")
        self.scrollAreaMaterials.setWidget(self.scrollAreaWidgetContents_3)
        self.labelMaterialsUsed = QtWidgets.QLabel(self.tabMaterials)
        self.labelMaterialsUsed.setGeometry(QtCore.QRect(290, 0, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelMaterialsUsed.setFont(font)
        self.labelMaterialsUsed.setObjectName("labelMaterialsUsed")
        self.lineEditLinkToSiteAdd = QtWidgets.QLineEdit(self.tabMaterials)
        self.lineEditLinkToSiteAdd.setGeometry(QtCore.QRect(260, 290, 331, 20))
        self.lineEditLinkToSiteAdd.setObjectName("lineEditLinkToSiteAdd")
        self.BtnDeleteSelectedMaterial = QtWidgets.QPushButton(self.tabMaterials)
        self.BtnDeleteSelectedMaterial.setGeometry(QtCore.QRect(630, 290, 151, 30))
        self.BtnDeleteSelectedMaterial.setObjectName("BtnDeleteSelectedMaterial")
        self.lineEditNameMaterialAdd = QtWidgets.QLineEdit(self.tabMaterials)
        self.lineEditNameMaterialAdd.setGeometry(QtCore.QRect(100, 290, 141, 20))
        self.lineEditNameMaterialAdd.setObjectName("lineEditNameMaterialAdd")
        self.lineEditDensityAdd = QtWidgets.QLineEdit(self.tabMaterials)
        self.lineEditDensityAdd.setGeometry(QtCore.QRect(100, 350, 61, 20))
        self.lineEditDensityAdd.setObjectName("lineEditDensityAdd")
        self.BtnAddMaterial = QtWidgets.QPushButton(self.tabMaterials)
        self.BtnAddMaterial.setGeometry(QtCore.QRect(330, 330, 191, 23))
        self.BtnAddMaterial.setObjectName("BtnAddMaterial")
        self.BtnSaveChangesMaterial = QtWidgets.QPushButton(self.tabMaterials)
        self.BtnSaveChangesMaterial.setGeometry(QtCore.QRect(630, 330, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnSaveChangesMaterial.setFont(font)
        self.BtnSaveChangesMaterial.setObjectName("BtnSaveChangesMaterial")
        self.labelDensity = QtWidgets.QLabel(self.tabMaterials)
        self.labelDensity.setGeometry(QtCore.QRect(20, 350, 61, 16))
        self.labelDensity.setObjectName("labelDensity")
        self.lineEditGostMaterialAdd = QtWidgets.QLineEdit(self.tabMaterials)
        self.lineEditGostMaterialAdd.setGeometry(QtCore.QRect(100, 320, 141, 20))
        self.lineEditGostMaterialAdd.setObjectName("lineEditGostMaterialAdd")
        self.labelAddNewMaterial = QtWidgets.QLabel(self.tabMaterials)
        self.labelAddNewMaterial.setGeometry(QtCore.QRect(100, 260, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelAddNewMaterial.setFont(font)
        self.labelAddNewMaterial.setObjectName("labelAddNewMaterial")
        self.labelGostMaterial = QtWidgets.QLabel(self.tabMaterials)
        self.labelGostMaterial.setGeometry(QtCore.QRect(20, 320, 47, 16))
        self.labelGostMaterial.setObjectName("labelGostMaterial")
        self.labelNameMaterial = QtWidgets.QLabel(self.tabMaterials)
        self.labelNameMaterial.setGeometry(QtCore.QRect(20, 286, 81, 20))
        self.labelNameMaterial.setObjectName("labelNameMaterial")
        self.labelDimension = QtWidgets.QLabel(self.tabMaterials)
        self.labelDimension.setGeometry(QtCore.QRect(170, 350, 61, 16))
        self.labelDimension.setObjectName("labelDimension")
        self.labelLinkToSite = QtWidgets.QLabel(self.tabMaterials)
        self.labelLinkToSite.setGeometry(QtCore.QRect(350, 270, 181, 20))
        self.labelLinkToSite.setObjectName("labelLinkToSite")
        self.line = QtWidgets.QFrame(self.tabMaterials)
        self.line.setGeometry(QtCore.QRect(600, 270, 20, 101))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.tabWidget.addTab(self.tabMaterials, "")
        self.tabForms = QtWidgets.QWidget()
        self.tabForms.setObjectName("tabForms")
        self.labelGostForm = QtWidgets.QLabel(self.tabForms)
        self.labelGostForm.setGeometry(QtCore.QRect(20, 320, 47, 16))
        self.labelGostForm.setObjectName("labelGostForm")
        self.BtnAddForm = QtWidgets.QPushButton(self.tabForms)
        self.BtnAddForm.setGeometry(QtCore.QRect(390, 350, 191, 23))
        self.BtnAddForm.setObjectName("BtnAddForm")
        self.labelNameForm = QtWidgets.QLabel(self.tabForms)
        self.labelNameForm.setGeometry(QtCore.QRect(20, 286, 81, 20))
        self.labelNameForm.setObjectName("labelNameForm")
        self.labelFormUsed = QtWidgets.QLabel(self.tabForms)
        self.labelFormUsed.setGeometry(QtCore.QRect(290, 0, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelFormUsed.setFont(font)
        self.labelFormUsed.setObjectName("labelFormUsed")
        self.scrollAreaForms = QtWidgets.QScrollArea(self.tabForms)
        self.scrollAreaForms.setGeometry(QtCore.QRect(10, 20, 781, 231))
        self.scrollAreaForms.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaForms.setWidgetResizable(True)
        self.scrollAreaForms.setObjectName("scrollAreaForms")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 762, 229))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.frameLineForm = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frameLineForm.setGeometry(QtCore.QRect(10, 10, 736, 31))
        self.frameLineForm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameLineForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLineForm.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameLineForm.setObjectName("frameLineForm")
        self.lineEditNameForm = QtWidgets.QLineEdit(self.frameLineForm)
        self.lineEditNameForm.setGeometry(QtCore.QRect(0, 0, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditNameForm.setFont(font)
        self.lineEditNameForm.setObjectName("lineEditNameForm")
        self.checkBoxSelectForm = QtWidgets.QCheckBox(self.frameLineForm)
        self.checkBoxSelectForm.setGeometry(QtCore.QRect(710, 6, 21, 21))
        self.checkBoxSelectForm.setText("")
        self.checkBoxSelectForm.setIconSize(QtCore.QSize(20, 20))
        self.checkBoxSelectForm.setObjectName("checkBoxSelectForm")
        self.lineEditGostForm = QtWidgets.QLineEdit(self.frameLineForm)
        self.lineEditGostForm.setGeometry(QtCore.QRect(470, 0, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditGostForm.setFont(font)
        self.lineEditGostForm.setObjectName("lineEditGostForm")
        self.scrollAreaForms.setWidget(self.scrollAreaWidgetContents_4)
        self.labelAddNewForm = QtWidgets.QLabel(self.tabForms)
        self.labelAddNewForm.setGeometry(QtCore.QRect(230, 260, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelAddNewForm.setFont(font)
        self.labelAddNewForm.setObjectName("labelAddNewForm")
        self.lineEditNameFormAdd = QtWidgets.QLineEdit(self.tabForms)
        self.lineEditNameFormAdd.setGeometry(QtCore.QRect(100, 290, 481, 20))
        self.lineEditNameFormAdd.setObjectName("lineEditNameFormAdd")
        self.lineEditGostFormAdd = QtWidgets.QLineEdit(self.tabForms)
        self.lineEditGostFormAdd.setGeometry(QtCore.QRect(100, 320, 221, 20))
        self.lineEditGostFormAdd.setObjectName("lineEditGostFormAdd")
        self.BtnDeleteSelectedForm = QtWidgets.QPushButton(self.tabForms)
        self.BtnDeleteSelectedForm.setGeometry(QtCore.QRect(630, 290, 151, 30))
        self.BtnDeleteSelectedForm.setObjectName("BtnDeleteSelectedForm")
        self.BtnSaveChangesForm = QtWidgets.QPushButton(self.tabForms)
        self.BtnSaveChangesForm.setGeometry(QtCore.QRect(630, 330, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnSaveChangesForm.setFont(font)
        self.BtnSaveChangesForm.setObjectName("BtnSaveChangesForm")
        self.line_2 = QtWidgets.QFrame(self.tabForms)
        self.line_2.setGeometry(QtCore.QRect(600, 270, 20, 101))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.tabForms, "")
        self.tabEmployees = QtWidgets.QWidget()
        self.tabEmployees.setObjectName("tabEmployees")
        self.lineEditSecondNameAdd = QtWidgets.QLineEdit(self.tabEmployees)
        self.lineEditSecondNameAdd.setGeometry(QtCore.QRect(100, 290, 191, 20))
        self.lineEditSecondNameAdd.setObjectName("lineEditSecondNameAdd")
        self.labelSecondName = QtWidgets.QLabel(self.tabEmployees)
        self.labelSecondName.setGeometry(QtCore.QRect(20, 290, 47, 13))
        self.labelSecondName.setObjectName("labelSecondName")
        self.lineEditFirstNameAdd = QtWidgets.QLineEdit(self.tabEmployees)
        self.lineEditFirstNameAdd.setGeometry(QtCore.QRect(100, 320, 191, 20))
        self.lineEditFirstNameAdd.setObjectName("lineEditFirstNameAdd")
        self.labelFirstName = QtWidgets.QLabel(self.tabEmployees)
        self.labelFirstName.setGeometry(QtCore.QRect(20, 320, 47, 16))
        self.labelFirstName.setObjectName("labelFirstName")
        self.lineEditMiddleNameAdd = QtWidgets.QLineEdit(self.tabEmployees)
        self.lineEditMiddleNameAdd.setGeometry(QtCore.QRect(100, 350, 191, 20))
        self.lineEditMiddleNameAdd.setObjectName("lineEditMiddleNameAdd")
        self.labelMiddleName = QtWidgets.QLabel(self.tabEmployees)
        self.labelMiddleName.setGeometry(QtCore.QRect(20, 350, 61, 16))
        self.labelMiddleName.setObjectName("labelMiddleName")
        self.lineEditPostAdd = QtWidgets.QLineEdit(self.tabEmployees)
        self.lineEditPostAdd.setGeometry(QtCore.QRect(400, 290, 191, 20))
        self.lineEditPostAdd.setObjectName("lineEditPostAdd")
        self.labelPost = QtWidgets.QLabel(self.tabEmployees)
        self.labelPost.setGeometry(QtCore.QRect(320, 290, 61, 16))
        self.labelPost.setObjectName("labelPost")
        self.labelNewEmployeeAdd = QtWidgets.QLabel(self.tabEmployees)
        self.labelNewEmployeeAdd.setGeometry(QtCore.QRect(230, 260, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelNewEmployeeAdd.setFont(font)
        self.labelNewEmployeeAdd.setObjectName("labelNewEmployeeAdd")
        self.labelListOfEmployees = QtWidgets.QLabel(self.tabEmployees)
        self.labelListOfEmployees.setGeometry(QtCore.QRect(310, 0, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelListOfEmployees.setFont(font)
        self.labelListOfEmployees.setObjectName("labelListOfEmployees")
        self.scrollAreaEmployees = QtWidgets.QScrollArea(self.tabEmployees)
        self.scrollAreaEmployees.setGeometry(QtCore.QRect(10, 20, 781, 231))
        self.scrollAreaEmployees.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaEmployees.setWidgetResizable(True)
        self.scrollAreaEmployees.setObjectName("scrollAreaEmployees")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 762, 229))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frameLineEmployee = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameLineEmployee.setGeometry(QtCore.QRect(10, 10, 736, 31))
        self.frameLineEmployee.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameLineEmployee.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLineEmployee.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameLineEmployee.setObjectName("frameLineEmployee")
        self.LbNumberEmployee = QtWidgets.QLabel(self.frameLineEmployee)
        self.LbNumberEmployee.setGeometry(QtCore.QRect(10, 8, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbNumberEmployee.setFont(font)
        self.LbNumberEmployee.setObjectName("LbNumberEmployee")
        self.lineEditSecondName = QtWidgets.QLineEdit(self.frameLineEmployee)
        self.lineEditSecondName.setGeometry(QtCore.QRect(30, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditSecondName.setFont(font)
        self.lineEditSecondName.setObjectName("lineEditSecondName")
        self.lineEditPost = QtWidgets.QLineEdit(self.frameLineEmployee)
        self.lineEditPost.setGeometry(QtCore.QRect(400, 0, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditPost.setFont(font)
        self.lineEditPost.setObjectName("lineEditPost")
        self.checkBoxSelectEmployee = QtWidgets.QCheckBox(self.frameLineEmployee)
        self.checkBoxSelectEmployee.setGeometry(QtCore.QRect(710, 6, 21, 21))
        self.checkBoxSelectEmployee.setText("")
        self.checkBoxSelectEmployee.setIconSize(QtCore.QSize(20, 20))
        self.checkBoxSelectEmployee.setObjectName("checkBoxSelectEmployee")
        self.lineEditFirstName = QtWidgets.QLineEdit(self.frameLineEmployee)
        self.lineEditFirstName.setGeometry(QtCore.QRect(160, 0, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditFirstName.setFont(font)
        self.lineEditFirstName.setObjectName("lineEditFirstName")
        self.lineEditMiddleName = QtWidgets.QLineEdit(self.frameLineEmployee)
        self.lineEditMiddleName.setGeometry(QtCore.QRect(270, 0, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditMiddleName.setFont(font)
        self.lineEditMiddleName.setObjectName("lineEditMiddleName")
        self.comboBoxRole = QtWidgets.QComboBox(self.frameLineEmployee)
        self.comboBoxRole.setGeometry(QtCore.QRect(570, 0, 131, 30))
        self.comboBoxRole.setCurrentText("")
        self.comboBoxRole.setObjectName("comboBoxRole")
        self.scrollAreaEmployees.setWidget(self.scrollAreaWidgetContents)
        self.labelRole = QtWidgets.QLabel(self.tabEmployees)
        self.labelRole.setGeometry(QtCore.QRect(320, 320, 61, 16))
        self.labelRole.setObjectName("labelRole")
        self.BtnAddEmployee = QtWidgets.QPushButton(self.tabEmployees)
        self.BtnAddEmployee.setGeometry(QtCore.QRect(400, 350, 191, 23))
        self.BtnAddEmployee.setObjectName("BtnAddEmployee")
        self.BtnSaveChangesEmpl = QtWidgets.QPushButton(self.tabEmployees)
        self.BtnSaveChangesEmpl.setGeometry(QtCore.QRect(630, 330, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnSaveChangesEmpl.setFont(font)
        self.BtnSaveChangesEmpl.setObjectName("BtnSaveChangesEmpl")
        self.line_9 = QtWidgets.QFrame(self.tabEmployees)
        self.line_9.setGeometry(QtCore.QRect(600, 270, 20, 101))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.BtnDeleteSelectedEmployee = QtWidgets.QPushButton(self.tabEmployees)
        self.BtnDeleteSelectedEmployee.setGeometry(QtCore.QRect(630, 290, 151, 30))
        self.BtnDeleteSelectedEmployee.setObjectName("BtnDeleteSelectedEmployee")
        self.comboBoxRoleAdd = QtWidgets.QComboBox(self.tabEmployees)
        self.comboBoxRoleAdd.setGeometry(QtCore.QRect(400, 320, 191, 20))
        self.comboBoxRoleAdd.setObjectName("comboBoxRoleAdd")
        self.tabWidget.addTab(self.tabEmployees, "")
        self.tabPasswords = QtWidgets.QWidget()
        self.tabPasswords.setObjectName("tabPasswords")
        self.frame_2 = QtWidgets.QFrame(self.tabPasswords)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 331, 101))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.BtnApplyStandartPasswordManager = QtWidgets.QPushButton(self.frame_2)
        self.BtnApplyStandartPasswordManager.setGeometry(QtCore.QRect(110, 7, 121, 23))
        self.BtnApplyStandartPasswordManager.setObjectName("BtnApplyStandartPasswordManager")
        self.labelManager = QtWidgets.QLabel(self.frame_2)
        self.labelManager.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelManager.setFont(font)
        self.labelManager.setObjectName("labelManager")
        self.labelStandartPasswordManager = QtWidgets.QLabel(self.frame_2)
        self.labelStandartPasswordManager.setGeometry(QtCore.QRect(250, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStandartPasswordManager.setFont(font)
        self.labelStandartPasswordManager.setObjectName("labelStandartPasswordManager")
        self.labelStandartPasswordEngineer = QtWidgets.QLabel(self.frame_2)
        self.labelStandartPasswordEngineer.setGeometry(QtCore.QRect(250, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStandartPasswordEngineer.setFont(font)
        self.labelStandartPasswordEngineer.setObjectName("labelStandartPasswordEngineer")
        self.BtnApplyStandartPasswordEngineer = QtWidgets.QPushButton(self.frame_2)
        self.BtnApplyStandartPasswordEngineer.setGeometry(QtCore.QRect(110, 37, 121, 23))
        self.BtnApplyStandartPasswordEngineer.setObjectName("BtnApplyStandartPasswordEngineer")
        self.labelProduction = QtWidgets.QLabel(self.frame_2)
        self.labelProduction.setGeometry(QtCore.QRect(10, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelProduction.setFont(font)
        self.labelProduction.setObjectName("labelProduction")
        self.BtnApplyStandartPasswordProduction = QtWidgets.QPushButton(self.frame_2)
        self.BtnApplyStandartPasswordProduction.setGeometry(QtCore.QRect(110, 67, 121, 23))
        self.BtnApplyStandartPasswordProduction.setObjectName("BtnApplyStandartPasswordProduction")
        self.labelStandartPasswordProduction = QtWidgets.QLabel(self.frame_2)
        self.labelStandartPasswordProduction.setGeometry(QtCore.QRect(250, 70, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStandartPasswordProduction.setFont(font)
        self.labelStandartPasswordProduction.setObjectName("labelStandartPasswordProduction")
        self.labelEngineer = QtWidgets.QLabel(self.frame_2)
        self.labelEngineer.setGeometry(QtCore.QRect(10, 40, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelEngineer.setFont(font)
        self.labelEngineer.setObjectName("labelEngineer")
        self.tabWidget.addTab(self.tabPasswords, "")
        self.BtnBack = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBack.setGeometry(QtCore.QRect(10, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnBack.setFont(font)
        self.BtnBack.setObjectName("BtnBack")
        Castomizing.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Castomizing)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        Castomizing.setMenuBar(self.menubar)

        self.retranslateUi(Castomizing)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Castomizing)

    def retranslateUi(self, Castomizing):
        _translate = QtCore.QCoreApplication.translate
        Castomizing.setWindowTitle(_translate("Castomizing", "Настройки"))
        self.lineEditNameMaterial.setText(_translate("Castomizing", "Сталь 45"))
        self.lineEditDensity.setText(_translate("Castomizing", "7826"))
        self.lineEditGostMaterial.setText(_translate("Castomizing", "ГОСТ 1050 - 88"))
        self.lineEditLinkToSite.setText(_translate("Castomizing", "https://www.splav-kharkov.com/mat_start.php?name_id=87"))
        self.labelMaterialsUsed.setText(_translate("Castomizing", "Применяемые материалы:"))
        self.BtnDeleteSelectedMaterial.setText(_translate("Castomizing", "Удалить выбранную запись"))
        self.BtnAddMaterial.setText(_translate("Castomizing", "Добавить"))
        self.BtnSaveChangesMaterial.setText(_translate("Castomizing", "Сохранить изменения"))
        self.labelDensity.setText(_translate("Castomizing", "Плотность"))
        self.labelAddNewMaterial.setText(_translate("Castomizing", "Добавление нового материала:"))
        self.labelGostMaterial.setText(_translate("Castomizing", "ГОСТ"))
        self.labelNameMaterial.setText(_translate("Castomizing", "Наименование"))
        self.labelDimension.setText(_translate("Castomizing", "кг/м"))
        self.labelLinkToSite.setText(_translate("Castomizing", "Ссылка на сайт с материалом"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMaterials), _translate("Castomizing", "Материалы"))
        self.labelGostForm.setText(_translate("Castomizing", "ГОСТ"))
        self.BtnAddForm.setText(_translate("Castomizing", "Добавить"))
        self.labelNameForm.setText(_translate("Castomizing", "Наименование"))
        self.labelFormUsed.setText(_translate("Castomizing", "Применяемые формы:"))
        self.lineEditNameForm.setText(_translate("Castomizing", "Сталь калиброванная круглая"))
        self.lineEditGostForm.setText(_translate("Castomizing", "ГОСТ 7417-75"))
        self.labelAddNewForm.setText(_translate("Castomizing", "Добавление новой формы:"))
        self.BtnDeleteSelectedForm.setText(_translate("Castomizing", "Удалить выбранную запись"))
        self.BtnSaveChangesForm.setText(_translate("Castomizing", "Сохранить изменения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabForms), _translate("Castomizing", "Формы"))
        self.labelSecondName.setText(_translate("Castomizing", "Фамилия"))
        self.labelFirstName.setText(_translate("Castomizing", "Имя"))
        self.labelMiddleName.setText(_translate("Castomizing", "Отчество"))
        self.labelPost.setText(_translate("Castomizing", "Должность"))
        self.labelNewEmployeeAdd.setText(_translate("Castomizing", "Добавление нового сотрудника"))
        self.labelListOfEmployees.setText(_translate("Castomizing", "Список сотрудников:"))
        self.LbNumberEmployee.setText(_translate("Castomizing", "1"))
        self.lineEditSecondName.setText(_translate("Castomizing", "Фамилия"))
        self.lineEditPost.setText(_translate("Castomizing", "Должность"))
        self.lineEditFirstName.setText(_translate("Castomizing", "Имя "))
        self.lineEditMiddleName.setText(_translate("Castomizing", "Отчество"))
        self.labelRole.setText(_translate("Castomizing", "Роль"))
        self.BtnAddEmployee.setText(_translate("Castomizing", "Добавить"))
        self.BtnSaveChangesEmpl.setText(_translate("Castomizing", "Сохранить изменения"))
        self.BtnDeleteSelectedEmployee.setText(_translate("Castomizing", "Удалить выбранную запись"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabEmployees), _translate("Castomizing", "Сотрудники "))
        self.BtnApplyStandartPasswordManager.setText(_translate("Castomizing", "Стандарный пароль"))
        self.labelManager.setText(_translate("Castomizing", "Менеджер"))
        self.labelStandartPasswordManager.setText(_translate("Castomizing", "\'manager\'"))
        self.labelStandartPasswordEngineer.setText(_translate("Castomizing", "\'engineer\'"))
        self.BtnApplyStandartPasswordEngineer.setText(_translate("Castomizing", "Стандарный пароль"))
        self.labelProduction.setText(_translate("Castomizing", "Производство"))
        self.BtnApplyStandartPasswordProduction.setText(_translate("Castomizing", "Стандарный пароль"))
        self.labelStandartPasswordProduction.setText(_translate("Castomizing", "\'prod\'"))
        self.labelEngineer.setText(_translate("Castomizing", "Инженер"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPasswords), _translate("Castomizing", "Пароли"))
        self.BtnBack.setText(_translate("Castomizing", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Castomizing = QtWidgets.QMainWindow()
    ui = Ui_Castomizing()
    ui.setupUi(Castomizing)
    Castomizing.show()
    sys.exit(app.exec_())
