
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Employees(object):
    def setupUi(self, Employees):
        Employees.setObjectName("Employees")
        Employees.resize(1051, 575)
        self.centralwidget = QtWidgets.QWidget(Employees)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_widget = QtWidgets.QWidget(self.centralwidget)
        self.header_widget.setMaximumSize(QtCore.QSize(16777215, 20))
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.header_widget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.header_widget)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setObjectName("main_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.main_widget)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 996, 463))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LbNumberEmployee = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbNumberEmployee.setFont(font)
        self.LbNumberEmployee.setObjectName("LbNumberEmployee")
        self.horizontalLayout_3.addWidget(self.LbNumberEmployee)
        self.lineEditSecondName = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditSecondName.setFont(font)
        self.lineEditSecondName.setText("")
        self.lineEditSecondName.setObjectName("lineEditSecondName")
        self.horizontalLayout_3.addWidget(self.lineEditSecondName)
        self.lineEditFirstName = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditFirstName.setFont(font)
        self.lineEditFirstName.setText("")
        self.lineEditFirstName.setObjectName("lineEditFirstName")
        self.horizontalLayout_3.addWidget(self.lineEditFirstName)
        self.lineEditMiddleName = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditMiddleName.setFont(font)
        self.lineEditMiddleName.setText("")
        self.lineEditMiddleName.setObjectName("lineEditMiddleName")
        self.horizontalLayout_3.addWidget(self.lineEditMiddleName)
        self.lineEditPost = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditPost.setFont(font)
        self.lineEditPost.setText("")
        self.lineEditPost.setObjectName("lineEditPost")
        self.horizontalLayout_3.addWidget(self.lineEditPost)
        self.comboBoxRole = QtWidgets.QComboBox(self.widget_4)
        self.comboBoxRole.setMinimumSize(QtCore.QSize(80, 0))
        self.comboBoxRole.setCurrentText("")
        self.comboBoxRole.setObjectName("comboBoxRole")
        self.horizontalLayout_3.addWidget(self.comboBoxRole)
        self.checkBoxSelectMaterial = QtWidgets.QCheckBox(self.widget_4)
        self.checkBoxSelectMaterial.setText("")
        self.checkBoxSelectMaterial.setIconSize(QtCore.QSize(20, 20))
        self.checkBoxSelectMaterial.setObjectName("checkBoxSelectMaterial")
        self.horizontalLayout_3.addWidget(self.checkBoxSelectMaterial)
        self.verticalLayout_3.addWidget(self.widget_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 394, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.main_widget)
        self.bottom_panel_widget = QtWidgets.QWidget(self.centralwidget)
        self.bottom_panel_widget.setMaximumSize(QtCore.QSize(16777215, 80))
        self.bottom_panel_widget.setObjectName("bottom_panel_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bottom_panel_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BtnDeleteSelectedMaterial = QtWidgets.QPushButton(self.bottom_panel_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnDeleteSelectedMaterial.setFont(font)
        self.BtnDeleteSelectedMaterial.setObjectName("BtnDeleteSelectedMaterial")
        self.horizontalLayout_2.addWidget(self.BtnDeleteSelectedMaterial)
        spacerItem3 = QtWidgets.QSpacerItem(301, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.BtnAddMaterial = QtWidgets.QPushButton(self.bottom_panel_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnAddMaterial.setFont(font)
        self.BtnAddMaterial.setObjectName("BtnAddMaterial")
        self.horizontalLayout_2.addWidget(self.BtnAddMaterial)
        spacerItem4 = QtWidgets.QSpacerItem(301, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.BtnSaveChangesMaterial = QtWidgets.QPushButton(self.bottom_panel_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnSaveChangesMaterial.setFont(font)
        self.BtnSaveChangesMaterial.setObjectName("BtnSaveChangesMaterial")
        self.horizontalLayout_2.addWidget(self.BtnSaveChangesMaterial)
        self.verticalLayout.addWidget(self.bottom_panel_widget)
        Employees.setCentralWidget(self.centralwidget)

        self.retranslateUi(Employees)
        QtCore.QMetaObject.connectSlotsByName(Employees)

    def retranslateUi(self, Employees):
        _translate = QtCore.QCoreApplication.translate
        Employees.setWindowTitle(_translate("Employees", "Сотрудники"))
        self.label.setText(_translate("Employees", "Список сотрудников:"))
        self.LbNumberEmployee.setText(_translate("Employees", "1"))
        self.lineEditSecondName.setPlaceholderText(_translate("Employees", "Фамилия"))
        self.lineEditFirstName.setPlaceholderText(_translate("Employees", "Имя "))
        self.lineEditMiddleName.setPlaceholderText(_translate("Employees", "Отчество"))
        self.lineEditPost.setPlaceholderText(_translate("Employees", "Должность"))
        self.BtnDeleteSelectedMaterial.setText(_translate("Employees", "Удалить выбранную запись"))
        self.BtnAddMaterial.setText(_translate("Employees", "Добавить запись"))
        self.BtnSaveChangesMaterial.setText(_translate("Employees", "Сохранить изменения"))

class Employees(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Employees()
        self.ui.setupUi(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Employees = QtWidgets.QMainWindow()
    ui = Ui_Employees()
    ui.setupUi(Employees)
    Employees.show()
    sys.exit(app.exec_())
