
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Passwords(object):
    def setupUi(self, Passwords):
        Passwords.setObjectName("Passwords")
        Passwords.resize(974, 565)
        self.centralwidget = QtWidgets.QWidget(Passwords)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.header_widget = QtWidgets.QWidget(self.centralwidget)
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.header_widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.header_widget)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.main_widget = QtWidgets.QWidget(self.widget)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout.setContentsMargins(-1, 100, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.BtnApplyStandartPasswordEngineer = QtWidgets.QPushButton(self.main_widget)
        self.BtnApplyStandartPasswordEngineer.setObjectName("BtnApplyStandartPasswordEngineer")
        self.gridLayout.addWidget(self.BtnApplyStandartPasswordEngineer, 1, 1, 1, 1)
        self.BtnApplyStandartPasswordProduction = QtWidgets.QPushButton(self.main_widget)
        self.BtnApplyStandartPasswordProduction.setObjectName("BtnApplyStandartPasswordProduction")
        self.gridLayout.addWidget(self.BtnApplyStandartPasswordProduction, 2, 1, 1, 1)
        self.labelStandartPasswordProduction = QtWidgets.QLabel(self.main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStandartPasswordProduction.setFont(font)
        self.labelStandartPasswordProduction.setObjectName("labelStandartPasswordProduction")
        self.gridLayout.addWidget(self.labelStandartPasswordProduction, 2, 2, 1, 1)
        self.labelStandartPasswordManager = QtWidgets.QLabel(self.main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStandartPasswordManager.setFont(font)
        self.labelStandartPasswordManager.setObjectName("labelStandartPasswordManager")
        self.gridLayout.addWidget(self.labelStandartPasswordManager, 0, 2, 1, 1)
        self.labelStandartPasswordEngineer = QtWidgets.QLabel(self.main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStandartPasswordEngineer.setFont(font)
        self.labelStandartPasswordEngineer.setObjectName("labelStandartPasswordEngineer")
        self.gridLayout.addWidget(self.labelStandartPasswordEngineer, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 3, 1, 1, 1)
        self.BtnApplyStandartPasswordManager = QtWidgets.QPushButton(self.main_widget)
        self.BtnApplyStandartPasswordManager.setObjectName("BtnApplyStandartPasswordManager")
        self.gridLayout.addWidget(self.BtnApplyStandartPasswordManager, 0, 1, 1, 1)
        self.labelManager = QtWidgets.QLabel(self.main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelManager.setFont(font)
        self.labelManager.setObjectName("labelManager")
        self.gridLayout.addWidget(self.labelManager, 0, 0, 1, 1)
        self.labelProduction = QtWidgets.QLabel(self.main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelProduction.setFont(font)
        self.labelProduction.setObjectName("labelProduction")
        self.gridLayout.addWidget(self.labelProduction, 2, 0, 1, 1)
        self.labelEngineer = QtWidgets.QLabel(self.main_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelEngineer.setFont(font)
        self.labelEngineer.setObjectName("labelEngineer")
        self.gridLayout.addWidget(self.labelEngineer, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.main_widget)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.widget)
        Passwords.setCentralWidget(self.centralwidget)

        self.retranslateUi(Passwords)
        QtCore.QMetaObject.connectSlotsByName(Passwords)

    def retranslateUi(self, Passwords):
        _translate = QtCore.QCoreApplication.translate
        Passwords.setWindowTitle(_translate("Passwords", "MainWindow"))
        self.label.setText(_translate("Passwords", "Здесь вы можете установить стандартные пароли для ролей:"))
        self.BtnApplyStandartPasswordEngineer.setText(_translate("Passwords", "Стандарный пароль"))
        self.BtnApplyStandartPasswordProduction.setText(_translate("Passwords", "Стандарный пароль"))
        self.labelStandartPasswordProduction.setText(_translate("Passwords", "\'prod\'"))
        self.labelStandartPasswordManager.setText(_translate("Passwords", "\'manager\'"))
        self.labelStandartPasswordEngineer.setText(_translate("Passwords", "\'engineer\'"))
        self.BtnApplyStandartPasswordManager.setText(_translate("Passwords", "Стандарный пароль"))
        self.labelManager.setText(_translate("Passwords", "Менеджер"))
        self.labelProduction.setText(_translate("Passwords", "Производство"))
        self.labelEngineer.setText(_translate("Passwords", "Инженер"))

class Passwords(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Passwords()
        self.ui.setupUi(self)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Passwords = QtWidgets.QMainWindow()
    ui = Ui_Passwords()
    ui.setupUi(Passwords)
    Passwords.show()
    sys.exit(app.exec_())
