
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DesignDocumentFillingForm(object):
    def setupUi(self, DesignDocumentFillingForm):
        DesignDocumentFillingForm.setObjectName("DesignDocumentFillingForm")
        DesignDocumentFillingForm.resize(1019, 750)
        self.centralwidget = QtWidgets.QWidget(DesignDocumentFillingForm)
        self.centralwidget.setObjectName("centralwidget")
        self.BtnRotateRight_2 = QtWidgets.QTabWidget(self.centralwidget)
        self.BtnRotateRight_2.setGeometry(QtCore.QRect(10, 40, 1006, 571))
        self.BtnRotateRight_2.setObjectName("BtnRotateRight_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEditUnitName = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditUnitName.setGeometry(QtCore.QRect(495, 25, 496, 26))
        self.lineEditUnitName.setObjectName("lineEditUnitName")
        self.labelEditUnitName = QtWidgets.QLabel(self.tab_3)
        self.labelEditUnitName.setGeometry(QtCore.QRect(495, 0, 256, 16))
        self.labelEditUnitName.setObjectName("labelEditUnitName")
        self.labelBelongingToAnAssemblyUnit = QtWidgets.QLabel(self.tab_3)
        self.labelBelongingToAnAssemblyUnit.setGeometry(QtCore.QRect(10, 15, 156, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelBelongingToAnAssemblyUnit.setFont(font)
        self.labelBelongingToAnAssemblyUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBelongingToAnAssemblyUnit.setWordWrap(True)
        self.labelBelongingToAnAssemblyUnit.setObjectName("labelBelongingToAnAssemblyUnit")
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 50, 381, 491))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.radioButtonUnit_1 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonUnit_1.setGeometry(QtCore.QRect(10, 10, 361, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonUnit_1.setFont(font)
        self.radioButtonUnit_1.setObjectName("radioButtonUnit_1")
        self.radioButtonUnit_2 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonUnit_2.setGeometry(QtCore.QRect(10, 45, 361, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonUnit_2.setFont(font)
        self.radioButtonUnit_2.setObjectName("radioButtonUnit_2")
        self.frame = QtWidgets.QFrame(self.tab_3)
        self.frame.setGeometry(QtCore.QRect(185, 5, 181, 16))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButtonSlave = QtWidgets.QRadioButton(self.frame)
        self.radioButtonSlave.setGeometry(QtCore.QRect(95, 0, 82, 17))
        self.radioButtonSlave.setObjectName("radioButtonSlave")
        self.radioButtonMain = QtWidgets.QRadioButton(self.frame)
        self.radioButtonMain.setGeometry(QtCore.QRect(5, 0, 82, 17))
        self.radioButtonMain.setObjectName("radioButtonMain")
        self.BtnOpenDesignFile = QtWidgets.QPushButton(self.tab_3)
        self.BtnOpenDesignFile.setGeometry(QtCore.QRect(380, 25, 106, 26))
        self.BtnOpenDesignFile.setToolTipDuration(3000)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../utils/icons/folder2-open.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnOpenDesignFile.setIcon(icon)
        self.BtnOpenDesignFile.setIconSize(QtCore.QSize(20, 20))
        self.BtnOpenDesignFile.setObjectName("BtnOpenDesignFile")
        self.tabWidgetDecignDoc = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidgetDecignDoc.setGeometry(QtCore.QRect(380, 55, 621, 491))
        self.tabWidgetDecignDoc.setObjectName("tabWidgetDecignDoc")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.BtnRotateLeft = QtWidgets.QPushButton(self.tab_5)
        self.BtnRotateLeft.setGeometry(QtCore.QRect(260, 425, 31, 31))
        self.BtnRotateLeft.setToolTipDuration(3000)
        self.BtnRotateLeft.setAutoFillBackground(False)
        self.BtnRotateLeft.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../utils/icons8.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("../utils/icons/icons8_1.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnRotateLeft.setIcon(icon1)
        self.BtnRotateLeft.setIconSize(QtCore.QSize(25, 25))
        self.BtnRotateLeft.setObjectName("BtnRotateLeft")
        self.BtnRotateRight = QtWidgets.QPushButton(self.tab_5)
        self.BtnRotateRight.setGeometry(QtCore.QRect(315, 425, 31, 31))
        self.BtnRotateRight.setToolTipDuration(3000)
        self.BtnRotateRight.setAutoFillBackground(False)
        self.BtnRotateRight.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../utils/icons8_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("../utils/icons/icons8_2.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnRotateRight.setIcon(icon2)
        self.BtnRotateRight.setIconSize(QtCore.QSize(25, 25))
        self.BtnRotateRight.setObjectName("BtnRotateRight")
        self.LbDesignDoc = QtWidgets.QLabel(self.tab_5)
        self.LbDesignDoc.setGeometry(QtCore.QRect(0, 0, 611, 416))
        self.LbDesignDoc.setText("")
        self.LbDesignDoc.setObjectName("LbDesignDoc")
        self.lineEditMass = QtWidgets.QLineEdit(self.tab_5)
        self.lineEditMass.setGeometry(QtCore.QRect(115, 430, 71, 20))
        self.lineEditMass.setText("")
        self.lineEditMass.setObjectName("lineEditMass")
        self.labelMass = QtWidgets.QLabel(self.tab_5)
        self.labelMass.setGeometry(QtCore.QRect(20, 435, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.labelMass.setFont(font)
        self.labelMass.setToolTipDuration(3000)
        self.labelMass.setObjectName("labelMass")
        self.BtnAddSheet = QtWidgets.QPushButton(self.tab_5)
        self.BtnAddSheet.setGeometry(QtCore.QRect(390, 425, 111, 31))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../utils/icons/plus-square-dotted.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnAddSheet.setIcon(icon3)
        self.BtnAddSheet.setObjectName("BtnAddSheet")
        self.BtnDeleteSheet = QtWidgets.QPushButton(self.tab_5)
        self.BtnDeleteSheet.setGeometry(QtCore.QRect(510, 425, 101, 31))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../utils/icons/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnDeleteSheet.setIcon(icon4)
        self.BtnDeleteSheet.setObjectName("BtnDeleteSheet")
        self.tabWidgetDecignDoc.addTab(self.tab_5, "")
        self.BtnRotateRight_2.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(1000, 5, 379, 536))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setStyleSheet("border-color: rgb(121, 121, 121);")
        self.label_6.setFrameShape(QtWidgets.QFrame.Box)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.labelEditDetailName = QtWidgets.QLabel(self.tab)
        self.labelEditDetailName.setGeometry(QtCore.QRect(660, 0, 191, 16))
        self.labelEditDetailName.setObjectName("labelEditDetailName")
        self.lineEditDetailName = QtWidgets.QLineEdit(self.tab)
        self.lineEditDetailName.setGeometry(QtCore.QRect(495, 25, 496, 26))
        self.lineEditDetailName.setObjectName("lineEditDetailName")
        self.BtnOpenDesignFile_2 = QtWidgets.QPushButton(self.tab)
        self.BtnOpenDesignFile_2.setGeometry(QtCore.QRect(380, 25, 106, 26))
        self.BtnOpenDesignFile_2.setToolTipDuration(3000)
        self.BtnOpenDesignFile_2.setIcon(icon)
        self.BtnOpenDesignFile_2.setIconSize(QtCore.QSize(20, 20))
        self.BtnOpenDesignFile_2.setObjectName("BtnOpenDesignFile_2")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(0, 50, 381, 491))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.radioButtonUnit_1_2 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButtonUnit_1_2.setGeometry(QtCore.QRect(10, 10, 361, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonUnit_1_2.setFont(font)
        self.radioButtonUnit_1_2.setObjectName("radioButtonUnit_1_2")
        self.radioButtonUnit_2_2 = QtWidgets.QRadioButton(self.frame_4)
        self.radioButtonUnit_2_2.setGeometry(QtCore.QRect(10, 45, 366, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonUnit_2_2.setFont(font)
        self.radioButtonUnit_2_2.setObjectName("radioButtonUnit_2_2")
        self.labelBelongingToAnAssemblyUnit_2 = QtWidgets.QLabel(self.tab)
        self.labelBelongingToAnAssemblyUnit_2.setGeometry(QtCore.QRect(10, 15, 156, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelBelongingToAnAssemblyUnit_2.setFont(font)
        self.labelBelongingToAnAssemblyUnit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBelongingToAnAssemblyUnit_2.setWordWrap(True)
        self.labelBelongingToAnAssemblyUnit_2.setObjectName("labelBelongingToAnAssemblyUnit_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_3.setGeometry(QtCore.QRect(380, 55, 621, 491))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.BtnRotateLeft_2 = QtWidgets.QPushButton(self.tab_6)
        self.BtnRotateLeft_2.setGeometry(QtCore.QRect(260, 425, 31, 31))
        self.BtnRotateLeft_2.setToolTipDuration(3000)
        self.BtnRotateLeft_2.setAutoFillBackground(False)
        self.BtnRotateLeft_2.setText("")
        self.BtnRotateLeft_2.setIcon(icon1)
        self.BtnRotateLeft_2.setIconSize(QtCore.QSize(25, 25))
        self.BtnRotateLeft_2.setObjectName("BtnRotateLeft_2")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(315, 425, 31, 31))
        self.pushButton_9.setToolTipDuration(3000)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.LbDesignDoc_2 = QtWidgets.QLabel(self.tab_6)
        self.LbDesignDoc_2.setGeometry(QtCore.QRect(0, 0, 616, 416))
        self.LbDesignDoc_2.setText("")
        self.LbDesignDoc_2.setPixmap(QtGui.QPixmap("../utils/drawings/KRS_1_7.jpg"))
        self.LbDesignDoc_2.setScaledContents(True)
        self.LbDesignDoc_2.setObjectName("LbDesignDoc_2")
        self.lineEditMass_2 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEditMass_2.setGeometry(QtCore.QRect(115, 430, 71, 20))
        self.lineEditMass_2.setText("")
        self.lineEditMass_2.setObjectName("lineEditMass_2")
        self.labelMass_2 = QtWidgets.QLabel(self.tab_6)
        self.labelMass_2.setGeometry(QtCore.QRect(5, 435, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.labelMass_2.setFont(font)
        self.labelMass_2.setToolTipDuration(3000)
        self.labelMass_2.setObjectName("labelMass_2")
        self.BtnAddSheet_2 = QtWidgets.QPushButton(self.tab_6)
        self.BtnAddSheet_2.setGeometry(QtCore.QRect(390, 425, 111, 31))
        self.BtnAddSheet_2.setIcon(icon3)
        self.BtnAddSheet_2.setObjectName("BtnAddSheet_2")
        self.BtnDeleteSheet_2 = QtWidgets.QPushButton(self.tab_6)
        self.BtnDeleteSheet_2.setGeometry(QtCore.QRect(510, 425, 101, 31))
        self.BtnDeleteSheet_2.setIcon(icon4)
        self.BtnDeleteSheet_2.setObjectName("BtnDeleteSheet_2")
        self.tabWidget_3.addTab(self.tab_6, "")
        self.BtnRotateRight_2.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(5, 5, 991, 531))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 972, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_17.setGeometry(QtCore.QRect(30, 190, 501, 21))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.frameLine = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameLine.setGeometry(QtCore.QRect(10, 10, 506, 21))
        self.frameLine.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLine.setObjectName("frameLine")
        self.frame_22 = QtWidgets.QFrame(self.frameLine)
        self.frame_22.setGeometry(QtCore.QRect(30, 0, 461, 20))
        self.frame_22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_22.setLineWidth(2)
        self.frame_22.setMidLineWidth(1)
        self.frame_22.setObjectName("frame_22")
        self.LbDocumentName = QtWidgets.QLabel(self.frame_22)
        self.LbDocumentName.setGeometry(QtCore.QRect(5, 2, 451, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LbDocumentName.setFont(font)
        self.LbDocumentName.setObjectName("LbDocumentName")
        self.label_customer_26 = QtWidgets.QLabel(self.frame_22)
        self.label_customer_26.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_26.setFont(font)
        self.label_customer_26.setObjectName("label_customer_26")
        self.LbDocumentCode = QtWidgets.QLabel(self.frameLine)
        self.LbDocumentCode.setGeometry(QtCore.QRect(0, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LbDocumentCode.setFont(font)
        self.LbDocumentCode.setObjectName("LbDocumentCode")
        self.frame_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_16.setGeometry(QtCore.QRect(30, 160, 506, 21))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_8.setGeometry(QtCore.QRect(30, 130, 501, 21))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_18.setGeometry(QtCore.QRect(30, 40, 501, 21))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.frame_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_19.setGeometry(QtCore.QRect(50, 100, 521, 21))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.frame_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_20.setGeometry(QtCore.QRect(50, 70, 521, 21))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BtnRotateRight_2.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.lineEditTag_1 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEditTag_1.setGeometry(QtCore.QRect(55, 20, 191, 20))
        self.lineEditTag_1.setText("")
        self.lineEditTag_1.setObjectName("lineEditTag_1")
        self.labelTag_1 = QtWidgets.QLabel(self.tab_4)
        self.labelTag_1.setGeometry(QtCore.QRect(25, 20, 31, 16))
        self.labelTag_1.setObjectName("labelTag_1")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_59.setGeometry(QtCore.QRect(585, -155, 211, 20))
        self.lineEdit_59.setText("")
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.BtnAddTag = QtWidgets.QPushButton(self.tab_4)
        self.BtnAddTag.setGeometry(QtCore.QRect(890, 20, 101, 23))
        self.BtnAddTag.setIcon(icon3)
        self.BtnAddTag.setObjectName("BtnAddTag")
        self.BtnRotateRight_2.addTab(self.tab_4, "")
        self.textEditComment = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditComment.setGeometry(QtCore.QRect(15, 625, 851, 96))
        self.textEditComment.setObjectName("textEditComment")
        self.labelComment = QtWidgets.QLabel(self.centralwidget)
        self.labelComment.setGeometry(QtCore.QRect(20, 605, 131, 16))
        self.labelComment.setObjectName("labelComment")
        self.BtnBack = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBack.setGeometry(QtCore.QRect(880, 625, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnBack.setFont(font)
        self.BtnBack.setObjectName("BtnBack")
        self.BtnSave = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSave.setGeometry(QtCore.QRect(880, 680, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnSave.setFont(font)
        self.BtnSave.setToolTipDuration(3000)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../utils/icons/floppy.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSave.setIcon(icon5)
        self.BtnSave.setIconSize(QtCore.QSize(20, 20))
        self.BtnSave.setObjectName("BtnSave")
        self.BtnAddDetail = QtWidgets.QPushButton(self.centralwidget)
        self.BtnAddDetail.setGeometry(QtCore.QRect(900, 10, 101, 23))
        self.BtnAddDetail.setObjectName("BtnAddDetail")
        self.BtnUnit = QtWidgets.QPushButton(self.centralwidget)
        self.BtnUnit.setGeometry(QtCore.QRect(780, 10, 111, 23))
        self.BtnUnit.setObjectName("BtnUnit")
        self.labelProductName = QtWidgets.QLabel(self.centralwidget)
        self.labelProductName.setGeometry(QtCore.QRect(15, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelProductName.setFont(font)
        self.labelProductName.setObjectName("labelProductName")
        self.lineEditProductName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditProductName.setGeometry(QtCore.QRect(150, 10, 606, 20))
        self.lineEditProductName.setObjectName("lineEditProductName")
        DesignDocumentFillingForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DesignDocumentFillingForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 21))
        self.menubar.setObjectName("menubar")
        DesignDocumentFillingForm.setMenuBar(self.menubar)

        self.retranslateUi(DesignDocumentFillingForm)
        self.BtnRotateRight_2.setCurrentIndex(2)
        self.tabWidgetDecignDoc.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DesignDocumentFillingForm)

    def retranslateUi(self, DesignDocumentFillingForm):
        _translate = QtCore.QCoreApplication.translate
        DesignDocumentFillingForm.setWindowTitle(_translate("DesignDocumentFillingForm", "Создание записи"))
        self.labelEditUnitName.setText(_translate("DesignDocumentFillingForm", "Введите название текущей сборочной единицы:"))
        self.labelBelongingToAnAssemblyUnit.setText(_translate("DesignDocumentFillingForm", "Принадлежность к сборочной единице:"))
        self.radioButtonUnit_1.setText(_translate("DesignDocumentFillingForm", "Сборочная единица 1"))
        self.radioButtonUnit_2.setText(_translate("DesignDocumentFillingForm", "Сборочная единица 2"))
        self.radioButtonSlave.setText(_translate("DesignDocumentFillingForm", "Подсборка"))
        self.radioButtonMain.setText(_translate("DesignDocumentFillingForm", "Главная"))
        self.BtnOpenDesignFile.setToolTip(_translate("DesignDocumentFillingForm", "Расположение файла изображения конструкторского документа"))
        self.BtnOpenDesignFile.setText(_translate("DesignDocumentFillingForm", "Файл чертежа"))
        self.BtnRotateLeft.setToolTip(_translate("DesignDocumentFillingForm", "Повернуть изображение влево"))
        self.BtnRotateRight.setToolTip(_translate("DesignDocumentFillingForm", "Повернуть изображение вправо"))
        self.labelMass.setToolTip(_translate("DesignDocumentFillingForm", "Длина детали"))
        self.labelMass.setText(_translate("DesignDocumentFillingForm", "Масса узла, кг"))
        self.BtnAddSheet.setText(_translate("DesignDocumentFillingForm", "Добавить лист"))
        self.BtnDeleteSheet.setText(_translate("DesignDocumentFillingForm", "Удалить лист"))
        self.tabWidgetDecignDoc.setTabText(self.tabWidgetDecignDoc.indexOf(self.tab_5), _translate("DesignDocumentFillingForm", "Чертёж 1"))
        self.BtnRotateRight_2.setTabText(self.BtnRotateRight_2.indexOf(self.tab_3), _translate("DesignDocumentFillingForm", "Сборочная единица"))
        self.labelEditDetailName.setText(_translate("DesignDocumentFillingForm", "Введите название текущей детали:"))
        self.BtnOpenDesignFile_2.setToolTip(_translate("DesignDocumentFillingForm", "Расположение файла изображения конструкторского документа"))
        self.BtnOpenDesignFile_2.setText(_translate("DesignDocumentFillingForm", "Файл чертежа"))
        self.radioButtonUnit_1_2.setText(_translate("DesignDocumentFillingForm", "Сборочная единица 1"))
        self.radioButtonUnit_2_2.setText(_translate("DesignDocumentFillingForm", "Сборочная единица 2"))
        self.labelBelongingToAnAssemblyUnit_2.setText(_translate("DesignDocumentFillingForm", "Принадлежность к сборочной единице:"))
        self.BtnRotateLeft_2.setToolTip(_translate("DesignDocumentFillingForm", "Повернуть изображение влево"))
        self.pushButton_9.setToolTip(_translate("DesignDocumentFillingForm", "Повернуть изображение вправо"))
        self.labelMass_2.setToolTip(_translate("DesignDocumentFillingForm", "Длина детали"))
        self.labelMass_2.setText(_translate("DesignDocumentFillingForm", "Масса детали, кг"))
        self.BtnAddSheet_2.setText(_translate("DesignDocumentFillingForm", "Добавить лист"))
        self.BtnDeleteSheet_2.setText(_translate("DesignDocumentFillingForm", "Удалить лист"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("DesignDocumentFillingForm", "Чертёж 1"))
        self.BtnRotateRight_2.setTabText(self.BtnRotateRight_2.indexOf(self.tab), _translate("DesignDocumentFillingForm", "Деталь 1"))
        self.LbDocumentName.setText(_translate("DesignDocumentFillingForm", "Сборочная единица"))
        self.label_customer_26.setText(_translate("DesignDocumentFillingForm", "1000"))
        self.LbDocumentCode.setText(_translate("DesignDocumentFillingForm", "СБ"))
        self.BtnRotateRight_2.setTabText(self.BtnRotateRight_2.indexOf(self.tab_2), _translate("DesignDocumentFillingForm", "Структура"))
        self.labelTag_1.setText(_translate("DesignDocumentFillingForm", "Тег 1"))
        self.BtnAddTag.setText(_translate("DesignDocumentFillingForm", "Добавить тег"))
        self.BtnRotateRight_2.setTabText(self.BtnRotateRight_2.indexOf(self.tab_4), _translate("DesignDocumentFillingForm", "Теги"))
        self.labelComment.setText(_translate("DesignDocumentFillingForm", "Комментарий"))
        self.BtnBack.setText(_translate("DesignDocumentFillingForm", "Назад"))
        self.BtnSave.setToolTip(_translate("DesignDocumentFillingForm", "Сохранить документ"))
        self.BtnSave.setText(_translate("DesignDocumentFillingForm", "Сохранить"))
        self.BtnAddDetail.setText(_translate("DesignDocumentFillingForm", "Добавить деталь"))
        self.BtnUnit.setText(_translate("DesignDocumentFillingForm", "Сборочная единица"))
        self.labelProductName.setText(_translate("DesignDocumentFillingForm", "Название изделия"))

class DesignDocumentFillingForm(QtWidgets.QMainWindow):
    def __init__(self, parent):
        super().__init__()
        self.ui = Ui_DesignDocumentFillingForm()
        self.ui.setupUi(self)
        self.parent = parent  # Сохраняем ссылку на родительское окно


        self.ui.BtnBack.clicked.connect(self.go_back)

    def go_back(self):
        self.parent.show()  # Показываем родительское окно
        self.close()  # Закрываем дочернее окно

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DesignDocumentFillingForm = QtWidgets.QMainWindow()
    ui = Ui_DesignDocumentFillingForm()
    ui.setupUi(DesignDocumentFillingForm)
    DesignDocumentFillingForm.show()
    sys.exit(app.exec_())
