
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(787, 683)
        MainWindow.setMinimumSize(QtCore.QSize(787, 670))
        MainWindow.setMaximumSize(QtCore.QSize(787, 20000))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidgetMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetMain.setEnabled(True)
        self.tabWidgetMain.setGeometry(QtCore.QRect(0, 10, 781, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidgetMain.sizePolicy().hasHeightForWidth())
        self.tabWidgetMain.setSizePolicy(sizePolicy)
        self.tabWidgetMain.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.tabWidgetMain.setObjectName("tabWidgetMain")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frameTerm = QtWidgets.QFrame(self.tab)
        self.frameTerm.setGeometry(QtCore.QRect(45, 510, 176, 26))
        self.frameTerm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameTerm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTerm.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameTerm.setLineWidth(4)
        self.frameTerm.setMidLineWidth(3)
        self.frameTerm.setObjectName("frameTerm")
        self.frame_14 = QtWidgets.QFrame(self.tab)
        self.frame_14.setGeometry(QtCore.QRect(10, 10, 751, 491))
        self.frame_14.setStyleSheet("background-color: rgb(247, 247, 247);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frameDate = QtWidgets.QFrame(self.frame_14)
        self.frameDate.setGeometry(QtCore.QRect(480, 10, 101, 21))
        self.frameDate.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameDate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameDate.setLineWidth(4)
        self.frameDate.setMidLineWidth(3)
        self.frameDate.setObjectName("frameDate")
        self.LbDate = QtWidgets.QLabel(self.frameDate)
        self.LbDate.setGeometry(QtCore.QRect(4, 1, 91, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LbDate.setFont(font)
        self.LbDate.setObjectName("LbDate")
        self.labelFrom = QtWidgets.QLabel(self.frame_14)
        self.labelFrom.setGeometry(QtCore.QRect(440, 15, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelFrom.setFont(font)
        self.labelFrom.setObjectName("labelFrom")
        self.LbOrderNumber = QtWidgets.QLabel(self.frame_14)
        self.LbOrderNumber.setGeometry(QtCore.QRect(110, 10, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LbOrderNumber.setFont(font)
        self.LbOrderNumber.setObjectName("LbOrderNumber")
        self.frameCustomer = QtWidgets.QFrame(self.frame_14)
        self.frameCustomer.setGeometry(QtCore.QRect(120, 40, 611, 31))
        self.frameCustomer.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameCustomer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameCustomer.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameCustomer.setLineWidth(4)
        self.frameCustomer.setMidLineWidth(3)
        self.frameCustomer.setObjectName("frameCustomer")
        self.LbCustomer_2 = QtWidgets.QLabel(self.frameCustomer)
        self.LbCustomer_2.setGeometry(QtCore.QRect(4, 1, 601, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LbCustomer_2.setFont(font)
        self.LbCustomer_2.setObjectName("LbCustomer_2")
        self.labelCustomer = QtWidgets.QLabel(self.frame_14)
        self.labelCustomer.setGeometry(QtCore.QRect(30, 42, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelCustomer.setFont(font)
        self.labelCustomer.setObjectName("labelCustomer")
        self.tabWidgetDetail = QtWidgets.QTabWidget(self.frame_14)
        self.tabWidgetDetail.setGeometry(QtCore.QRect(0, 70, 751, 421))
        self.tabWidgetDetail.setObjectName("tabWidgetDetail")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.frameProductName = QtWidgets.QFrame(self.tab_10)
        self.frameProductName.setGeometry(QtCore.QRect(140, 10, 591, 31))
        self.frameProductName.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameProductName.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameProductName.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameProductName.setLineWidth(4)
        self.frameProductName.setMidLineWidth(3)
        self.frameProductName.setObjectName("frameProductName")
        self.LbProductName_2 = QtWidgets.QLabel(self.frameProductName)
        self.LbProductName_2.setGeometry(QtCore.QRect(4, 1, 581, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LbProductName_2.setFont(font)
        self.LbProductName_2.setObjectName("LbProductName_2")
        self.labelToProdQuantity = QtWidgets.QLabel(self.tab_10)
        self.labelToProdQuantity.setGeometry(QtCore.QRect(300, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelToProdQuantity.setFont(font)
        self.labelToProdQuantity.setObjectName("labelToProdQuantity")
        self.labelQuantity_2 = QtWidgets.QLabel(self.tab_10)
        self.labelQuantity_2.setGeometry(QtCore.QRect(10, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelQuantity_2.setFont(font)
        self.labelQuantity_2.setObjectName("labelQuantity_2")
        self.labelThings = QtWidgets.QLabel(self.tab_10)
        self.labelThings.setGeometry(QtCore.QRect(230, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelThings.setFont(font)
        self.labelThings.setObjectName("labelThings")
        self.frameMaterialGOST_3 = QtWidgets.QFrame(self.tab_10)
        self.frameMaterialGOST_3.setGeometry(QtCore.QRect(140, 110, 471, 31))
        self.frameMaterialGOST_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameMaterialGOST_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMaterialGOST_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMaterialGOST_3.setLineWidth(4)
        self.frameMaterialGOST_3.setMidLineWidth(3)
        self.frameMaterialGOST_3.setObjectName("frameMaterialGOST_3")
        self.LbMaterialGOST_3 = QtWidgets.QLabel(self.frameMaterialGOST_3)
        self.LbMaterialGOST_3.setGeometry(QtCore.QRect(4, 1, 461, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LbMaterialGOST_3.setFont(font)
        self.LbMaterialGOST_3.setObjectName("LbMaterialGOST_3")
        self.frame_7 = QtWidgets.QFrame(self.tab_10)
        self.frame_7.setGeometry(QtCore.QRect(300, 70, 81, 31))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setLineWidth(4)
        self.frame_7.setMidLineWidth(3)
        self.frame_7.setObjectName("frame_7")
        self.LbToProdQuantity = QtWidgets.QLabel(self.frame_7)
        self.LbToProdQuantity.setGeometry(QtCore.QRect(4, 1, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LbToProdQuantity.setFont(font)
        self.LbToProdQuantity.setObjectName("LbToProdQuantity")
        self.labelMaterial_2 = QtWidgets.QLabel(self.tab_10)
        self.labelMaterial_2.setGeometry(QtCore.QRect(10, 110, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelMaterial_2.setFont(font)
        self.labelMaterial_2.setObjectName("labelMaterial_2")
        self.labelByOrderQuantity = QtWidgets.QLabel(self.tab_10)
        self.labelByOrderQuantity.setGeometry(QtCore.QRect(140, 50, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelByOrderQuantity.setFont(font)
        self.labelByOrderQuantity.setObjectName("labelByOrderQuantity")
        self.frame_3 = QtWidgets.QFrame(self.tab_10)
        self.frame_3.setGeometry(QtCore.QRect(140, 70, 81, 31))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setLineWidth(4)
        self.frame_3.setMidLineWidth(3)
        self.frame_3.setObjectName("frame_3")
        self.LbByOrderQuantity = QtWidgets.QLabel(self.frame_3)
        self.LbByOrderQuantity.setGeometry(QtCore.QRect(4, 1, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LbByOrderQuantity.setFont(font)
        self.LbByOrderQuantity.setObjectName("LbByOrderQuantity")
        self.labelProductName = QtWidgets.QLabel(self.tab_10)
        self.labelProductName.setGeometry(QtCore.QRect(10, 12, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.labelProductName.setFont(font)
        self.labelProductName.setObjectName("labelProductName")
        self.labelThings_2 = QtWidgets.QLabel(self.tab_10)
        self.labelThings_2.setGeometry(QtCore.QRect(390, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelThings_2.setFont(font)
        self.labelThings_2.setObjectName("labelThings_2")
        self.scrollAreaIssueMaterial = QtWidgets.QScrollArea(self.tab_10)
        self.scrollAreaIssueMaterial.setGeometry(QtCore.QRect(0, 160, 741, 231))
        self.scrollAreaIssueMaterial.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollAreaIssueMaterial.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollAreaIssueMaterial.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollAreaIssueMaterial.setWidgetResizable(False)
        self.scrollAreaIssueMaterial.setObjectName("scrollAreaIssueMaterial")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 712, 569))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 711, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("background-color: rgb(247, 247, 247);\n"
"")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.frameFormDimensionGOST_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frameFormDimensionGOST_2.setGeometry(QtCore.QRect(100, 10, 391, 25))
        self.frameFormDimensionGOST_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameFormDimensionGOST_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameFormDimensionGOST_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameFormDimensionGOST_2.setLineWidth(4)
        self.frameFormDimensionGOST_2.setMidLineWidth(3)
        self.frameFormDimensionGOST_2.setObjectName("frameFormDimensionGOST_2")
        self.LbFormDimensionGOST_2 = QtWidgets.QLabel(self.frameFormDimensionGOST_2)
        self.LbFormDimensionGOST_2.setGeometry(QtCore.QRect(8, 1, 376, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LbFormDimensionGOST_2.setFont(font)
        self.LbFormDimensionGOST_2.setObjectName("LbFormDimensionGOST_2")
        self.frameMaterialGOST_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frameMaterialGOST_2.setGeometry(QtCore.QRect(100, 35, 391, 25))
        self.frameMaterialGOST_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameMaterialGOST_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMaterialGOST_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMaterialGOST_2.setLineWidth(4)
        self.frameMaterialGOST_2.setMidLineWidth(3)
        self.frameMaterialGOST_2.setObjectName("frameMaterialGOST_2")
        self.LbMaterialGOST_2 = QtWidgets.QLabel(self.frameMaterialGOST_2)
        self.LbMaterialGOST_2.setGeometry(QtCore.QRect(8, 1, 376, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LbMaterialGOST_2.setFont(font)
        self.LbMaterialGOST_2.setObjectName("LbMaterialGOST_2")
        self.frameForm_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frameForm_2.setGeometry(QtCore.QRect(20, 10, 81, 50))
        self.frameForm_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameForm_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameForm_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameForm_2.setLineWidth(4)
        self.frameForm_2.setMidLineWidth(3)
        self.frameForm_2.setObjectName("frameForm_2")
        self.LbForm_2 = QtWidgets.QLabel(self.frameForm_2)
        self.LbForm_2.setGeometry(QtCore.QRect(4, 10, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbForm_2.setFont(font)
        self.LbForm_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LbForm_2.setObjectName("LbForm_2")
        self.frameDimensionsOfMaterial_2 = QtWidgets.QFrame(self.groupBox_2)
        self.frameDimensionsOfMaterial_2.setGeometry(QtCore.QRect(490, 10, 221, 50))
        self.frameDimensionsOfMaterial_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameDimensionsOfMaterial_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDimensionsOfMaterial_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameDimensionsOfMaterial_2.setLineWidth(4)
        self.frameDimensionsOfMaterial_2.setMidLineWidth(3)
        self.frameDimensionsOfMaterial_2.setObjectName("frameDimensionsOfMaterial_2")
        self.LbDimensionsOfMaterial_2 = QtWidgets.QLabel(self.frameDimensionsOfMaterial_2)
        self.LbDimensionsOfMaterial_2.setGeometry(QtCore.QRect(4, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.LbDimensionsOfMaterial_2.setFont(font)
        self.LbDimensionsOfMaterial_2.setAlignment(QtCore.Qt.AlignCenter)
        self.LbDimensionsOfMaterial_2.setObjectName("LbDimensionsOfMaterial_2")
        self.scrollAreaIssueMaterial.setWidget(self.scrollAreaWidgetContents_2)
        self.labelIssueMaterial = QtWidgets.QLabel(self.tab_10)
        self.labelIssueMaterial.setGeometry(QtCore.QRect(230, 150, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelIssueMaterial.setFont(font)
        self.labelIssueMaterial.setObjectName("labelIssueMaterial")
        self.tabWidgetDetail.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidgetDetail.addTab(self.tab_11, "")
        self.LbTerm = QtWidgets.QLabel(self.tab)
        self.LbTerm.setGeometry(QtCore.QRect(55, 515, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbTerm.setFont(font)
        self.LbTerm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LbTerm.setObjectName("LbTerm")
        self.tabWidgetMain.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidgetTechnologicPassport = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidgetTechnologicPassport.setGeometry(QtCore.QRect(10, 9, 751, 551))
        self.tabWidgetTechnologicPassport.setObjectName("tabWidgetTechnologicPassport")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_8)
        self.scrollArea.setGeometry(QtCore.QRect(0, 20, 741, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 742, 4998))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame_12 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_12.setGeometry(QtCore.QRect(10, 10, 701, 51))
        self.frame_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.line = QtWidgets.QFrame(self.frame_12)
        self.line.setGeometry(QtCore.QRect(30, 0, 21, 51))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame_12)
        self.line_2.setGeometry(QtCore.QRect(180, 0, 21, 51))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.LbNumber = QtWidgets.QLabel(self.frame_12)
        self.LbNumber.setGeometry(QtCore.QRect(10, 10, 21, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbNumber.setFont(font)
        self.LbNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.LbNumber.setObjectName("LbNumber")
        self.LbOperation = QtWidgets.QLabel(self.frame_12)
        self.LbOperation.setGeometry(QtCore.QRect(50, 10, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbOperation.setFont(font)
        self.LbOperation.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.LbOperation.setWordWrap(True)
        self.LbOperation.setObjectName("LbOperation")
        self.LbWorks = QtWidgets.QLabel(self.frame_12)
        self.LbWorks.setGeometry(QtCore.QRect(200, 10, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbWorks.setFont(font)
        self.LbWorks.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.LbWorks.setWordWrap(True)
        self.LbWorks.setObjectName("LbWorks")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.labelOperation = QtWidgets.QLabel(self.tab_8)
        self.labelOperation.setGeometry(QtCore.QRect(81, 1, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelOperation.setFont(font)
        self.labelOperation.setObjectName("labelOperation")
        self.labelWorks = QtWidgets.QLabel(self.tab_8)
        self.labelWorks.setGeometry(QtCore.QRect(411, 1, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelWorks.setFont(font)
        self.labelWorks.setObjectName("labelWorks")
        self.labelNumber = QtWidgets.QLabel(self.tab_8)
        self.labelNumber.setGeometry(QtCore.QRect(21, 1, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelNumber.setFont(font)
        self.labelNumber.setObjectName("labelNumber")
        self.tabWidgetTechnologicPassport.addTab(self.tab_8, "")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_4.setGeometry(QtCore.QRect(650, 580, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setText("Назад")
        self.pushButton_4.setObjectName("pushButton_4")
        self.tabWidgetMain.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidgetNorms = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidgetNorms.setGeometry(QtCore.QRect(10, 10, 751, 411))
        self.tabWidgetNorms.setObjectName("tabWidgetNorms")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.groupBoxNorms = QtWidgets.QGroupBox(self.tab_9)
        self.groupBoxNorms.setGeometry(QtCore.QRect(0, 0, 751, 386))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxNorms.setFont(font)
        self.groupBoxNorms.setStyleSheet("background-color: rgb(238, 238, 238);")
        self.groupBoxNorms.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxNorms.setFlat(False)
        self.groupBoxNorms.setCheckable(False)
        self.groupBoxNorms.setObjectName("groupBoxNorms")
        self.labelNormUnitProd = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelNormUnitProd.setGeometry(QtCore.QRect(20, 60, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNormUnitProd.setFont(font)
        self.labelNormUnitProd.setWordWrap(True)
        self.labelNormUnitProd.setObjectName("labelNormUnitProd")
        self.frameOneUnitNormMass = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameOneUnitNormMass.setGeometry(QtCore.QRect(140, 60, 121, 41))
        self.frameOneUnitNormMass.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameOneUnitNormMass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOneUnitNormMass.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameOneUnitNormMass.setLineWidth(4)
        self.frameOneUnitNormMass.setMidLineWidth(3)
        self.frameOneUnitNormMass.setObjectName("frameOneUnitNormMass")
        self.LbOneUnitNormMass = QtWidgets.QLabel(self.frameOneUnitNormMass)
        self.LbOneUnitNormMass.setGeometry(QtCore.QRect(4, 3, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LbOneUnitNormMass.setFont(font)
        self.LbOneUnitNormMass.setObjectName("LbOneUnitNormMass")
        self.frameOneUnitNormVolume = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameOneUnitNormVolume.setGeometry(QtCore.QRect(140, 100, 121, 41))
        self.frameOneUnitNormVolume.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameOneUnitNormVolume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOneUnitNormVolume.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameOneUnitNormVolume.setLineWidth(4)
        self.frameOneUnitNormVolume.setMidLineWidth(3)
        self.frameOneUnitNormVolume.setObjectName("frameOneUnitNormVolume")
        self.LbOneUnitNormVolume = QtWidgets.QLabel(self.frameOneUnitNormVolume)
        self.LbOneUnitNormVolume.setGeometry(QtCore.QRect(4, 3, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LbOneUnitNormVolume.setFont(font)
        self.LbOneUnitNormVolume.setObjectName("LbOneUnitNormVolume")
        self.frameOneUnitNormLength = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameOneUnitNormLength.setGeometry(QtCore.QRect(140, 140, 121, 41))
        self.frameOneUnitNormLength.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameOneUnitNormLength.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOneUnitNormLength.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameOneUnitNormLength.setLineWidth(4)
        self.frameOneUnitNormLength.setMidLineWidth(3)
        self.frameOneUnitNormLength.setObjectName("frameOneUnitNormLength")
        self.LbOneUnitNormLength = QtWidgets.QLabel(self.frameOneUnitNormLength)
        self.LbOneUnitNormLength.setGeometry(QtCore.QRect(4, 3, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LbOneUnitNormLength.setFont(font)
        self.LbOneUnitNormLength.setObjectName("LbOneUnitNormLength")
        self.labelOneUnitNormMassKg = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelOneUnitNormMassKg.setGeometry(QtCore.QRect(270, 60, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelOneUnitNormMassKg.setFont(font)
        self.labelOneUnitNormMassKg.setObjectName("labelOneUnitNormMassKg")
        self.labelOneUnitNormVolume = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelOneUnitNormVolume.setGeometry(QtCore.QRect(270, 100, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelOneUnitNormVolume.setFont(font)
        self.labelOneUnitNormVolume.setObjectName("labelOneUnitNormVolume")
        self.labelOneUnitNormLength = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelOneUnitNormLength.setGeometry(QtCore.QRect(270, 140, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelOneUnitNormLength.setFont(font)
        self.labelOneUnitNormLength.setObjectName("labelOneUnitNormLength")
        self.labelMaterial = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelMaterial.setGeometry(QtCore.QRect(20, 223, 71, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelMaterial.setFont(font)
        self.labelMaterial.setWordWrap(True)
        self.labelMaterial.setObjectName("labelMaterial")
        self.frameDimensionsOfMaterial = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameDimensionsOfMaterial.setGeometry(QtCore.QRect(540, 220, 181, 61))
        self.frameDimensionsOfMaterial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameDimensionsOfMaterial.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameDimensionsOfMaterial.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameDimensionsOfMaterial.setLineWidth(4)
        self.frameDimensionsOfMaterial.setMidLineWidth(3)
        self.frameDimensionsOfMaterial.setObjectName("frameDimensionsOfMaterial")
        self.LbDimensionsOfMaterial = QtWidgets.QLabel(self.frameDimensionsOfMaterial)
        self.LbDimensionsOfMaterial.setGeometry(QtCore.QRect(4, 10, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbDimensionsOfMaterial.setFont(font)
        self.LbDimensionsOfMaterial.setAlignment(QtCore.Qt.AlignCenter)
        self.LbDimensionsOfMaterial.setObjectName("LbDimensionsOfMaterial")
        self.labelAllNormLength = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelAllNormLength.setGeometry(QtCore.QRect(700, 140, 16, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelAllNormLength.setFont(font)
        self.labelAllNormLength.setObjectName("labelAllNormLength")
        self.labelNormAllProd = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelNormAllProd.setGeometry(QtCore.QRect(450, 60, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNormAllProd.setFont(font)
        self.labelNormAllProd.setWordWrap(True)
        self.labelNormAllProd.setObjectName("labelNormAllProd")
        self.labelAllNormVolume = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelAllNormVolume.setGeometry(QtCore.QRect(700, 100, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelAllNormVolume.setFont(font)
        self.labelAllNormVolume.setObjectName("labelAllNormVolume")
        self.frameAllNormLength = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameAllNormLength.setGeometry(QtCore.QRect(570, 140, 121, 41))
        self.frameAllNormLength.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameAllNormLength.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAllNormLength.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameAllNormLength.setLineWidth(4)
        self.frameAllNormLength.setMidLineWidth(3)
        self.frameAllNormLength.setObjectName("frameAllNormLength")
        self.LbAllNormLength = QtWidgets.QLabel(self.frameAllNormLength)
        self.LbAllNormLength.setGeometry(QtCore.QRect(4, 3, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LbAllNormLength.setFont(font)
        self.LbAllNormLength.setObjectName("LbAllNormLength")
        self.frameAllNormVolume = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameAllNormVolume.setGeometry(QtCore.QRect(570, 100, 121, 41))
        self.frameAllNormVolume.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameAllNormVolume.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAllNormVolume.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameAllNormVolume.setLineWidth(4)
        self.frameAllNormVolume.setMidLineWidth(3)
        self.frameAllNormVolume.setObjectName("frameAllNormVolume")
        self.LbAllNormVolume = QtWidgets.QLabel(self.frameAllNormVolume)
        self.LbAllNormVolume.setGeometry(QtCore.QRect(4, 3, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LbAllNormVolume.setFont(font)
        self.LbAllNormVolume.setObjectName("LbAllNormVolume")
        self.labelAllNormMassKg = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelAllNormMassKg.setGeometry(QtCore.QRect(700, 60, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelAllNormMassKg.setFont(font)
        self.labelAllNormMassKg.setObjectName("labelAllNormMassKg")
        self.frameAllNormMass = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameAllNormMass.setGeometry(QtCore.QRect(570, 60, 121, 41))
        self.frameAllNormMass.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameAllNormMass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameAllNormMass.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameAllNormMass.setLineWidth(4)
        self.frameAllNormMass.setMidLineWidth(3)
        self.frameAllNormMass.setObjectName("frameAllNormMass")
        self.LbAllNormMass = QtWidgets.QLabel(self.frameAllNormMass)
        self.LbAllNormMass.setGeometry(QtCore.QRect(4, 3, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LbAllNormMass.setFont(font)
        self.LbAllNormMass.setObjectName("LbAllNormMass")
        self.labelOneDetailMass = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelOneDetailMass.setGeometry(QtCore.QRect(20, 310, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelOneDetailMass.setFont(font)
        self.labelOneDetailMass.setWordWrap(True)
        self.labelOneDetailMass.setObjectName("labelOneDetailMass")
        self.labelOneDetailMassKg = QtWidgets.QLabel(self.groupBoxNorms)
        self.labelOneDetailMassKg.setGeometry(QtCore.QRect(270, 320, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelOneDetailMassKg.setFont(font)
        self.labelOneDetailMassKg.setObjectName("labelOneDetailMassKg")
        self.frameOneDetailMass = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameOneDetailMass.setGeometry(QtCore.QRect(140, 320, 121, 41))
        self.frameOneDetailMass.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameOneDetailMass.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOneDetailMass.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameOneDetailMass.setLineWidth(4)
        self.frameOneDetailMass.setMidLineWidth(3)
        self.frameOneDetailMass.setObjectName("frameOneDetailMass")
        self.LbOneDetailMass = QtWidgets.QLabel(self.frameOneDetailMass)
        self.LbOneDetailMass.setGeometry(QtCore.QRect(4, 3, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LbOneDetailMass.setFont(font)
        self.LbOneDetailMass.setObjectName("LbOneDetailMass")
        self.frameForm = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameForm.setGeometry(QtCore.QRect(130, 220, 121, 61))
        self.frameForm.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameForm.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameForm.setLineWidth(4)
        self.frameForm.setMidLineWidth(3)
        self.frameForm.setObjectName("frameForm")
        self.LbForm = QtWidgets.QLabel(self.frameForm)
        self.LbForm.setGeometry(QtCore.QRect(10, 10, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.LbForm.setFont(font)
        self.LbForm.setAlignment(QtCore.Qt.AlignCenter)
        self.LbForm.setObjectName("LbForm")
        self.FormDimensionGOST = QtWidgets.QFrame(self.groupBoxNorms)
        self.FormDimensionGOST.setGeometry(QtCore.QRect(250, 220, 281, 31))
        self.FormDimensionGOST.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.FormDimensionGOST.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FormDimensionGOST.setFrameShadow(QtWidgets.QFrame.Plain)
        self.FormDimensionGOST.setLineWidth(4)
        self.FormDimensionGOST.setMidLineWidth(3)
        self.FormDimensionGOST.setObjectName("FormDimensionGOST")
        self.LbFormDimensionGOST = QtWidgets.QLabel(self.FormDimensionGOST)
        self.LbFormDimensionGOST.setGeometry(QtCore.QRect(8, 5, 200, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LbFormDimensionGOST.setFont(font)
        self.LbFormDimensionGOST.setObjectName("LbFormDimensionGOST")
        self.frameMaterialGOST = QtWidgets.QFrame(self.groupBoxNorms)
        self.frameMaterialGOST.setGeometry(QtCore.QRect(250, 250, 281, 31))
        self.frameMaterialGOST.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frameMaterialGOST.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameMaterialGOST.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frameMaterialGOST.setLineWidth(4)
        self.frameMaterialGOST.setMidLineWidth(3)
        self.frameMaterialGOST.setObjectName("frameMaterialGOST")
        self.LbMaterialGOST = QtWidgets.QLabel(self.frameMaterialGOST)
        self.LbMaterialGOST.setGeometry(QtCore.QRect(8, 5, 200, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LbMaterialGOST.setFont(font)
        self.LbMaterialGOST.setObjectName("LbMaterialGOST")
        self.tabWidgetNorms.addTab(self.tab_9, "")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 580, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setText("Назад")
        self.pushButton_5.setObjectName("pushButton_5")
        self.tabWidgetMain.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidgetDrawings = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidgetDrawings.setGeometry(QtCore.QRect(10, 5, 751, 551))
        self.tabWidgetDrawings.setObjectName("tabWidgetDrawings")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.LbDrawing = QtWidgets.QLabel(self.tab_6)
        self.LbDrawing.setGeometry(QtCore.QRect(0, 0, 741, 523))
        self.LbDrawing.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.LbDrawing.setText("")
        self.LbDrawing.setPixmap(QtGui.QPixmap("../utils/drawings/KRS_1_7.jpg"))
        self.LbDrawing.setScaledContents(True)
        self.LbDrawing.setObjectName("LbDrawing")
        self.tabWidgetDrawings.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidgetDrawings.addTab(self.tab_7, "")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_6.setGeometry(QtCore.QRect(650, 580, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setText("Назад")
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidgetMain.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_7.setGeometry(QtCore.QRect(650, 580, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setText("Назад")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tabWidgetLabels = QtWidgets.QTabWidget(self.tab_5)
        self.tabWidgetLabels.setGeometry(QtCore.QRect(0, 0, 776, 556))
        self.tabWidgetLabels.setObjectName("tabWidgetLabels")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.frame_11 = QtWidgets.QFrame(self.tab_12)
        self.frame_11.setGeometry(QtCore.QRect(45, 20, 681, 371))
        self.frame_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.LbProductName = QtWidgets.QLabel(self.frame_11)
        self.LbProductName.setGeometry(QtCore.QRect(30, 105, 336, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.LbProductName.setFont(font)
        self.LbProductName.setObjectName("LbProductName")
        self.labelOurSite = QtWidgets.QLabel(self.frame_11)
        self.labelOurSite.setGeometry(QtCore.QRect(510, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelOurSite.setFont(font)
        self.labelOurSite.setObjectName("labelOurSite")
        self.LbQRCode = QtWidgets.QLabel(self.frame_11)
        self.LbQRCode.setGeometry(QtCore.QRect(465, 40, 176, 176))
        self.LbQRCode.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.LbQRCode.setText("")
        self.LbQRCode.setPixmap(QtGui.QPixmap("pic/our_website.png"))
        self.LbQRCode.setScaledContents(True)
        self.LbQRCode.setObjectName("LbQRCode")
        self.labelMassNetto = QtWidgets.QLabel(self.frame_11)
        self.labelMassNetto.setGeometry(QtCore.QRect(495, 225, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelMassNetto.setFont(font)
        self.labelMassNetto.setObjectName("labelMassNetto")
        self.LbCustomer = QtWidgets.QLabel(self.frame_11)
        self.LbCustomer.setGeometry(QtCore.QRect(30, 135, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbCustomer.setFont(font)
        self.LbCustomer.setObjectName("LbCustomer")
        self.LbMassNetto = QtWidgets.QLabel(self.frame_11)
        self.LbMassNetto.setGeometry(QtCore.QRect(495, 250, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.LbMassNetto.setFont(font)
        self.LbMassNetto.setObjectName("LbMassNetto")
        self.LbSignE = QtWidgets.QLabel(self.frame_11)
        self.LbSignE.setGeometry(QtCore.QRect(570, 245, 30, 30))
        self.LbSignE.setText("")
        self.LbSignE.setPixmap(QtGui.QPixmap("../utils/pic/Antech_ru_020_Ves_Netto_(e).jpg"))
        self.LbSignE.setScaledContents(True)
        self.LbSignE.setObjectName("LbSignE")
        self.labelLogo = QtWidgets.QLabel(self.frame_11)
        self.labelLogo.setGeometry(QtCore.QRect(0, 0, 131, 66))
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap("../utils/pic/Эмблема.png"))
        self.labelLogo.setScaledContents(True)
        self.labelLogo.setObjectName("labelLogo")
        self.labelGrifAgro = QtWidgets.QLabel(self.frame_11)
        self.labelGrifAgro.setGeometry(QtCore.QRect(135, 15, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        self.labelGrifAgro.setFont(font)
        self.labelGrifAgro.setObjectName("labelGrifAgro")
        self.labelAddres = QtWidgets.QLabel(self.frame_11)
        self.labelAddres.setGeometry(QtCore.QRect(140, 40, 231, 19))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(False)
        self.labelAddres.setFont(font)
        self.labelAddres.setObjectName("labelAddres")
        self.LbQuantity = QtWidgets.QLabel(self.frame_11)
        self.LbQuantity.setGeometry(QtCore.QRect(30, 160, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbQuantity.setFont(font)
        self.LbQuantity.setObjectName("LbQuantity")
        self.LbTotalBatchQuantity = QtWidgets.QLabel(self.frame_11)
        self.LbTotalBatchQuantity.setGeometry(QtCore.QRect(30, 185, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbTotalBatchQuantity.setFont(font)
        self.LbTotalBatchQuantity.setObjectName("LbTotalBatchQuantity")
        self.LbPacker = QtWidgets.QLabel(self.frame_11)
        self.LbPacker.setGeometry(QtCore.QRect(30, 210, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbPacker.setFont(font)
        self.LbPacker.setObjectName("LbPacker")
        self.labelManufactureDate = QtWidgets.QLabel(self.frame_11)
        self.labelManufactureDate.setGeometry(QtCore.QRect(30, 235, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelManufactureDate.setFont(font)
        self.labelManufactureDate.setObjectName("labelManufactureDate")
        self.LbManufactureDate = QtWidgets.QLabel(self.frame_11)
        self.LbManufactureDate.setGeometry(QtCore.QRect(30, 260, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbManufactureDate.setFont(font)
        self.LbManufactureDate.setObjectName("LbManufactureDate")
        self.LbUmbrella = QtWidgets.QLabel(self.frame_11)
        self.LbUmbrella.setGeometry(QtCore.QRect(420, 290, 71, 66))
        self.LbUmbrella.setText("")
        self.LbUmbrella.setPixmap(QtGui.QPixmap("../utils/pic/Berech_ot_vlagi.jpg"))
        self.LbUmbrella.setScaledContents(True)
        self.LbUmbrella.setObjectName("LbUmbrella")
        self.LbEmptyBox = QtWidgets.QLabel(self.frame_11)
        self.LbEmptyBox.setGeometry(QtCore.QRect(30, 290, 341, 66))
        self.LbEmptyBox.setFrameShape(QtWidgets.QFrame.Box)
        self.LbEmptyBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.LbEmptyBox.setLineWidth(2)
        self.LbEmptyBox.setMidLineWidth(3)
        self.LbEmptyBox.setText("")
        self.LbEmptyBox.setScaledContents(False)
        self.LbEmptyBox.setObjectName("LbEmptyBox")
        self.LbOrderNumberAndDate = QtWidgets.QLabel(self.frame_11)
        self.LbOrderNumberAndDate.setGeometry(QtCore.QRect(30, 80, 326, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LbOrderNumberAndDate.setFont(font)
        self.LbOrderNumberAndDate.setObjectName("LbOrderNumberAndDate")
        self.LbSignE.raise_()
        self.labelLogo.raise_()
        self.labelGrifAgro.raise_()
        self.labelAddres.raise_()
        self.LbTotalBatchQuantity.raise_()
        self.LbPacker.raise_()
        self.labelManufactureDate.raise_()
        self.LbManufactureDate.raise_()
        self.LbUmbrella.raise_()
        self.LbEmptyBox.raise_()
        self.labelOurSite.raise_()
        self.LbQRCode.raise_()
        self.labelMassNetto.raise_()
        self.LbCustomer.raise_()
        self.LbProductName.raise_()
        self.LbQuantity.raise_()
        self.LbMassNetto.raise_()
        self.LbOrderNumberAndDate.raise_()
        self.dateEditDateProd = QtWidgets.QDateEdit(self.tab_12)
        self.dateEditDateProd.setGeometry(QtCore.QRect(595, 420, 86, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dateEditDateProd.setFont(font)
        self.dateEditDateProd.setStyleSheet("")
        self.dateEditDateProd.setCalendarPopup(True)
        self.dateEditDateProd.setObjectName("dateEditDateProd")
        self.labelDateProd = QtWidgets.QLabel(self.tab_12)
        self.labelDateProd.setGeometry(QtCore.QRect(450, 420, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDateProd.setFont(font)
        self.labelDateProd.setObjectName("labelDateProd")
        self.labelPacker = QtWidgets.QLabel(self.tab_12)
        self.labelPacker.setGeometry(QtCore.QRect(70, 420, 86, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPacker.setFont(font)
        self.labelPacker.setObjectName("labelPacker")
        self.comboBoxPacker = QtWidgets.QComboBox(self.tab_12)
        self.comboBoxPacker.setGeometry(QtCore.QRect(160, 420, 206, 22))
        self.comboBoxPacker.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxPacker.setObjectName("comboBoxPacker")
        self.lineEditQuantity = QtWidgets.QLineEdit(self.tab_12)
        self.lineEditQuantity.setGeometry(QtCore.QRect(160, 470, 113, 20))
        self.lineEditQuantity.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditQuantity.setObjectName("lineEditQuantity")
        self.labelQuantity = QtWidgets.QLabel(self.tab_12)
        self.labelQuantity.setGeometry(QtCore.QRect(70, 470, 86, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelQuantity.setFont(font)
        self.labelQuantity.setObjectName("labelQuantity")
        self.tabWidgetLabels.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.tabWidgetLabels.addTab(self.tab_13, "")
        self.tabWidgetMain.addTab(self.tab_5, "")
        self.BtnBack = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBack.setGeometry(QtCore.QRect(10, 640, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnBack.setFont(font)
        self.BtnBack.setText("Назад")
        self.BtnBack.setObjectName("BtnBack")
        self.BtnStatusInfo = QtWidgets.QPushButton(self.centralwidget)
        self.BtnStatusInfo.setGeometry(QtCore.QRect(10, 600, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnStatusInfo.setFont(font)
        self.BtnStatusInfo.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.BtnStatusInfo.setText("")
        self.BtnStatusInfo.setObjectName("BtnStatusInfo")
        self.BtnExcelReportOpen = QtWidgets.QPushButton(self.centralwidget)
        self.BtnExcelReportOpen.setGeometry(QtCore.QRect(140, 600, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnExcelReportOpen.setFont(font)
        self.BtnExcelReportOpen.setText("Excel-отчёт")
        self.BtnExcelReportOpen.setObjectName("BtnExcelReportOpen")
        self.framePrintArea = QtWidgets.QFrame(self.centralwidget)
        self.framePrintArea.setGeometry(QtCore.QRect(270, 590, 511, 81))
        self.framePrintArea.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.framePrintArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.framePrintArea.setObjectName("framePrintArea")
        self.BtnPrint = QtWidgets.QPushButton(self.framePrintArea)
        self.BtnPrint.setGeometry(QtCore.QRect(390, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnPrint.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../utils/icons/printer.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnPrint.setIcon(icon)
        self.BtnPrint.setIconSize(QtCore.QSize(27, 27))
        self.BtnPrint.setObjectName("BtnPrint")
        self.comboBoxPrinterSelect = QtWidgets.QComboBox(self.framePrintArea)
        self.comboBoxPrinterSelect.setGeometry(QtCore.QRect(0, 20, 241, 31))
        self.comboBoxPrinterSelect.setObjectName("comboBoxPrinterSelect")
        self.labelPrinterSelect = QtWidgets.QLabel(self.framePrintArea)
        self.labelPrinterSelect.setGeometry(QtCore.QRect(20, 0, 51, 16))
        self.labelPrinterSelect.setObjectName("labelPrinterSelect")
        self.checkBoxPrintAll = QtWidgets.QCheckBox(self.framePrintArea)
        self.checkBoxPrintAll.setGeometry(QtCore.QRect(280, 0, 211, 20))
        self.checkBoxPrintAll.setObjectName("checkBoxPrintAll")
        self.spinBoxNumbersOfCopy = QtWidgets.QSpinBox(self.framePrintArea)
        self.spinBoxNumbersOfCopy.setGeometry(QtCore.QRect(310, 57, 61, 22))
        self.spinBoxNumbersOfCopy.setMinimum(1)
        self.spinBoxNumbersOfCopy.setObjectName("spinBoxNumbersOfCopy")
        self.labelNumbersOfCopy = QtWidgets.QLabel(self.framePrintArea)
        self.labelNumbersOfCopy.setGeometry(QtCore.QRect(270, 60, 41, 16))
        self.labelNumbersOfCopy.setObjectName("labelNumbersOfCopy")
        self.checkBoxPrintCurrentPage = QtWidgets.QCheckBox(self.framePrintArea)
        self.checkBoxPrintCurrentPage.setGeometry(QtCore.QRect(280, 20, 221, 20))
        self.checkBoxPrintCurrentPage.setObjectName("checkBoxPrintCurrentPage")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(250, 600, 20, 71))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidgetMain.setCurrentIndex(0)
        self.tabWidgetDetail.setCurrentIndex(0)
        self.tabWidgetTechnologicPassport.setCurrentIndex(0)
        self.tabWidgetNorms.setCurrentIndex(0)
        self.tabWidgetDrawings.setCurrentIndex(0)
        self.tabWidgetLabels.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Заказ № 34-230"))
        self.LbDate.setText(_translate("MainWindow", "26.07.2024"))
        self.labelFrom.setText(_translate("MainWindow", "от "))
        self.LbOrderNumber.setText(_translate("MainWindow", "Заказ на изготовление № 34-230"))
        self.LbCustomer_2.setText(_translate("MainWindow", "ООО \"Белагро Бел\""))
        self.labelCustomer.setText(_translate("MainWindow", "Заказчик"))
        self.LbProductName_2.setText(_translate("MainWindow", "Нож КСША 40.00.004"))
        self.labelToProdQuantity.setText(_translate("MainWindow", "В запуск"))
        self.labelQuantity_2.setText(_translate("MainWindow", "Количество"))
        self.labelThings.setText(_translate("MainWindow", "шт"))
        self.LbMaterialGOST_3.setText(_translate("MainWindow", "Сталь 45 ГОСТ 1050-2013"))
        self.LbToProdQuantity.setText(_translate("MainWindow", "176"))
        self.labelMaterial_2.setText(_translate("MainWindow", "Материал"))
        self.labelByOrderQuantity.setText(_translate("MainWindow", "По заказу"))
        self.LbByOrderQuantity.setText(_translate("MainWindow", "150"))
        self.labelProductName.setText(_translate("MainWindow", "Наименование"))
        self.labelThings_2.setText(_translate("MainWindow", "шт"))
        self.LbFormDimensionGOST_2.setText(_translate("MainWindow", "8,0 ГОСТ 19903-2015"))
        self.LbMaterialGOST_2.setText(_translate("MainWindow", "45 ГОСТ 1050-2013"))
        self.LbForm_2.setText(_translate("MainWindow", "Лист"))
        self.LbDimensionsOfMaterial_2.setText(_translate("MainWindow", "1500х3000 - 1 шт"))
        self.labelIssueMaterial.setText(_translate("MainWindow", "Выдать материал"))
        self.tabWidgetDetail.setTabText(self.tabWidgetDetail.indexOf(self.tab_10), _translate("MainWindow", "1"))
        self.tabWidgetDetail.setTabText(self.tabWidgetDetail.indexOf(self.tab_11), _translate("MainWindow", "2"))
        self.LbTerm.setText(_translate("MainWindow", "Срок 10 рабочих дней"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab), _translate("MainWindow", "Заказ"))
        self.LbNumber.setText(_translate("MainWindow", "1"))
        self.LbOperation.setText(_translate("MainWindow", "Отрубная"))
        self.LbWorks.setText(_translate("MainWindow", "Из листа Ст.45 s8 рубить полосы в размер 268х1500х8 (16 заготовок из полосы) в кол-ве 11 шт. Итого: 176 шт."))
        self.labelOperation.setText(_translate("MainWindow", "Операция"))
        self.labelWorks.setText(_translate("MainWindow", "Работы"))
        self.labelNumber.setText(_translate("MainWindow", "№"))
        self.tabWidgetTechnologicPassport.setTabText(self.tabWidgetTechnologicPassport.indexOf(self.tab_8), _translate("MainWindow", "Деталь 1"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_2), _translate("MainWindow", "Технологический паспорт"))
        self.groupBoxNorms.setTitle(_translate("MainWindow", "Норма расхода материала"))
        self.labelNormUnitProd.setText(_translate("MainWindow", "Норма расхода на единицу продукции"))
        self.LbOneUnitNormMass.setText(_translate("MainWindow", "1,57"))
        self.LbOneUnitNormVolume.setText(_translate("MainWindow", "0,025"))
        self.LbOneUnitNormLength.setText(_translate("MainWindow", "-"))
        self.labelOneUnitNormMassKg.setText(_translate("MainWindow", "кг"))
        self.labelOneUnitNormVolume.setText(_translate("MainWindow", "м²"))
        self.labelOneUnitNormLength.setText(_translate("MainWindow", "м"))
        self.labelMaterial.setText(_translate("MainWindow", "Материал"))
        self.LbDimensionsOfMaterial.setText(_translate("MainWindow", "1500х3000 - 1 шт"))
        self.labelAllNormLength.setText(_translate("MainWindow", "м"))
        self.labelNormAllProd.setText(_translate("MainWindow", "Норма расхода на всю продукцию"))
        self.labelAllNormVolume.setText(_translate("MainWindow", "м²"))
        self.LbAllNormLength.setText(_translate("MainWindow", "-"))
        self.LbAllNormVolume.setText(_translate("MainWindow", "4,4"))
        self.labelAllNormMassKg.setText(_translate("MainWindow", "кг"))
        self.LbAllNormMass.setText(_translate("MainWindow", "276,32"))
        self.labelOneDetailMass.setText(_translate("MainWindow", "Масса одной детали"))
        self.labelOneDetailMassKg.setText(_translate("MainWindow", "кг"))
        self.LbOneDetailMass.setText(_translate("MainWindow", "1,24"))
        self.LbForm.setText(_translate("MainWindow", "Лист"))
        self.LbFormDimensionGOST.setText(_translate("MainWindow", "8,0 ГОСТ 19903-2015"))
        self.LbMaterialGOST.setText(_translate("MainWindow", "45 ГОСТ 1050-2013"))
        self.tabWidgetNorms.setTabText(self.tabWidgetNorms.indexOf(self.tab_9), _translate("MainWindow", "Деталь 1"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_3), _translate("MainWindow", "Отчёт"))
        self.tabWidgetDrawings.setTabText(self.tabWidgetDrawings.indexOf(self.tab_6), _translate("MainWindow", "Лист 1"))
        self.tabWidgetDrawings.setTabText(self.tabWidgetDrawings.indexOf(self.tab_7), _translate("MainWindow", "Лист 2"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_4), _translate("MainWindow", "Чертёж"))
        self.LbProductName.setText(_translate("MainWindow", "Нож КСША 40.00.004                                              "))
        self.labelOurSite.setText(_translate("MainWindow", "Наш сайт"))
        self.labelMassNetto.setText(_translate("MainWindow", "МАССА НЕТТО:"))
        self.LbCustomer.setText(_translate("MainWindow", "ООО \"Белагро Бел\""))
        self.LbMassNetto.setText(_translate("MainWindow", "40 КГ"))
        self.labelGrifAgro.setText(_translate("MainWindow", "ООО ПКФ \"ГРИФ-АГРО\""))
        self.labelAddres.setText(_translate("MainWindow", "г. Витебск, ул. Лазо 105, оф. 14"))
        self.LbQuantity.setText(_translate("MainWindow", "Количество:         шт."))
        self.LbTotalBatchQuantity.setText(_translate("MainWindow", "Вся партия:         шт."))
        self.LbPacker.setText(_translate("MainWindow", "Упаковщик:"))
        self.labelManufactureDate.setText(_translate("MainWindow", "Дата изготовления:"))
        self.LbManufactureDate.setText(_translate("MainWindow", "НОЯБРЬ 2024 г."))
        self.LbOrderNumberAndDate.setText(_translate("MainWindow", "Заказ №230 от 26.07.2024"))
        self.dateEditDateProd.setDisplayFormat(_translate("MainWindow", "MM.yyyy"))
        self.labelDateProd.setText(_translate("MainWindow", "Дата изготовления:"))
        self.labelPacker.setText(_translate("MainWindow", "Упаковщик:"))
        self.labelQuantity.setText(_translate("MainWindow", "Количество:"))
        self.tabWidgetLabels.setTabText(self.tabWidgetLabels.indexOf(self.tab_12), _translate("MainWindow", "Деталь_1"))
        self.tabWidgetLabels.setTabText(self.tabWidgetLabels.indexOf(self.tab_13), _translate("MainWindow", "Деталь_2"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_5), _translate("MainWindow", "Этикетка"))
        self.BtnPrint.setText(_translate("MainWindow", "Печать"))
        self.labelPrinterSelect.setText(_translate("MainWindow", "Принтер"))
        self.checkBoxPrintAll.setText(_translate("MainWindow", "Напечатать документ целиком"))
        self.labelNumbersOfCopy.setText(_translate("MainWindow", "Копии:"))
        self.checkBoxPrintCurrentPage.setText(_translate("MainWindow", "Напечатать всё на текущей странице"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
