from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowEngineer(object):
    def setupUi(self, MainWindowEngineer):
        MainWindowEngineer.setObjectName("MainWindowEngineer")
        MainWindowEngineer.resize(365, 208)
        self.centralwidget = QtWidgets.QWidget(MainWindowEngineer)
        self.centralwidget.setObjectName("centralwidget")
        self.BtnOrderBase = QtWidgets.QPushButton(self.centralwidget)
        self.BtnOrderBase.setGeometry(QtCore.QRect(20, 100, 131, 31))
        self.BtnOrderBase.setObjectName("BtnOrderBase")
        self.BtnDrowingArchive = QtWidgets.QPushButton(self.centralwidget)
        self.BtnDrowingArchive.setGeometry(QtCore.QRect(20, 140, 131, 31))
        self.BtnDrowingArchive.setObjectName("BtnDrowingArchive")
        self.BtnRoleSelection = QtWidgets.QPushButton(self.centralwidget)
        self.BtnRoleSelection.setGeometry(QtCore.QRect(240, 140, 101, 31))
        self.BtnRoleSelection.setObjectName("BtnRoleSelection")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 27, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(310, 27, 31, 21))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.LbNewTasks = QtWidgets.QLabel(self.frame)
        self.LbNewTasks.setGeometry(QtCore.QRect(6, 2, 20, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LbNewTasks.setFont(font)
        self.LbNewTasks.setAlignment(QtCore.Qt.AlignCenter)
        self.LbNewTasks.setObjectName("LbNewTasks")
        self.BtnNewTasks = QtWidgets.QPushButton(self.centralwidget)
        self.BtnNewTasks.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.BtnNewTasks.setObjectName("BtnNewTasks")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(310, 70, 31, 21))
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setMidLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.LbForRework = QtWidgets.QLabel(self.frame_2)
        self.LbForRework.setGeometry(QtCore.QRect(6, 2, 20, 15))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LbForRework.setFont(font)
        self.LbForRework.setAlignment(QtCore.Qt.AlignCenter)
        self.LbForRework.setObjectName("LbForRework")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(190, 70, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.BtnReworkOrders = QtWidgets.QPushButton(self.centralwidget)
        self.BtnReworkOrders.setGeometry(QtCore.QRect(20, 60, 131, 31))
        self.BtnReworkOrders.setObjectName("BtnReworkOrders")
        MainWindowEngineer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowEngineer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 365, 21))
        self.menubar.setObjectName("menubar")
        MainWindowEngineer.setMenuBar(self.menubar)

        self.retranslateUi(MainWindowEngineer)
        QtCore.QMetaObject.connectSlotsByName(MainWindowEngineer)

    def retranslateUi(self, MainWindowEngineer):
        _translate = QtCore.QCoreApplication.translate
        MainWindowEngineer.setWindowTitle(_translate("MainWindowEngineer", "Главное окно инженера"))
        self.BtnOrderBase.setText(_translate("MainWindowEngineer", "База заказов"))
        self.BtnDrowingArchive.setText(_translate("MainWindowEngineer", "Архив КД"))
        self.BtnRoleSelection.setText(_translate("MainWindowEngineer", "К выбору роли"))
        self.label.setText(_translate("MainWindowEngineer", "Новых заданий:"))
        self.LbNewTasks.setText(_translate("MainWindowEngineer", "12"))
        self.BtnNewTasks.setText(_translate("MainWindowEngineer", "Новые задания"))
        self.LbForRework.setText(_translate("MainWindowEngineer", "12"))
        self.label_4.setText(_translate("MainWindowEngineer", "На доработку:"))
        self.BtnReworkOrders.setText(_translate("MainWindowEngineer", "Заказы на доработку"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowEngineer = QtWidgets.QMainWindow()
    ui = Ui_MainWindowEngineer()
    ui.setupUi(MainWindowEngineer)
    MainWindowEngineer.show()
    sys.exit(app.exec_())
