
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_NewTasks(object):
    def setupUi(self, NewTasks):
        NewTasks.setObjectName("NewTasks")
        NewTasks.resize(1102, 441)
        self.centralwidget = QtWidgets.QWidget(NewTasks)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 30, 1081, 341))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1062, 339))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frameLineTask = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameLineTask.setGeometry(QtCore.QRect(10, 10, 1041, 21))
        self.frameLineTask.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLineTask.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLineTask.setObjectName("frameLineTask")
        self.frame = QtWidgets.QFrame(self.frameLineTask)
        self.frame.setGeometry(QtCore.QRect(30, 0, 1015, 20))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(40, 1, 10, 18))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(150, 1, 18, 18))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.LbCheckNumber = QtWidgets.QLabel(self.frame)
        self.LbCheckNumber.setGeometry(QtCore.QRect(10, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LbCheckNumber.setFont(font)
        self.LbCheckNumber.setObjectName("LbCheckNumber")
        self.LbCustomer = QtWidgets.QLabel(self.frame)
        self.LbCustomer.setGeometry(QtCore.QRect(170, 2, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LbCustomer.setFont(font)
        self.LbCustomer.setObjectName("LbCustomer")
        self.LbDate = QtWidgets.QLabel(self.frame)
        self.LbDate.setGeometry(QtCore.QRect(60, 2, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LbDate.setFont(font)
        self.LbDate.setObjectName("LbDate")
        self.LbQuantity = QtWidgets.QLabel(self.frame)
        self.LbQuantity.setGeometry(QtCore.QRect(905, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LbQuantity.setFont(font)
        self.LbQuantity.setObjectName("LbQuantity")
        self.comboBoxProductName = QtWidgets.QComboBox(self.frame)
        self.comboBoxProductName.setGeometry(QtCore.QRect(470, 0, 431, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxProductName.setFont(font)
        self.comboBoxProductName.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.comboBoxProductName.setModelColumn(8)
        self.comboBoxProductName.setObjectName("comboBoxProductName")
        self.BtnStartDeveloping = QtWidgets.QPushButton(self.frameLineTask)
        self.BtnStartDeveloping.setGeometry(QtCore.QRect(990, 0, 51, 20))
        self.BtnStartDeveloping.setIconSize(QtCore.QSize(14, 14))
        self.BtnStartDeveloping.setObjectName("BtnStartDeveloping")
        self.BtnStatusInfo = QtWidgets.QPushButton(self.frameLineTask)
        self.BtnStatusInfo.setGeometry(QtCore.QRect(4, 0, 25, 20))
        self.BtnStatusInfo.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.BtnStatusInfo.setText("")
        self.BtnStatusInfo.setObjectName("BtnStatusInfo")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BtnBack = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBack.setGeometry(QtCore.QRect(10, 380, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnBack.setFont(font)
        self.BtnBack.setObjectName("BtnBack")
        self.labelQuantity = QtWidgets.QLabel(self.centralwidget)
        self.labelQuantity.setGeometry(QtCore.QRect(940, 10, 61, 16))
        self.labelQuantity.setObjectName("labelQuantity")
        self.labelBoxProductName = QtWidgets.QLabel(self.centralwidget)
        self.labelBoxProductName.setGeometry(QtCore.QRect(680, 10, 121, 16))
        self.labelBoxProductName.setObjectName("labelBoxProductName")
        self.labelCustomer = QtWidgets.QLabel(self.centralwidget)
        self.labelCustomer.setGeometry(QtCore.QRect(270, 10, 171, 16))
        self.labelCustomer.setObjectName("labelCustomer")
        self.labelDate = QtWidgets.QLabel(self.centralwidget)
        self.labelDate.setGeometry(QtCore.QRect(130, 10, 31, 16))
        self.labelDate.setObjectName("labelDate")
        self.labelCheckNumber = QtWidgets.QLabel(self.centralwidget)
        self.labelCheckNumber.setGeometry(QtCore.QRect(60, 10, 31, 16))
        self.labelCheckNumber.setObjectName("labelCheckNumber")
        NewTasks.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(NewTasks)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 21))
        self.menubar.setObjectName("menubar")
        NewTasks.setMenuBar(self.menubar)

        self.retranslateUi(NewTasks)
        QtCore.QMetaObject.connectSlotsByName(NewTasks)

    def retranslateUi(self, NewTasks):
        _translate = QtCore.QCoreApplication.translate
        NewTasks.setWindowTitle(_translate("NewTasks", "Новые задания"))
        self.LbCheckNumber.setText(_translate("NewTasks", "142"))
        self.LbCustomer.setText(_translate("NewTasks", "ООО \"Белагро Бел\""))
        self.LbDate.setText(_translate("NewTasks", "26.07.2024"))
        self.LbQuantity.setText(_translate("NewTasks", "1000"))
        self.BtnStartDeveloping.setText(_translate("NewTasks", "Начать"))
        self.BtnBack.setText(_translate("NewTasks", "Назад"))
        self.labelQuantity.setText(_translate("NewTasks", "Количество"))
        self.labelBoxProductName.setText(_translate("NewTasks", "Наименование изделия"))
        self.labelCustomer.setText(_translate("NewTasks", "Название организации заказчика"))
        self.labelDate.setText(_translate("NewTasks", "Дата"))
        self.labelCheckNumber.setText(_translate("NewTasks", "№ сч"))

class NewTasks(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_NewTasks()
        self.ui.setupUi(self)

        self.ui.BtnBack.clicked.connect(self.back_main_engineer_window)
        self.ui.BtnStatusInfo.clicked.connect(self.status_info_window)

    def status_info_window(self):
        try:
            from windows.statuses import StatusInfoWindow
            self.status_info = StatusInfoWindow()
            self.status_info.show()
        except Exception as e:
            QMessageBox.critical(self, "Ошибка", f"Не удалось открыть информацию о статусах: {e}")

    def back_main_engineer_window(self):
        try:
            from windows.main_engineer_window import MainWindowEngineer
            self.main_engineer_window = MainWindowEngineer()
            self.main_engineer_window.show()
            self.close()
        except Exception as e:
            QMessageBox.critical(self, "Ошибка", f"Не удалось открыть главное окно инженера: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NewTasks = QtWidgets.QMainWindow()
    ui = Ui_NewTasks()
    ui.setupUi(NewTasks)
    NewTasks.show()
    sys.exit(app.exec_())
