
from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc


class Ui_Statuses(object):
    def setupUi(self, Statuses):
        Statuses.setObjectName("Statuses")
        Statuses.resize(647, 437)
        self.centralwidget = QtWidgets.QWidget(Statuses)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelCheck1 = QtWidgets.QLabel(self.widget)
        self.labelCheck1.setMinimumSize(QtCore.QSize(30, 30))
        self.labelCheck1.setMaximumSize(QtCore.QSize(30, 30))
        self.labelCheck1.setText("")
        self.labelCheck1.setPixmap(QtGui.QPixmap("../utils/icons/check.svg"))
        self.labelCheck1.setScaledContents(False)
        self.labelCheck1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCheck1.setIndent(0)
        self.labelCheck1.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.labelCheck1)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(50, 0))
        self.frame.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout.addWidget(self.frame)
        self.labelStatus1 = QtWidgets.QLabel(self.widget)
        self.labelStatus1.setObjectName("label")
        self.horizontalLayout.addWidget(self.labelStatus1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelCheck2 = QtWidgets.QLabel(self.widget_2)
        self.labelCheck2.setMinimumSize(QtCore.QSize(30, 30))
        self.labelCheck2.setMaximumSize(QtCore.QSize(30, 30))
        self.labelCheck2.setText("")
        self.labelCheck2.setPixmap(QtGui.QPixmap("../utils/icons/check.svg"))
        self.labelCheck2.setScaledContents(False)
        self.labelCheck2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCheck2.setIndent(0)
        self.labelCheck2.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.labelCheck2)
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.labelStatus2 = QtWidgets.QLabel(self.widget_2)
        self.labelStatus2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.labelStatus2)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelCheck3 = QtWidgets.QLabel(self.widget_3)
        self.labelCheck3.setMinimumSize(QtCore.QSize(30, 30))
        self.labelCheck3.setMaximumSize(QtCore.QSize(30, 30))
        self.labelCheck3.setText("")
        self.labelCheck3.setPixmap(QtGui.QPixmap("../utils/icons/check.svg"))
        self.labelCheck3.setScaledContents(False)
        self.labelCheck3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCheck3.setIndent(0)
        self.labelCheck3.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.labelCheck3)
        self.frame_6 = QtWidgets.QFrame(self.widget_3)
        self.frame_6.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_6.setAutoFillBackground(False)
        self.frame_6.setStyleSheet("background-color: rgb(191, 74, 195);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.labelStatus3 = QtWidgets.QLabel(self.widget_3)
        self.labelStatus3.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.labelStatus3)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelCheck4 = QtWidgets.QLabel(self.widget_4)
        self.labelCheck4.setMinimumSize(QtCore.QSize(30, 30))
        self.labelCheck4.setMaximumSize(QtCore.QSize(30, 30))
        self.labelCheck4.setText("")
        self.labelCheck4.setPixmap(QtGui.QPixmap("../utils/icons/check.svg"))
        self.labelCheck4.setScaledContents(False)
        self.labelCheck4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCheck4.setIndent(0)
        self.labelCheck4.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.labelCheck4)
        self.frame_4 = QtWidgets.QFrame(self.widget_4)
        self.frame_4.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_4.setAutoFillBackground(False)
        self.frame_4.setStyleSheet("background-color: rgb(0, 132, 0);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.labelStatus4 = QtWidgets.QLabel(self.widget_4)
        self.labelStatus4.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.labelStatus4)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelCheck5 = QtWidgets.QLabel(self.widget_5)
        self.labelCheck5.setMinimumSize(QtCore.QSize(30, 30))
        self.labelCheck5.setMaximumSize(QtCore.QSize(30, 30))
        self.labelCheck5.setText("")
        self.labelCheck5.setPixmap(QtGui.QPixmap("../utils/icons/check.svg"))
        self.labelCheck5.setScaledContents(False)
        self.labelCheck5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCheck5.setIndent(0)
        self.labelCheck5.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.labelCheck5)
        self.frame_3 = QtWidgets.QFrame(self.widget_5)
        self.frame_3.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setStyleSheet("background-color: rgb(0, 0, 255);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.labelStatus5 = QtWidgets.QLabel(self.widget_5)
        self.labelStatus5.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.labelStatus5)
        self.verticalLayout.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.centralwidget)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelCheck6 = QtWidgets.QLabel(self.widget_6)
        self.labelCheck6.setMinimumSize(QtCore.QSize(30, 30))
        self.labelCheck6.setMaximumSize(QtCore.QSize(30, 30))
        self.labelCheck6.setText("")
        self.labelCheck6.setPixmap(QtGui.QPixmap("../utils/icons/check.svg"))
        self.labelCheck6.setScaledContents(False)
        self.labelCheck6.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCheck6.setIndent(0)
        self.labelCheck6.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.labelCheck6)
        self.frame_5 = QtWidgets.QFrame(self.widget_6)
        self.frame_5.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_5.setAutoFillBackground(False)
        self.frame_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_6.addWidget(self.frame_5)
        self.labelStatus6 = QtWidgets.QLabel(self.widget_6)
        self.labelStatus6.setObjectName("label_5")
        self.horizontalLayout_6.addWidget(self.labelStatus6)
        self.verticalLayout.addWidget(self.widget_6)
        Statuses.setCentralWidget(self.centralwidget)

        self.retranslateUi(Statuses)
        QtCore.QMetaObject.connectSlotsByName(Statuses)

    def retranslateUi(self, Statuses):
        _translate = QtCore.QCoreApplication.translate
        Statuses.setWindowTitle(_translate("Statuses", "Статусы"))
        self.labelStatus1.setText(_translate("Statuses", "1. Задание сформировано, разработка заказа не начата."))
        self.labelStatus2.setText(_translate("Statuses", "2. Заказ находится в разработке (на исправлении)."))
        self.labelStatus3.setText(_translate("Statuses", "3. Заказ отправлен на проверку и утверждение."))
        self.labelStatus4.setText(_translate("Statuses", "4. Заказ проверен и утверждён."))
        self.labelStatus5.setText(_translate("Statuses", "5. Заказ принят на производво."))
        self.labelStatus6.setText(_translate("Statuses", "6. Заказ отменён."))

class Statuses(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_Statuses()
        self.ui.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = Statuses()  # Создаём экземпляр вашего класса Materials
    window.show()         # Показываем окно
    sys.exit(app.exec_())
