
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_TasksList(object):
    def setupUi(self, TasksList):
        TasksList.setObjectName("TasksList")
        TasksList.resize(1132, 798)
        self.centralwidget = QtWidgets.QWidget(TasksList)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 65, 1111, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.labelProductName = QtWidgets.QLabel(self.frame_3)
        self.labelProductName.setGeometry(QtCore.QRect(660, 15, 121, 16))
        self.labelProductName.setObjectName("labelProductName")
        self.labelCheckNumber = QtWidgets.QLabel(self.frame_3)
        self.labelCheckNumber.setGeometry(QtCore.QRect(10, 0, 51, 16))
        self.labelCheckNumber.setObjectName("labelCheckNumber")
        self.labelDate = QtWidgets.QLabel(self.frame_3)
        self.labelDate.setGeometry(QtCore.QRect(95, 0, 31, 16))
        self.labelDate.setObjectName("labelDate")
        self.labelQuantity = QtWidgets.QLabel(self.frame_3)
        self.labelQuantity.setGeometry(QtCore.QRect(960, 15, 61, 16))
        self.labelQuantity.setObjectName("labelQuantity")
        self.labelCustomer = QtWidgets.QLabel(self.frame_3)
        self.labelCustomer.setGeometry(QtCore.QRect(240, 15, 171, 16))
        self.labelCustomer.setObjectName("labelCustomer")
        self.BtnSortNumericUp = QtWidgets.QPushButton(self.frame_3)
        self.BtnSortNumericUp.setGeometry(QtCore.QRect(35, 20, 21, 20))
        self.BtnSortNumericUp.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../utils/icons/sort-numeric-down-alt.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSortNumericUp.setIcon(icon)
        self.BtnSortNumericUp.setObjectName("BtnSortNumericUp")
        self.BtnSortNumericDown = QtWidgets.QPushButton(self.frame_3)
        self.BtnSortNumericDown.setGeometry(QtCore.QRect(10, 20, 21, 20))
        self.BtnSortNumericDown.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../utils/icons/sort-numeric-down.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSortNumericDown.setIcon(icon1)
        self.BtnSortNumericDown.setObjectName("BtnSortNumericDown")
        self.BtnSortDown = QtWidgets.QPushButton(self.frame_3)
        self.BtnSortDown.setGeometry(QtCore.QRect(85, 20, 21, 20))
        self.BtnSortDown.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../utils/icons/sort-down.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSortDown.setIcon(icon2)
        self.BtnSortDown.setObjectName("BtnSortDown")
        self.BtnSortUp = QtWidgets.QPushButton(self.frame_3)
        self.BtnSortUp.setGeometry(QtCore.QRect(110, 20, 21, 20))
        self.BtnSortUp.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../utils/icons/sort-down-alt.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSortUp.setIcon(icon3)
        self.BtnSortUp.setObjectName("BtnSortUp")
        self.line_5 = QtWidgets.QFrame(self.frame_3)
        self.line_5.setGeometry(QtCore.QRect(50, 8, 20, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.frame_3)
        self.line_6.setGeometry(QtCore.QRect(160, 10, 20, 31))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.frame_3)
        self.line_7.setGeometry(QtCore.QRect(480, 10, 20, 31))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_9 = QtWidgets.QFrame(self.frame_3)
        self.line_9.setGeometry(QtCore.QRect(940, 10, 20, 31))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.frame_3)
        self.line_10.setGeometry(QtCore.QRect(1025, 10, 20, 31))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 110, 1111, 601))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1092, 599))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 1071, 51))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frameLineTask = QtWidgets.QFrame(self.frame_4)
        self.frameLineTask.setGeometry(QtCore.QRect(0, 0, 1071, 41))
        self.frameLineTask.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frameLineTask.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLineTask.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameLineTask.setLineWidth(2)
        self.frameLineTask.setMidLineWidth(1)
        self.frameLineTask.setObjectName("frameLineTask")
        self.line = QtWidgets.QFrame(self.frameLineTask)
        self.line.setGeometry(QtCore.QRect(40, 1, 18, 39))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frameLineTask)
        self.line_2.setGeometry(QtCore.QRect(150, 1, 18, 39))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.LbCheckNumber = QtWidgets.QLabel(self.frameLineTask)
        self.LbCheckNumber.setGeometry(QtCore.QRect(10, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LbCheckNumber.setFont(font)
        self.LbCheckNumber.setObjectName("LbCheckNumber")
        self.LbCustomer = QtWidgets.QLabel(self.frameLineTask)
        self.LbCustomer.setGeometry(QtCore.QRect(170, 10, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LbCustomer.setFont(font)
        self.LbCustomer.setObjectName("LbCustomer")
        self.line_8 = QtWidgets.QFrame(self.frameLineTask)
        self.line_8.setGeometry(QtCore.QRect(1015, 1, 18, 39))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.LbDate = QtWidgets.QLabel(self.frameLineTask)
        self.LbDate.setGeometry(QtCore.QRect(60, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LbDate.setFont(font)
        self.LbDate.setObjectName("LbDate")
        self.LbQuantity = QtWidgets.QLabel(self.frameLineTask)
        self.LbQuantity.setGeometry(QtCore.QRect(950, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LbQuantity.setFont(font)
        self.LbQuantity.setObjectName("LbQuantity")
        self.comboBoxProductName = QtWidgets.QComboBox(self.frameLineTask)
        self.comboBoxProductName.setGeometry(QtCore.QRect(480, 0, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxProductName.setFont(font)
        self.comboBoxProductName.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.comboBoxProductName.setModelColumn(8)
        self.comboBoxProductName.setObjectName("comboBoxProductName")
        self.BtnEditTask = QtWidgets.QPushButton(self.frame_4)
        self.BtnEditTask.setGeometry(QtCore.QRect(1030, 5, 31, 31))
        self.BtnEditTask.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../utils/icons/pencil-square.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnEditTask.setIcon(icon4)
        self.BtnEditTask.setIconSize(QtCore.QSize(23, 23))
        self.BtnEditTask.setObjectName("BtnEditTask")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BtnBack = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBack.setGeometry(QtCore.QRect(10, 720, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnBack.setFont(font)
        self.BtnBack.setObjectName("BtnBack")
        self.BtnSearchCustomer = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSearchCustomer.setGeometry(QtCore.QRect(350, 30, 31, 31))
        self.BtnSearchCustomer.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../utils/icons/search.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSearchCustomer.setIcon(icon5)
        self.BtnSearchCustomer.setObjectName("BtnSearchCustomer")
        self.lineEditSearchCustomer = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSearchCustomer.setGeometry(QtCore.QRect(20, 29, 321, 31))
        self.lineEditSearchCustomer.setObjectName("lineEditSearchCustomer")
        self.dateEditStartPeriod = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditStartPeriod.setGeometry(QtCore.QRect(890, 37, 81, 22))
        self.dateEditStartPeriod.setCalendarPopup(True)
        self.dateEditStartPeriod.setObjectName("dateEditStartPeriod")
        self.dateEditEndPeriod = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditEndPeriod.setGeometry(QtCore.QRect(1000, 37, 81, 22))
        self.dateEditEndPeriod.setCalendarPopup(True)
        self.dateEditEndPeriod.setObjectName("dateEditEndPeriod")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(980, 40, 16, 16))
        self.label_7.setObjectName("label_7")
        self.checkBoxPeriodOn = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBoxPeriodOn.setGeometry(QtCore.QRect(800, 40, 81, 17))
        self.checkBoxPeriodOn.setObjectName("checkBoxPeriodOn")
        self.lineEditSearchProductName = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSearchProductName.setGeometry(QtCore.QRect(410, 30, 321, 31))
        self.lineEditSearchProductName.setObjectName("lineEditSearchProductName")
        self.BtnSearchProductName = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSearchProductName.setGeometry(QtCore.QRect(740, 31, 31, 31))
        self.BtnSearchProductName.setText("")
        self.BtnSearchProductName.setIcon(icon5)
        self.BtnSearchProductName.setObjectName("BtnSearchProductName")
        self.labelSearchCustomer = QtWidgets.QLabel(self.centralwidget)
        self.labelSearchCustomer.setGeometry(QtCore.QRect(70, 5, 221, 20))
        self.labelSearchCustomer.setObjectName("labelSearchCustomer")
        self.labelSearchProductName = QtWidgets.QLabel(self.centralwidget)
        self.labelSearchProductName.setGeometry(QtCore.QRect(480, 5, 171, 20))
        self.labelSearchProductName.setObjectName("labelSearchProductName")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(390, 20, 20, 51))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(780, 20, 20, 51))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        TasksList.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TasksList)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 21))
        self.menubar.setObjectName("menubar")
        TasksList.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TasksList)
        self.statusbar.setObjectName("statusbar")
        TasksList.setStatusBar(self.statusbar)

        self.retranslateUi(TasksList)
        QtCore.QMetaObject.connectSlotsByName(TasksList)

    def retranslateUi(self, TasksList):
        _translate = QtCore.QCoreApplication.translate
        TasksList.setWindowTitle(_translate("TasksList", "Список заданий"))
        self.labelProductName.setText(_translate("TasksList", "Наименование изделия"))
        self.labelCheckNumber.setText(_translate("TasksList", "№ счёта"))
        self.labelDate.setText(_translate("TasksList", "Дата"))
        self.labelQuantity.setText(_translate("TasksList", "Количество"))
        self.labelCustomer.setText(_translate("TasksList", "Название организации заказчика"))
        self.LbCheckNumber.setText(_translate("TasksList", "142"))
        self.LbCustomer.setText(_translate("TasksList", "ООО \"Белагро Бел\""))
        self.LbDate.setText(_translate("TasksList", "26.07.2024"))
        self.LbQuantity.setText(_translate("TasksList", "1000"))
        self.BtnBack.setText(_translate("TasksList", "Назад"))
        self.label_7.setText(_translate("TasksList", "по"))
        self.checkBoxPeriodOn.setText(_translate("TasksList", "В период от"))
        self.labelSearchCustomer.setText(_translate("TasksList", "Поиск по названию организации заказчика"))
        self.labelSearchProductName.setText(_translate("TasksList", "Поиск по наименованию изделия"))

class TasksList(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_TasksList()
        self.ui.setupUi(self)

        self.ui.BtnBack.clicked.connect(self.back_main_manager_window)

    def back_main_manager_window(self):
        try:
            from windows.main_manager_window import MainWindowManager
            self.main_manager_window = MainWindowManager()  # Создаем экземпляр главного окна менеджера
            self.main_manager_window.show()  # Показываем окно
            self.close()  # Закрываем текущее окно
        except Exception as e:
            QMessageBox.critical(self, "Ошибка", f"Не удалось открыть главное окно менеджера: {e}")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TasksList = QtWidgets.QMainWindow()
    ui = Ui_TasksList()
    ui.setupUi(TasksList)
    TasksList.show()
    sys.exit(app.exec_())
