
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TaskList(object):
    def setupUi(self, TaskList):
        TaskList.setObjectName("TaskList")
        TaskList.resize(1132, 798)
        self.centralwidget = QtWidgets.QWidget(TaskList)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 65, 1111, 41))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(660, 15, 121, 16))
        self.label_11.setObjectName("label_11")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(10, 0, 51, 16))
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(95, 0, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(960, 15, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(240, 15, 171, 16))
        self.label_10.setObjectName("label_10")
        self.BtnSortNumericUp = QtWidgets.QPushButton(self.frame_3)
        self.BtnSortNumericUp.setGeometry(QtCore.QRect(35, 20, 21, 20))
        self.BtnSortNumericUp.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../utils/icons/sort-numeric-down-alt.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSortNumericUp.setIcon(icon)
        self.BtnSortNumericUp.setObjectName("BtnSortNumericUp")
        self.BtnSortNumericDown = QtWidgets.QPushButton(self.frame_3)
        self.BtnSortNumericDown.setGeometry(QtCore.QRect(10, 20, 21, 20))
        self.BtnSortNumericDown.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../utils/icons/sort-numeric-down.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSortNumericDown.setIcon(icon1)
        self.BtnSortNumericDown.setObjectName("BtnSortNumericDown")
        self.BtnSortDown = QtWidgets.QPushButton(self.frame_3)
        self.BtnSortDown.setGeometry(QtCore.QRect(85, 20, 21, 20))
        self.BtnSortDown.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../utils/icons/sort-down.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSortDown.setIcon(icon2)
        self.BtnSortDown.setObjectName("BtnSortDown")
        self.BtnSortUp = QtWidgets.QPushButton(self.frame_3)
        self.BtnSortUp.setGeometry(QtCore.QRect(110, 20, 21, 20))
        self.BtnSortUp.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../utils/icons/sort-down-alt.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSortUp.setIcon(icon3)
        self.BtnSortUp.setObjectName("BtnSortUp")
        self.line_5 = QtWidgets.QFrame(self.frame_3)
        self.line_5.setGeometry(QtCore.QRect(50, 8, 20, 31))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.frame_3)
        self.line_6.setGeometry(QtCore.QRect(160, 10, 20, 31))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.frame_3)
        self.line_7.setGeometry(QtCore.QRect(480, 10, 20, 31))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_9 = QtWidgets.QFrame(self.frame_3)
        self.line_9.setGeometry(QtCore.QRect(940, 10, 20, 31))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.frame_3)
        self.line_10.setGeometry(QtCore.QRect(1025, 10, 20, 31))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 110, 1111, 601))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1092, 599))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setGeometry(QtCore.QRect(10, 10, 1071, 51))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame = QtWidgets.QFrame(self.frame_4)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1071, 41))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(40, 1, 18, 39))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(150, 1, 18, 39))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.LbCheckNumber = QtWidgets.QLabel(self.frame)
        self.LbCheckNumber.setGeometry(QtCore.QRect(10, 10, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.LbCheckNumber.setFont(font)
        self.LbCheckNumber.setObjectName("LbCheckNumber")
        self.Lbcustomer = QtWidgets.QLabel(self.frame)
        self.Lbcustomer.setGeometry(QtCore.QRect(170, 10, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Lbcustomer.setFont(font)
        self.Lbcustomer.setObjectName("Lbcustomer")
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setGeometry(QtCore.QRect(1015, 1, 18, 39))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.LbDate = QtWidgets.QLabel(self.frame)
        self.LbDate.setGeometry(QtCore.QRect(60, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LbDate.setFont(font)
        self.LbDate.setObjectName("LbDate")
        self.LbQuantity = QtWidgets.QLabel(self.frame)
        self.LbQuantity.setGeometry(QtCore.QRect(950, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LbQuantity.setFont(font)
        self.LbQuantity.setObjectName("LbQuantity")
        self.comboBoxProductName = QtWidgets.QComboBox(self.frame)
        self.comboBoxProductName.setGeometry(QtCore.QRect(480, 0, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBoxProductName.setFont(font)
        self.comboBoxProductName.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.comboBoxProductName.setModelColumn(8)
        self.comboBoxProductName.setObjectName("comboBoxProductName")
        self.BtnEdit = QtWidgets.QPushButton(self.frame_4)
        self.BtnEdit.setGeometry(QtCore.QRect(1030, 5, 31, 31))
        self.BtnEdit.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../utils/icons/pencil-square.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnEdit.setIcon(icon4)
        self.BtnEdit.setIconSize(QtCore.QSize(23, 23))
        self.BtnEdit.setObjectName("BtnEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BtnBack = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBack.setGeometry(QtCore.QRect(10, 720, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnBack.setFont(font)
        self.BtnBack.setObjectName("BtnBack")
        self.BtnSearch_1 = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSearch_1.setGeometry(QtCore.QRect(350, 30, 31, 31))
        self.BtnSearch_1.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../utils/icons/search.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnSearch_1.setIcon(icon5)
        self.BtnSearch_1.setObjectName("BtnSearch_1")
        self.lineEditSearch_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSearch_1.setGeometry(QtCore.QRect(20, 29, 321, 31))
        self.lineEditSearch_1.setObjectName("lineEditSearch_1")
        self.dateEditFrom = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditFrom.setGeometry(QtCore.QRect(890, 37, 81, 22))
        self.dateEditFrom.setCalendarPopup(True)
        self.dateEditFrom.setObjectName("dateEditFrom")
        self.dateEditBy = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEditBy.setGeometry(QtCore.QRect(1000, 37, 81, 22))
        self.dateEditBy.setCalendarPopup(True)
        self.dateEditBy.setObjectName("dateEditBy")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(980, 40, 16, 16))
        self.label_7.setObjectName("label_7")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(800, 40, 81, 17))
        self.checkBox.setObjectName("checkBox")
        self.lineEditSearch_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSearch_2.setGeometry(QtCore.QRect(410, 30, 321, 31))
        self.lineEditSearch_2.setObjectName("lineEditSearch_2")
        self.BtnSearch_2 = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSearch_2.setGeometry(QtCore.QRect(740, 31, 31, 31))
        self.BtnSearch_2.setText("")
        self.BtnSearch_2.setIcon(icon5)
        self.BtnSearch_2.setObjectName("BtnSearch_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(70, 5, 221, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(480, 5, 171, 20))
        self.label_13.setObjectName("label_13")
        self.line_11 = QtWidgets.QFrame(self.centralwidget)
        self.line_11.setGeometry(QtCore.QRect(390, 20, 20, 51))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.centralwidget)
        self.line_12.setGeometry(QtCore.QRect(780, 20, 20, 51))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        TaskList.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TaskList)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 21))
        self.menubar.setObjectName("menubar")
        TaskList.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TaskList)
        self.statusbar.setObjectName("statusbar")
        TaskList.setStatusBar(self.statusbar)

        self.retranslateUi(TaskList)
        QtCore.QMetaObject.connectSlotsByName(TaskList)

    def retranslateUi(self, TaskList):
        _translate = QtCore.QCoreApplication.translate
        TaskList.setWindowTitle(_translate("TaskList", "Список заданий"))
        self.label_11.setText(_translate("TaskList", "Наименование изделия"))
        self.label_3.setText(_translate("TaskList", "№ счёта"))
        self.label_6.setText(_translate("TaskList", "Дата"))
        self.label_9.setText(_translate("TaskList", "Количество"))
        self.label_10.setText(_translate("TaskList", "Название организации заказчика"))
        self.LbCheckNumber.setText(_translate("TaskList", "142"))
        self.Lbcustomer.setText(_translate("TaskList", "ООО \"Белагро Бел\""))
        self.LbDate.setText(_translate("TaskList", "26.07.2024"))
        self.LbQuantity.setText(_translate("TaskList", "1000"))
        self.BtnBack.setText(_translate("TaskList", "Назад"))
        self.label_7.setText(_translate("TaskList", "по"))
        self.checkBox.setText(_translate("TaskList", "В период от"))
        self.label_12.setText(_translate("TaskList", "Поиск по названию организации заказчика"))
        self.label_13.setText(_translate("TaskList", "Поиск по наименованию изделия"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TaskList = QtWidgets.QMainWindow()
    ui = Ui_TaskList()
    ui.setupUi(TaskList)
    TaskList.show()
    sys.exit(app.exec_())
