
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TechnologicalPassport(object):
    def setupUi(self, TechnologicalPassport):
        TechnologicalPassport.setObjectName("TechnologicalPassport")
        TechnologicalPassport.resize(991, 710)
        self.centralwidget = QtWidgets.QWidget(TechnologicalPassport)
        self.centralwidget.setObjectName("centralwidget")
        self.BtnBack = QtWidgets.QPushButton(self.centralwidget)
        self.BtnBack.setGeometry(QtCore.QRect(20, 650, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnBack.setFont(font)
        self.BtnBack.setObjectName("BtnBack")
        self.BtnNext = QtWidgets.QPushButton(self.centralwidget)
        self.BtnNext.setGeometry(QtCore.QRect(860, 650, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BtnNext.setFont(font)
        self.BtnNext.setObjectName("BtnNext")
        self.BtnAddNewDetail = QtWidgets.QPushButton(self.centralwidget)
        self.BtnAddNewDetail.setGeometry(QtCore.QRect(430, 630, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BtnAddNewDetail.setFont(font)
        self.BtnAddNewDetail.setObjectName("BtnAddNewDetail")
        self.tabWidgetDetail = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetDetail.setGeometry(QtCore.QRect(10, 0, 981, 631))
        self.tabWidgetDetail.setObjectName("tabWidgetDetail")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.labelCheckNumber = QtWidgets.QLabel(self.tab)
        self.labelCheckNumber.setGeometry(QtCore.QRect(10, 0, 51, 16))
        self.labelCheckNumber.setObjectName("labelCheckNumber")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(10, 70, 951, 531))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 932, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.frameOperation = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frameOperation.setGeometry(QtCore.QRect(10, 10, 911, 61))
        self.frameOperation.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.frameOperation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameOperation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameOperation.setObjectName("frameOperation")
        self.comboBoxOperations = QtWidgets.QComboBox(self.frameOperation)
        self.comboBoxOperations.setGeometry(QtCore.QRect(90, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBoxOperations.setFont(font)
        self.comboBoxOperations.setEditable(True)
        self.comboBoxOperations.setCurrentText("")
        self.comboBoxOperations.setMinimumContentsLength(7)
        self.comboBoxOperations.setModelColumn(22)
        self.comboBoxOperations.setObjectName("comboBoxOperations")
        self.LbOperationNumber = QtWidgets.QLabel(self.frameOperation)
        self.LbOperationNumber.setGeometry(QtCore.QRect(50, 15, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.LbOperationNumber.setFont(font)
        self.LbOperationNumber.setAlignment(QtCore.Qt.AlignCenter)
        self.LbOperationNumber.setObjectName("LbOperationNumber")
        self.textEditWorks = QtWidgets.QTextEdit(self.frameOperation)
        self.textEditWorks.setGeometry(QtCore.QRect(290, 10, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEditWorks.setFont(font)
        self.textEditWorks.setObjectName("textEditWorks")
        self.BtnDeleteOperation = QtWidgets.QPushButton(self.frameOperation)
        self.BtnDeleteOperation.setGeometry(QtCore.QRect(870, 15, 31, 31))
        self.BtnDeleteOperation.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../utils/icons/x-square.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("x-square.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnDeleteOperation.setIcon(icon)
        self.BtnDeleteOperation.setObjectName("BtnDeleteOperation")
        self.BtnUp = QtWidgets.QPushButton(self.frameOperation)
        self.BtnUp.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.BtnUp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../utils/icons/caret-up-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnUp.setIcon(icon1)
        self.BtnUp.setObjectName("BtnUp")
        self.BtnDown = QtWidgets.QPushButton(self.frameOperation)
        self.BtnDown.setGeometry(QtCore.QRect(10, 35, 31, 16))
        self.BtnDown.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../utils/icons/caret-down-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnDown.setIcon(icon2)
        self.BtnDown.setObjectName("BtnDown")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.labelOperation = QtWidgets.QLabel(self.tab)
        self.labelOperation.setGeometry(QtCore.QRect(170, 50, 51, 16))
        self.labelOperation.setObjectName("labelOperation")
        self.labelProductName = QtWidgets.QLabel(self.tab)
        self.labelProductName.setGeometry(QtCore.QRect(640, 0, 121, 16))
        self.labelProductName.setObjectName("labelProductName")
        self.labelCustomer = QtWidgets.QLabel(self.tab)
        self.labelCustomer.setGeometry(QtCore.QRect(240, 0, 171, 16))
        self.labelCustomer.setObjectName("labelCustomer")
        self.labelDate = QtWidgets.QLabel(self.tab)
        self.labelDate.setGeometry(QtCore.QRect(90, 0, 31, 16))
        self.labelDate.setObjectName("labelDate")
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(10, 40, 951, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(500, 20, 461, 20))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setLineWidth(2)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.LbProductName = QtWidgets.QLabel(self.frame_3)
        self.LbProductName.setGeometry(QtCore.QRect(10, 2, 386, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LbProductName.setFont(font)
        self.LbProductName.setObjectName("LbProductName")
        self.label_customer_10 = QtWidgets.QLabel(self.frame_3)
        self.label_customer_10.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_10.setFont(font)
        self.label_customer_10.setObjectName("label_customer_10")
        self.line_5 = QtWidgets.QFrame(self.frame_3)
        self.line_5.setGeometry(QtCore.QRect(390, 1, 18, 18))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.LbQuantity = QtWidgets.QLabel(self.frame_3)
        self.LbQuantity.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LbQuantity.setFont(font)
        self.LbQuantity.setObjectName("LbQuantity")
        self.labelNum = QtWidgets.QLabel(self.tab)
        self.labelNum.setGeometry(QtCore.QRect(80, 50, 21, 16))
        self.labelNum.setObjectName("labelNum")
        self.labelQuantity = QtWidgets.QLabel(self.tab)
        self.labelQuantity.setGeometry(QtCore.QRect(890, 0, 61, 16))
        self.labelQuantity.setObjectName("labelQuantity")
        self.labelWorks = QtWidgets.QLabel(self.tab)
        self.labelWorks.setGeometry(QtCore.QRect(570, 50, 51, 16))
        self.labelWorks.setObjectName("labelWorks")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 20, 491, 20))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(40, 1, 10, 18))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(150, 1, 18, 18))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.LbCheckNumber = QtWidgets.QLabel(self.frame)
        self.LbCheckNumber.setGeometry(QtCore.QRect(10, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LbCheckNumber.setFont(font)
        self.LbCheckNumber.setObjectName("LbCheckNumber")
        self.LbCustomer = QtWidgets.QLabel(self.frame)
        self.LbCustomer.setGeometry(QtCore.QRect(170, 2, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LbCustomer.setFont(font)
        self.LbCustomer.setObjectName("LbCustomer")
        self.LbDate = QtWidgets.QLabel(self.frame)
        self.LbDate.setGeometry(QtCore.QRect(60, 2, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.LbDate.setFont(font)
        self.LbDate.setObjectName("LbDate")
        self.label_customer_6 = QtWidgets.QLabel(self.frame)
        self.label_customer_6.setGeometry(QtCore.QRect(950, 2, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_6.setFont(font)
        self.label_customer_6.setObjectName("label_customer_6")
        self.tabWidgetDetail.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidgetDetail.addTab(self.tab_2, "")
        TechnologicalPassport.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TechnologicalPassport)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 991, 21))
        self.menubar.setObjectName("menubar")
        TechnologicalPassport.setMenuBar(self.menubar)

        self.retranslateUi(TechnologicalPassport)
        self.tabWidgetDetail.setCurrentIndex(0)
        self.comboBoxOperations.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(TechnologicalPassport)

    def retranslateUi(self, TechnologicalPassport):
        _translate = QtCore.QCoreApplication.translate
        TechnologicalPassport.setWindowTitle(_translate("TechnologicalPassport", "Разработка технологического паспорта"))
        self.BtnBack.setText(_translate("TechnologicalPassport", "Назад"))
        self.BtnNext.setText(_translate("TechnologicalPassport", "Далее"))
        self.BtnAddNewDetail.setText(_translate("TechnologicalPassport", "+"))
        self.labelCheckNumber.setText(_translate("TechnologicalPassport", "№ счёта"))
        self.LbOperationNumber.setText(_translate("TechnologicalPassport", "1"))
        self.labelOperation.setText(_translate("TechnologicalPassport", "Операция"))
        self.labelProductName.setText(_translate("TechnologicalPassport", "Наименование изделия"))
        self.labelCustomer.setText(_translate("TechnologicalPassport", "Название организации заказчика"))
        self.labelDate.setText(_translate("TechnologicalPassport", "Дата"))
        self.LbProductName.setText(_translate("TechnologicalPassport", "Нож КСША 40.00.004"))
        self.label_customer_10.setText(_translate("TechnologicalPassport", "1000"))
        self.LbQuantity.setText(_translate("TechnologicalPassport", "1000"))
        self.labelNum.setText(_translate("TechnologicalPassport", "№"))
        self.labelQuantity.setText(_translate("TechnologicalPassport", "Количество"))
        self.labelWorks.setText(_translate("TechnologicalPassport", "Работы"))
        self.LbCheckNumber.setText(_translate("TechnologicalPassport", "142"))
        self.LbCustomer.setText(_translate("TechnologicalPassport", "ООО \"Белагро Бел\""))
        self.LbDate.setText(_translate("TechnologicalPassport", "26.07.2024"))
        self.label_customer_6.setText(_translate("TechnologicalPassport", "1000"))
        self.tabWidgetDetail.setTabText(self.tabWidgetDetail.indexOf(self.tab), _translate("TechnologicalPassport", "Деталь 1"))
        self.tabWidgetDetail.setTabText(self.tabWidgetDetail.indexOf(self.tab_2), _translate("TechnologicalPassport", "Деталь 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TechnologicalPassport = QtWidgets.QMainWindow()
    ui = Ui_TechnologicalPassport()
    ui.setupUi(TechnologicalPassport)
    TechnologicalPassport.show()
    sys.exit(app.exec_())
