# Generated by Django 5.1.4 on 2025-03-06 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('density', models.FloatField()),
                ('standard', models.CharField(max_length=25)),
                ('website_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RodForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_shape', models.CharField(max_length=20)),
                ('section_size1', models.FloatField()),
                ('section_size2', models.FloatField(blank=True, null=True)),
                ('bar_length', models.FloatField()),
                ('standard', models.CharField(max_length=25)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
        ),
        migrations.CreateModel(
            name='SheetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(max_length=25)),
                ('thickness', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material')),
            ],
        ),
    ]
