from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderDev(object):
    def setupUi(self, OrderDev):
        OrderDev.setObjectName("OrderDev")
        OrderDev.resize(1129, 771)
        OrderDev.setWindowTitle("Разработка нового заказа")
        self.centralwidget = QtWidgets.QWidget(OrderDev)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_status = QtWidgets.QPushButton(self.widget)
        self.pushButton_status.setMaximumSize(QtCore.QSize(50, 20))
        self.pushButton_status.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_status.setText("")
        self.pushButton_status.setObjectName("pushButton_status")
        self.horizontalLayout.addWidget(self.pushButton_status)
        self.frame_customer = QtWidgets.QFrame(self.widget)
        self.frame_customer.setMinimumSize(QtCore.QSize(500, 0))
        self.frame_customer.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame_customer.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_customer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_customer.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_customer.setLineWidth(2)
        self.frame_customer.setMidLineWidth(1)
        self.frame_customer.setObjectName("frame_customer")
        self.line_2 = QtWidgets.QFrame(self.frame_customer)
        self.line_2.setGeometry(QtCore.QRect(40, 1, 10, 18))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame_customer)
        self.line_3.setGeometry(QtCore.QRect(124, 1, 18, 18))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_check_number = QtWidgets.QLabel(self.frame_customer)
        self.label_check_number.setGeometry(QtCore.QRect(10, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_check_number.setFont(font)
        self.label_check_number.setText("142")
        self.label_check_number.setObjectName("label_check_number")
        self.label_customer = QtWidgets.QLabel(self.frame_customer)
        self.label_customer.setGeometry(QtCore.QRect(140, 2, 355, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer.setFont(font)
        self.label_customer.setText("ООО \"Белагро Бел\"")
        self.label_customer.setObjectName("label_customer")
        self.label_date_of_task = QtWidgets.QLabel(self.frame_customer)
        self.label_date_of_task.setGeometry(QtCore.QRect(54, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_date_of_task.setFont(font)
        self.label_date_of_task.setText("26.07.2024")
        self.label_date_of_task.setObjectName("label_date_of_task")
        self.horizontalLayout.addWidget(self.frame_customer)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_developer_text = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_developer_text.setFont(font)
        self.label_developer_text.setText("Разработчик:")
        self.label_developer_text.setObjectName("label_developer_text")
        self.horizontalLayout.addWidget(self.label_developer_text)
        self.comboBox_developer = QtWidgets.QComboBox(self.widget)
        self.comboBox_developer.setMinimumSize(QtCore.QSize(150, 0))
        self.comboBox_developer.setMaximumSize(QtCore.QSize(150, 16777215))
        self.comboBox_developer.setCurrentText("")
        self.comboBox_developer.setObjectName("comboBox_developer")
        self.horizontalLayout.addWidget(self.comboBox_developer)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_save = QtWidgets.QPushButton(self.widget)
        self.button_save.setMinimumSize(QtCore.QSize(100, 40))
        self.button_save.setMaximumSize(QtCore.QSize(40, 40))
        self.button_save.setText("Сохранить")
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap("pic/floppy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        # self.button_save.setIcon(icon)
        self.button_save.setObjectName("button_save")
        self.horizontalLayout.addWidget(self.button_save)
        self.verticalLayout.addWidget(self.widget)
        self.tabWidget_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_main.setObjectName("tabWidget_main")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.tab)
        self.widget_2.setMaximumSize(QtCore.QSize(440, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_title_products = QtWidgets.QLabel(self.widget_2)
        self.label_title_products.setText("Данные по заданию:")
        self.label_title_products.setObjectName("label_title_products")
        self.verticalLayout_2.addWidget(self.label_title_products)
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 35))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_product_name_text = QtWidgets.QLabel(self.widget_4)
        self.label_product_name_text.setMinimumSize(QtCore.QSize(220, 0))
        self.label_product_name_text.setText("Наименование изделия:")
        self.label_product_name_text.setObjectName("label_product_name_text")
        self.horizontalLayout_3.addWidget(self.label_product_name_text)
        self.label_quantity_text = QtWidgets.QLabel(self.widget_4)
        self.label_quantity_text.setMinimumSize(QtCore.QSize(130, 0))
        self.label_quantity_text.setText("Количество:")
        self.label_quantity_text.setObjectName("label_quantity_text")
        self.horizontalLayout_3.addWidget(self.label_quantity_text)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.widget_2)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(420, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(420, 16777215))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 401, 565))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_product = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_product.setMinimumSize(QtCore.QSize(380, 45))
        self.frame_product.setMaximumSize(QtCore.QSize(380, 16777215))
        self.frame_product.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_product.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_product.setObjectName("frame_product")
        self.frame_product_inside = QtWidgets.QFrame(self.frame_product)
        self.frame_product_inside.setGeometry(QtCore.QRect(28, 7, 301, 30))
        self.frame_product_inside.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_product_inside.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_product_inside.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_product_inside.setLineWidth(2)
        self.frame_product_inside.setMidLineWidth(1)
        self.frame_product_inside.setObjectName("frame_product_inside")
        self.label_product_name = QtWidgets.QLabel(self.frame_product_inside)
        self.label_product_name.setGeometry(QtCore.QRect(10, 5, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_product_name.setFont(font)
        self.label_product_name.setText("Нож КСША 40.00.004")
        self.label_product_name.setObjectName("label_product_name")

        self.line_10 = QtWidgets.QFrame(self.frame_product_inside)
        self.line_10.setGeometry(QtCore.QRect(238, 1, 18, 27))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label_quantity_of_task = QtWidgets.QLabel(self.frame_product_inside)
        self.label_quantity_of_task.setGeometry(QtCore.QRect(250, 7, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_quantity_of_task.setFont(font)
        self.label_quantity_of_task.setText("1000")
        self.label_quantity_of_task.setObjectName("label_quantity_of_task")
        self.label_product_number = QtWidgets.QLabel(self.frame_product)
        self.label_product_number.setGeometry(QtCore.QRect(6, 15, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_product_number.setFont(font)
        self.label_product_number.setText("1")
        self.label_product_number.setObjectName("label_product_number")
        self.button_design_document = QtWidgets.QPushButton(self.frame_product)
        self.button_design_document.setGeometry(QtCore.QRect(336, 6, 40, 30))
        self.button_design_document.setText("КД")
        self.button_design_document.setObjectName("button_design_document")
        self.verticalLayout_4.addWidget(self.frame_product)
        spacerItem3 = QtWidgets.QSpacerItem(20, 503, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.tab)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_title_products_hierarchy = QtWidgets.QLabel(self.widget_3)
        self.label_title_products_hierarchy.setText("Необходимо отметить элементы КД, которые входят в заказ:")
        self.label_title_products_hierarchy.setObjectName("label_title_products_hierarchy")
        self.verticalLayout_3.addWidget(self.label_title_products_hierarchy)
        self.scrollArea = QtWidgets.QScrollArea(self.widget_3)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 604, 606))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.tabWidget_main.addTab(self.tab, "Привязка КД")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.tab_2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.tabWidget_main.addTab(self.tab_2, "Изделие 1")
        self.verticalLayout.addWidget(self.tabWidget_main)
        OrderDev.setCentralWidget(self.centralwidget)

        self.tabWidget_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OrderDev)

