from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderDev(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 721)
        MainWindow.setWindowTitle("Разработка задания")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 20, 586, 20))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")

        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(40, 1, 10, 18))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(150, 1, 18, 18))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.label_text_date_of_task = QtWidgets.QLabel(self.centralwidget)
        self.label_text_date_of_task.setGeometry(QtCore.QRect(60, 0, 51, 16))
        self.label_text_date_of_task.setObjectName("label_3")
        self.label_text_date_of_task.setText("№ счёта")

        self.label_check_number = QtWidgets.QLabel(self.frame)
        self.label_check_number.setGeometry(QtCore.QRect(10, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_check_number.setFont(font)
        self.label_check_number.setObjectName("label_4")
        self.label_check_number.setText("142")

        self.label_customer = QtWidgets.QLabel(self.frame)
        self.label_customer.setGeometry(QtCore.QRect(165, 2, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer.setFont(font)
        self.label_customer.setObjectName("label_customer")
        self.label_customer.setText("ООО \"Белагро Бел\"")

        self.label_date_of_task = QtWidgets.QLabel(self.frame)
        self.label_date_of_task.setGeometry(QtCore.QRect(60, 2, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_date_of_task.setFont(font)
        self.label_date_of_task.setObjectName("date_of_task")
        self.label_date_of_task.setText("26.07.2024")

        self.label_date_text = QtWidgets.QLabel(self.centralwidget)
        self.label_date_text.setGeometry(QtCore.QRect(140, 0, 31, 16))
        self.label_date_text.setObjectName("label_date_text")
        self.label_date_text.setText("Дата")

        self.label_customer_text = QtWidgets.QLabel(self.centralwidget)
        self.label_customer_text.setGeometry(QtCore.QRect(290, 0, 171, 16))
        self.label_customer_text.setObjectName("label_10")
        self.label_customer_text.setText("Название организации заказчика")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 55, 1006, 641))
        self.tabWidget.setObjectName("tabWidget")

        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")

        self.frame_6 = QtWidgets.QFrame(self.tab_11)
        self.frame_6.setGeometry(QtCore.QRect(5, 20, 373, 51))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")

        self.label_96 = QtWidgets.QLabel(self.frame_6)
        self.label_96.setGeometry(QtCore.QRect(268, 0, 61, 16))
        self.label_96.setObjectName("label_96")

        self.label_97 = QtWidgets.QLabel(self.frame_6)
        self.label_97.setGeometry(QtCore.QRect(38, 0, 121, 16))
        self.label_97.setObjectName("label_97")

        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(28, 20, 301, 20))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_7.setLineWidth(2)
        self.frame_7.setMidLineWidth(1)
        self.frame_7.setObjectName("frame_7")

        self.label_98 = QtWidgets.QLabel(self.frame_7)
        self.label_98.setGeometry(QtCore.QRect(10, 2, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_98.setFont(font)
        self.label_98.setObjectName("label_98")

        self.label_customer_13 = QtWidgets.QLabel(self.frame_7)
        self.label_customer_13.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_13.setFont(font)
        self.label_customer_13.setObjectName("label_customer_13")

        self.line_10 = QtWidgets.QFrame(self.frame_7)
        self.line_10.setGeometry(QtCore.QRect(240, 1, 18, 18))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")

        self.label_99 = QtWidgets.QLabel(self.frame_7)
        self.label_99.setGeometry(QtCore.QRect(250, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")

        self.label_100 = QtWidgets.QLabel(self.frame_6)
        self.label_100.setGeometry(QtCore.QRect(6, 22, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")

        self.pushButton_10 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_10.setGeometry(QtCore.QRect(336, 19, 26, 23))
        self.pushButton_10.setObjectName("pushButton_10")

        self.label_101 = QtWidgets.QLabel(self.tab_11)
        self.label_101.setGeometry(QtCore.QRect(20, 0, 106, 16))
        self.label_101.setObjectName("label_101")

        self.label_192 = QtWidgets.QLabel(self.tab_11)
        self.label_192.setGeometry(QtCore.QRect(514, 0, 323, 16))
        self.label_192.setObjectName("label_192")

        self.scrollArea = QtWidgets.QScrollArea(self.tab_11)
        self.scrollArea.setGeometry(QtCore.QRect(385, 21, 611, 585))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 592, 583))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.frame_17 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_17.setGeometry(QtCore.QRect(30, 190, 571, 21))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")

        self.frame_28 = QtWidgets.QFrame(self.frame_17)
        self.frame_28.setGeometry(QtCore.QRect(30, 0, 461, 20))
        self.frame_28.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_28.setLineWidth(2)
        self.frame_28.setMidLineWidth(1)
        self.frame_28.setObjectName("frame_28")

        self.label_209 = QtWidgets.QLabel(self.frame_28)
        self.label_209.setGeometry(QtCore.QRect(10, 2, 346, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_209.setFont(font)
        self.label_209.setObjectName("label_209")

        self.label_customer_32 = QtWidgets.QLabel(self.frame_28)
        self.label_customer_32.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_32.setFont(font)
        self.label_customer_32.setObjectName("label_customer_32")

        self.line_25 = QtWidgets.QFrame(self.frame_28)
        self.line_25.setGeometry(QtCore.QRect(390, 1, 18, 18))
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")

        self.label_210 = QtWidgets.QLabel(self.frame_28)
        self.label_210.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_210.setFont(font)
        self.label_210.setObjectName("label_210")

        self.label_191 = QtWidgets.QLabel(self.frame_17)
        self.label_191.setGeometry(QtCore.QRect(0, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_191.setFont(font)
        self.label_191.setObjectName("label_191")

        self.checkBox_10 = QtWidgets.QCheckBox(self.frame_17)
        self.checkBox_10.setGeometry(QtCore.QRect(495, 0, 16, 21))
        self.checkBox_10.setText("")
        self.checkBox_10.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_10.setObjectName("checkBox_10")

        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 571, 21))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")

        self.frame_22 = QtWidgets.QFrame(self.frame_2)
        self.frame_22.setGeometry(QtCore.QRect(30, 0, 461, 20))
        self.frame_22.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_22.setLineWidth(2)
        self.frame_22.setMidLineWidth(1)
        self.frame_22.setObjectName("frame_22")

        self.label_200 = QtWidgets.QLabel(self.frame_22)
        self.label_200.setGeometry(QtCore.QRect(10, 2, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_200.setFont(font)
        self.label_200.setObjectName("label_200")

        self.label_customer_26 = QtWidgets.QLabel(self.frame_22)
        self.label_customer_26.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_26.setFont(font)
        self.label_customer_26.setObjectName("label_customer_26")

        self.line_22 = QtWidgets.QFrame(self.frame_22)
        self.line_22.setGeometry(QtCore.QRect(390, 1, 18, 18))
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")

        self.label_201 = QtWidgets.QLabel(self.frame_22)
        self.label_201.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_201.setFont(font)
        self.label_201.setObjectName("label_201")

        self.label_93 = QtWidgets.QLabel(self.frame_2)
        self.label_93.setGeometry(QtCore.QRect(0, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")

        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_3.setGeometry(QtCore.QRect(495, 0, 16, 21))
        self.checkBox_3.setText("")
        self.checkBox_3.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_3.setObjectName("checkBox_3")

        self.frame_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_16.setGeometry(QtCore.QRect(30, 160, 571, 21))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")

        self.frame_26 = QtWidgets.QFrame(self.frame_16)
        self.frame_26.setGeometry(QtCore.QRect(30, 0, 461, 20))
        self.frame_26.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_26.setLineWidth(2)
        self.frame_26.setMidLineWidth(1)
        self.frame_26.setObjectName("frame_26")

        self.label_206 = QtWidgets.QLabel(self.frame_26)
        self.label_206.setGeometry(QtCore.QRect(10, 2, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_206.setFont(font)
        self.label_206.setObjectName("label_206")

        self.label_customer_30 = QtWidgets.QLabel(self.frame_26)
        self.label_customer_30.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_30.setFont(font)
        self.label_customer_30.setObjectName("label_customer_30")

        self.line_24 = QtWidgets.QFrame(self.frame_26)
        self.line_24.setGeometry(QtCore.QRect(390, 1, 18, 18))
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")

        self.label_207 = QtWidgets.QLabel(self.frame_26)
        self.label_207.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_207.setFont(font)
        self.label_207.setObjectName("label_207")

        self.label_103 = QtWidgets.QLabel(self.frame_16)
        self.label_103.setGeometry(QtCore.QRect(0, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_103.setFont(font)
        self.label_103.setObjectName("label_103")

        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_16)
        self.checkBox_9.setGeometry(QtCore.QRect(495, 0, 16, 21))
        self.checkBox_9.setText("")
        self.checkBox_9.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_9.setObjectName("checkBox_9")

        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_8.setGeometry(QtCore.QRect(30, 130, 571, 21))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")

        self.frame_24 = QtWidgets.QFrame(self.frame_8)
        self.frame_24.setGeometry(QtCore.QRect(30, 0, 461, 20))
        self.frame_24.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_24.setLineWidth(2)
        self.frame_24.setMidLineWidth(1)
        self.frame_24.setObjectName("frame_24")

        self.label_203 = QtWidgets.QLabel(self.frame_24)
        self.label_203.setGeometry(QtCore.QRect(10, 2, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_203.setFont(font)
        self.label_203.setObjectName("label_203")

        self.label_customer_28 = QtWidgets.QLabel(self.frame_24)
        self.label_customer_28.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_28.setFont(font)
        self.label_customer_28.setObjectName("label_customer_28")

        self.line_23 = QtWidgets.QFrame(self.frame_24)
        self.line_23.setGeometry(QtCore.QRect(390, 1, 18, 18))
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")

        self.label_204 = QtWidgets.QLabel(self.frame_24)
        self.label_204.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_204.setFont(font)
        self.label_204.setObjectName("label_204")

        self.label_102 = QtWidgets.QLabel(self.frame_8)
        self.label_102.setGeometry(QtCore.QRect(0, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_102.setFont(font)
        self.label_102.setObjectName("label_102")

        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_8.setGeometry(QtCore.QRect(495, 0, 16, 21))
        self.checkBox_8.setText("")
        self.checkBox_8.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_8.setObjectName("checkBox_8")

        self.frame_18 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_18.setGeometry(QtCore.QRect(30, 40, 571, 21))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")

        self.frame_30 = QtWidgets.QFrame(self.frame_18)
        self.frame_30.setGeometry(QtCore.QRect(30, 0, 461, 20))
        self.frame_30.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_30.setLineWidth(2)
        self.frame_30.setMidLineWidth(1)
        self.frame_30.setObjectName("frame_30")

        self.label_212 = QtWidgets.QLabel(self.frame_30)
        self.label_212.setGeometry(QtCore.QRect(10, 2, 361, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_212.setFont(font)
        self.label_212.setObjectName("label_212")

        self.label_customer_34 = QtWidgets.QLabel(self.frame_30)
        self.label_customer_34.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_34.setFont(font)
        self.label_customer_34.setObjectName("label_customer_34")

        self.line_26 = QtWidgets.QFrame(self.frame_30)
        self.line_26.setGeometry(QtCore.QRect(390, 1, 18, 18))
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")

        self.label_213 = QtWidgets.QLabel(self.frame_30)
        self.label_213.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_213.setFont(font)
        self.label_213.setObjectName("label_213")

        self.label_194 = QtWidgets.QLabel(self.frame_18)
        self.label_194.setGeometry(QtCore.QRect(0, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_194.setFont(font)
        self.label_194.setObjectName("label_194")

        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_18)
        self.checkBox_4.setGeometry(QtCore.QRect(495, 0, 16, 21))
        self.checkBox_4.setText("")
        self.checkBox_4.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_4.setObjectName("checkBox_4")

        self.frame_19 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_19.setGeometry(QtCore.QRect(50, 100, 571, 21))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")

        self.frame_32 = QtWidgets.QFrame(self.frame_19)
        self.frame_32.setGeometry(QtCore.QRect(30, 0, 461, 20))
        self.frame_32.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_32.setLineWidth(2)
        self.frame_32.setMidLineWidth(1)
        self.frame_32.setObjectName("frame_32")

        self.label_215 = QtWidgets.QLabel(self.frame_32)
        self.label_215.setGeometry(QtCore.QRect(10, 2, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_215.setFont(font)
        self.label_215.setObjectName("label_215")

        self.label_customer_36 = QtWidgets.QLabel(self.frame_32)
        self.label_customer_36.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_36.setFont(font)
        self.label_customer_36.setObjectName("label_customer_36")

        self.line_27 = QtWidgets.QFrame(self.frame_32)
        self.line_27.setGeometry(QtCore.QRect(390, 1, 18, 18))
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")

        self.label_216 = QtWidgets.QLabel(self.frame_32)
        self.label_216.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_216.setFont(font)
        self.label_216.setObjectName("label_216")

        self.label_195 = QtWidgets.QLabel(self.frame_19)
        self.label_195.setGeometry(QtCore.QRect(0, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_195.setFont(font)
        self.label_195.setObjectName("label_195")

        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_19)
        self.checkBox_7.setGeometry(QtCore.QRect(495, 0, 16, 21))
        self.checkBox_7.setText("")
        self.checkBox_7.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_7.setObjectName("checkBox_7")

        self.frame_20 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_20.setGeometry(QtCore.QRect(50, 70, 571, 21))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")

        self.frame_34 = QtWidgets.QFrame(self.frame_20)
        self.frame_34.setGeometry(QtCore.QRect(30, 0, 461, 20))
        self.frame_34.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_34.setLineWidth(2)
        self.frame_34.setMidLineWidth(1)
        self.frame_34.setObjectName("frame_34")

        self.label_218 = QtWidgets.QLabel(self.frame_34)
        self.label_218.setGeometry(QtCore.QRect(10, 2, 356, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_218.setFont(font)
        self.label_218.setObjectName("label_218")

        self.label_customer_38 = QtWidgets.QLabel(self.frame_34)
        self.label_customer_38.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_38.setFont(font)
        self.label_customer_38.setObjectName("label_customer_38")

        self.line_28 = QtWidgets.QFrame(self.frame_34)
        self.line_28.setGeometry(QtCore.QRect(390, 1, 18, 18))
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")

        self.label_219 = QtWidgets.QLabel(self.frame_34)
        self.label_219.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_219.setFont(font)
        self.label_219.setObjectName("label_219")

        self.label_196 = QtWidgets.QLabel(self.frame_20)
        self.label_196.setGeometry(QtCore.QRect(0, 0, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_196.setFont(font)
        self.label_196.setObjectName("label_196")

        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_20)
        self.checkBox_6.setGeometry(QtCore.QRect(495, 0, 16, 21))
        self.checkBox_6.setText("")
        self.checkBox_6.setIconSize(QtCore.QSize(20, 20))
        self.checkBox_6.setObjectName("checkBox_6")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_5 = QtWidgets.QFrame(self.tab_11)
        self.frame_5.setGeometry(QtCore.QRect(610, 10, 381, 21))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")

        self.tabWidget.addTab(self.tab_11, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(500, 0, 71, 16))
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")

        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(10, 44, 981, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.label_74 = QtWidgets.QLabel(self.tab)
        self.label_74.setGeometry(QtCore.QRect(832, 14, 156, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_74.setFont(font)
        self.label_74.setToolTipDuration(3000)
        self.label_74.setObjectName("label_74")

        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(160, 0, 121, 16))
        self.label_11.setObjectName("label_11")

        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(20, 20, 461, 20))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setLineWidth(2)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName("frame_3")

        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 2, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.label_customer_10 = QtWidgets.QLabel(self.frame_3)
        self.label_customer_10.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_10.setFont(font)
        self.label_customer_10.setObjectName("label_customer_10")

        self.line_5 = QtWidgets.QFrame(self.frame_3)
        self.line_5.setGeometry(QtCore.QRect(390, 1, 18, 18))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(410, 0, 61, 16))
        self.label_9.setObjectName("label_9")

        self.lineEdit_96 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_96.setGeometry(QtCore.QRect(500, 20, 71, 20))
        self.lineEdit_96.setText("")
        self.lineEdit_96.setObjectName("lineEdit_96")

        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(660, 40, 321, 21))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")

        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 62, 993, 551))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")

        self.tabWidget_2 = QtWidgets.QTabWidget(self.page)
        self.tabWidget_2.setGeometry(QtCore.QRect(4, 22, 351, 443))
        self.tabWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget_2.setObjectName("tabWidget_2")

        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(164, 0, 183, 213))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pic/circle.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 73, 101, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")

        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(10, 78, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 103, 101, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(10, 108, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setToolTipDuration(3000)
        self.label_20.setObjectName("label_20")

        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(70, 53, 41, 16))
        self.label_21.setObjectName("label_21")

        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 302, 31, 23))
        self.pushButton_2.setObjectName("pushButton_2")

        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(10, 282, 101, 16))
        self.label_35.setObjectName("label_35")

        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 302, 281, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")

        self.label_39 = QtWidgets.QLabel(self.tab_3)
        self.label_39.setGeometry(QtCore.QRect(10, 332, 91, 16))
        self.label_39.setObjectName("label_39")

        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 352, 281, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")

        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_2.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")

        self.tabWidget_2.addTab(self.tab_3, "")

        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")

        self.label_8 = QtWidgets.QLabel(self.tab_7)
        self.label_8.setGeometry(QtCore.QRect(170, 0, 179, 227))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("pic/hexagon.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")

        self.label_22 = QtWidgets.QLabel(self.tab_7)
        self.label_22.setGeometry(QtCore.QRect(78, 88, 41, 16))
        self.label_22.setObjectName("label_22")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_4.setGeometry(QtCore.QRect(58, 108, 101, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")

        self.label_23 = QtWidgets.QLabel(self.tab_7)
        self.label_23.setGeometry(QtCore.QRect(18, 113, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")

        self.label_24 = QtWidgets.QLabel(self.tab_7)
        self.label_24.setGeometry(QtCore.QRect(18, 143, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setToolTipDuration(3000)
        self.label_24.setObjectName("label_24")

        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_5.setGeometry(QtCore.QRect(58, 138, 101, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.label_40 = QtWidgets.QLabel(self.tab_7)
        self.label_40.setGeometry(QtCore.QRect(10, 326, 91, 16))
        self.label_40.setObjectName("label_40")

        self.pushButton_3 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 296, 31, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setGeometry(QtCore.QRect(10, 276, 101, 16))
        self.label_36.setObjectName("label_36")

        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 346, 281, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")

        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 296, 281, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")

        self.checkBox_17 = QtWidgets.QCheckBox(self.tab_7)
        self.checkBox_17.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_17.setText("")
        self.checkBox_17.setObjectName("checkBox_17")

        self.tabWidget_2.addTab(self.tab_7, "")

        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")

        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(176, 0, 171, 233))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("pic/pipe.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")

        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(70, 38, 41, 16))
        self.label_25.setObjectName("label_25")

        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 58, 101, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(10, 63, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")

        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(10, 123, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setToolTipDuration(3000)
        self.label_27.setObjectName("label_27")

        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(50, 118, 101, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_8.setGeometry(QtCore.QRect(50, 88, 101, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")

        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(10, 93, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")

        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(10, 330, 91, 16))
        self.label_41.setObjectName("label_41")

        self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 300, 31, 23))
        self.pushButton_4.setObjectName("pushButton_4")

        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(10, 280, 101, 16))
        self.label_37.setObjectName("label_37")

        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 350, 281, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")

        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 300, 281, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")

        self.checkBox_18 = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_18.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_18.setText("")
        self.checkBox_18.setObjectName("checkBox_18")

        self.tabWidget_2.addTab(self.tab_4, "")

        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")

        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(192, 0, 155, 197))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("pic/square.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")

        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(74, 49, 41, 16))
        self.label_29.setObjectName("label_29")

        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_9.setGeometry(QtCore.QRect(54, 99, 101, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")

        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(54, 69, 101, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")

        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(14, 74, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")

        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(14, 104, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setToolTipDuration(3000)
        self.label_31.setObjectName("label_31")

        self.label_42 = QtWidgets.QLabel(self.tab_5)
        self.label_42.setGeometry(QtCore.QRect(10, 288, 91, 16))
        self.label_42.setObjectName("label_42")

        self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 258, 31, 23))
        self.pushButton_5.setObjectName("pushButton_5")

        self.label_38 = QtWidgets.QLabel(self.tab_5)
        self.label_38.setGeometry(QtCore.QRect(10, 238, 101, 16))
        self.label_38.setObjectName("label_38")

        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 308, 281, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")

        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 258, 281, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")

        self.checkBox_19 = QtWidgets.QCheckBox(self.tab_5)
        self.checkBox_19.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_19.setText("")
        self.checkBox_19.setObjectName("checkBox_19")

        self.tabWidget_2.addTab(self.tab_5, "")

        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")

        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(16, 91, 71, 16))
        self.label_32.setToolTip("")
        self.label_32.setToolTipDuration(-1)
        self.label_32.setObjectName("label_32")

        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(86, 86, 51, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")

        self.label_33 = QtWidgets.QLabel(self.tab_6)
        self.label_33.setGeometry(QtCore.QRect(16, 121, 61, 16))
        self.label_33.setToolTip("")
        self.label_33.setToolTipDuration(-1)
        self.label_33.setObjectName("label_33")

        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(86, 116, 91, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")

        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_13.setGeometry(QtCore.QRect(86, 146, 91, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")

        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(16, 151, 61, 16))
        self.label_34.setToolTip("")
        self.label_34.setToolTipDuration(-1)
        self.label_34.setObjectName("label_34")

        self.label_43 = QtWidgets.QLabel(self.tab_6)
        self.label_43.setGeometry(QtCore.QRect(10, 304, 91, 16))
        self.label_43.setObjectName("label_43")

        self.pushButton_6 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 274, 31, 23))
        self.pushButton_6.setObjectName("pushButton_6")

        self.label_44 = QtWidgets.QLabel(self.tab_6)
        self.label_44.setGeometry(QtCore.QRect(10, 254, 101, 16))
        self.label_44.setObjectName("label_44")

        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 324, 281, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")

        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_23.setGeometry(QtCore.QRect(10, 274, 281, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")

        self.checkBox_20 = QtWidgets.QCheckBox(self.tab_6)
        self.checkBox_20.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_20.setText("")
        self.checkBox_20.setObjectName("checkBox_20")

        self.tabWidget_2.addTab(self.tab_6, "")

        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(18, 0, 141, 20))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_15.setText("Выбор материала и формы:")

        self.tabWidget_3 = QtWidgets.QTabWidget(self.page)
        self.tabWidget_3.setGeometry(QtCore.QRect(376, 20, 613, 501))
        self.tabWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget_3.setObjectName("tabWidget_3")

        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")

        self.label_14 = QtWidgets.QLabel(self.tab_8)
        self.label_14.setGeometry(QtCore.QRect(80, 0, 521, 211))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("pic/single_proc_2.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")

        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_40.setGeometry(QtCore.QRect(110, 245, 51, 20))
        self.lineEdit_40.setObjectName("lineEdit_40")

        self.label_71 = QtWidgets.QLabel(self.tab_8)
        self.label_71.setGeometry(QtCore.QRect(10, 280, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setToolTipDuration(3000)
        self.label_71.setObjectName("label_71")

        self.label_72 = QtWidgets.QLabel(self.tab_8)
        self.label_72.setGeometry(QtCore.QRect(10, 340, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setToolTipDuration(3000)
        self.label_72.setObjectName("label_72")

        self.label_73 = QtWidgets.QLabel(self.tab_8)
        self.label_73.setGeometry(QtCore.QRect(10, 220, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_73.setFont(font)
        self.label_73.setToolTipDuration(3000)
        self.label_73.setObjectName("label_73")

        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_43.setGeometry(QtCore.QRect(110, 215, 51, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")

        self.lineEdit_44 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_44.setGeometry(QtCore.QRect(110, 335, 51, 20))
        self.lineEdit_44.setObjectName("lineEdit_44")

        self.label_76 = QtWidgets.QLabel(self.tab_8)
        self.label_76.setGeometry(QtCore.QRect(10, 250, 98, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setToolTipDuration(3000)
        self.label_76.setObjectName("label_76")

        self.label_77 = QtWidgets.QLabel(self.tab_8)
        self.label_77.setGeometry(QtCore.QRect(10, 310, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setToolTipDuration(3000)
        self.label_77.setObjectName("label_77")

        self.lineEdit_45 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_45.setGeometry(QtCore.QRect(110, 305, 51, 20))
        self.lineEdit_45.setObjectName("lineEdit_45")

        self.lineEdit_46 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_46.setGeometry(QtCore.QRect(110, 275, 51, 20))
        self.lineEdit_46.setObjectName("lineEdit_46")

        self.label_79 = QtWidgets.QLabel(self.tab_8)
        self.label_79.setGeometry(QtCore.QRect(200, 220, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")

        self.label_80 = QtWidgets.QLabel(self.tab_8)
        self.label_80.setGeometry(QtCore.QRect(200, 250, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")

        self.label_81 = QtWidgets.QLabel(self.tab_8)
        self.label_81.setGeometry(QtCore.QRect(200, 280, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")

        self.line_8 = QtWidgets.QFrame(self.tab_8)
        self.line_8.setGeometry(QtCore.QRect(170, 210, 20, 201))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")

        self.pushButton_7 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_7.setGeometry(QtCore.QRect(510, 435, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")

        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_22.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")

        self.tabWidget_3.addTab(self.tab_8, "")

        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")

        self.label_50 = QtWidgets.QLabel(self.tab_9)
        self.label_50.setGeometry(QtCore.QRect(30, 0, 571, 211))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap("pic/complex_proc.png"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")

        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_28.setGeometry(QtCore.QRect(110, 210, 51, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")

        self.label_52 = QtWidgets.QLabel(self.tab_9)
        self.label_52.setGeometry(QtCore.QRect(10, 215, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_52.setFont(font)
        self.label_52.setToolTipDuration(3000)
        self.label_52.setObjectName("label_52")

        self.label_53 = QtWidgets.QLabel(self.tab_9)
        self.label_53.setGeometry(QtCore.QRect(10, 245, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setToolTipDuration(3000)
        self.label_53.setObjectName("label_53")

        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_29.setGeometry(QtCore.QRect(110, 240, 51, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")

        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_30.setGeometry(QtCore.QRect(110, 270, 51, 20))
        self.lineEdit_30.setObjectName("lineEdit_30")

        self.label_54 = QtWidgets.QLabel(self.tab_9)
        self.label_54.setGeometry(QtCore.QRect(10, 275, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setToolTipDuration(3000)
        self.label_54.setObjectName("label_54")

        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_31.setGeometry(QtCore.QRect(110, 300, 51, 20))
        self.lineEdit_31.setObjectName("lineEdit_31")

        self.label_55 = QtWidgets.QLabel(self.tab_9)
        self.label_55.setGeometry(QtCore.QRect(10, 305, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setToolTipDuration(3000)
        self.label_55.setObjectName("label_55")

        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_37.setGeometry(QtCore.QRect(110, 330, 51, 20))
        self.lineEdit_37.setObjectName("lineEdit_37")

        self.label_63 = QtWidgets.QLabel(self.tab_9)
        self.label_63.setGeometry(QtCore.QRect(10, 335, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setToolTipDuration(3000)
        self.label_63.setObjectName("label_63")

        self.label_64 = QtWidgets.QLabel(self.tab_9)
        self.label_64.setGeometry(QtCore.QRect(10, 365, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setToolTipDuration(3000)
        self.label_64.setObjectName("label_64")

        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_38.setGeometry(QtCore.QRect(110, 360, 51, 20))
        self.lineEdit_38.setObjectName("lineEdit_38")

        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_39.setGeometry(QtCore.QRect(110, 390, 51, 20))
        self.lineEdit_39.setObjectName("lineEdit_39")

        self.label_65 = QtWidgets.QLabel(self.tab_9)
        self.label_65.setGeometry(QtCore.QRect(10, 395, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_65.setFont(font)
        self.label_65.setToolTipDuration(3000)
        self.label_65.setObjectName("label_65")

        self.label_51 = QtWidgets.QLabel(self.tab_9)
        self.label_51.setGeometry(QtCore.QRect(200, 220, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")

        self.label_66 = QtWidgets.QLabel(self.tab_9)
        self.label_66.setGeometry(QtCore.QRect(200, 250, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")

        self.line_7 = QtWidgets.QFrame(self.tab_9)
        self.line_7.setGeometry(QtCore.QRect(170, 210, 20, 201))
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.label_67 = QtWidgets.QLabel(self.tab_9)
        self.label_67.setGeometry(QtCore.QRect(200, 280, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")

        self.label_68 = QtWidgets.QLabel(self.tab_9)
        self.label_68.setGeometry(QtCore.QRect(200, 310, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")

        self.label_69 = QtWidgets.QLabel(self.tab_9)
        self.label_69.setGeometry(QtCore.QRect(200, 340, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")

        self.label_70 = QtWidgets.QLabel(self.tab_9)
        self.label_70.setGeometry(QtCore.QRect(200, 370, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")

        self.pushButton = QtWidgets.QPushButton(self.tab_9)
        self.pushButton.setGeometry(QtCore.QRect(510, 435, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_21.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")

        self.tabWidget_3.addTab(self.tab_9, "")

        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")

        self.label_56 = QtWidgets.QLabel(self.tab_10)
        self.label_56.setGeometry(QtCore.QRect(270, 0, 331, 231))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("pic/sheet_2.png"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")

        self.pushButton_8 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_8.setGeometry(QtCore.QRect(510, 435, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")

        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_32.setGeometry(QtCore.QRect(140, 40, 51, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")

        self.label_57 = QtWidgets.QLabel(self.tab_10)
        self.label_57.setGeometry(QtCore.QRect(40, 75, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setToolTipDuration(3000)
        self.label_57.setObjectName("label_57")

        self.label_58 = QtWidgets.QLabel(self.tab_10)
        self.label_58.setGeometry(QtCore.QRect(40, 15, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_58.setFont(font)
        self.label_58.setToolTipDuration(3000)
        self.label_58.setObjectName("label_58")

        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_33.setGeometry(QtCore.QRect(140, 10, 51, 20))
        self.lineEdit_33.setObjectName("lineEdit_33")

        self.label_59 = QtWidgets.QLabel(self.tab_10)
        self.label_59.setGeometry(QtCore.QRect(40, 45, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setToolTipDuration(3000)
        self.label_59.setObjectName("label_59")

        self.label_60 = QtWidgets.QLabel(self.tab_10)
        self.label_60.setGeometry(QtCore.QRect(40, 105, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setToolTipDuration(3000)
        self.label_60.setObjectName("label_60")

        self.lineEdit_34 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_34.setGeometry(QtCore.QRect(140, 100, 51, 20))
        self.lineEdit_34.setObjectName("lineEdit_34")

        self.lineEdit_35 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_35.setGeometry(QtCore.QRect(140, 70, 51, 20))
        self.lineEdit_35.setObjectName("lineEdit_35")

        self.line_9 = QtWidgets.QFrame(self.tab_10)
        self.line_9.setGeometry(QtCore.QRect(10, 240, 581, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")

        self.label_78 = QtWidgets.QLabel(self.tab_10)
        self.label_78.setGeometry(QtCore.QRect(20, 350, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")

        self.label_82 = QtWidgets.QLabel(self.tab_10)
        self.label_82.setGeometry(QtCore.QRect(20, 290, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")

        self.label_83 = QtWidgets.QLabel(self.tab_10)
        self.label_83.setGeometry(QtCore.QRect(20, 320, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")

        self.label_61 = QtWidgets.QLabel(self.tab_10)
        self.label_61.setGeometry(QtCore.QRect(20, 260, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")

        self.label_84 = QtWidgets.QLabel(self.tab_10)
        self.label_84.setGeometry(QtCore.QRect(20, 380, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")

        self.label_85 = QtWidgets.QLabel(self.tab_10)
        self.label_85.setGeometry(QtCore.QRect(20, 410, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")

        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_36.setGeometry(QtCore.QRect(220, 170, 51, 20))
        self.lineEdit_36.setObjectName("lineEdit_36")

        self.checkBox = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox.setGeometry(QtCore.QRect(20, 175, 191, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")

        self.frame_35 = QtWidgets.QFrame(self.tab_10)
        self.frame_35.setGeometry(QtCore.QRect(30, 120, 181, 41))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")

        self.radioButton_23 = QtWidgets.QRadioButton(self.frame_35)
        self.radioButton_23.setGeometry(QtCore.QRect(100, 20, 41, 17))
        self.radioButton_23.setToolTipDuration(3000)
        self.radioButton_23.setObjectName("radioButton_23")

        self.radioButton_24 = QtWidgets.QRadioButton(self.frame_35)
        self.radioButton_24.setGeometry(QtCore.QRect(20, 20, 41, 17))
        self.radioButton_24.setToolTipDuration(3000)
        self.radioButton_24.setObjectName("radioButton_24")

        self.label_220 = QtWidgets.QLabel(self.frame_35)
        self.label_220.setGeometry(QtCore.QRect(0, 0, 181, 16))
        self.label_220.setObjectName("label_220")

        self.frame_36 = QtWidgets.QFrame(self.tab_10)
        self.frame_36.setGeometry(QtCore.QRect(30, 200, 241, 41))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")

        self.radioButton_25 = QtWidgets.QRadioButton(self.frame_36)
        self.radioButton_25.setGeometry(QtCore.QRect(100, 20, 41, 17))
        self.radioButton_25.setToolTipDuration(3000)
        self.radioButton_25.setObjectName("radioButton_25")

        self.radioButton_26 = QtWidgets.QRadioButton(self.frame_36)
        self.radioButton_26.setGeometry(QtCore.QRect(20, 20, 41, 17))
        self.radioButton_26.setToolTipDuration(3000)
        self.radioButton_26.setObjectName("radioButton_26")

        self.label_221 = QtWidgets.QLabel(self.frame_36)
        self.label_221.setGeometry(QtCore.QRect(0, 0, 241, 16))
        self.label_221.setObjectName("label_221")

        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_23.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")

        self.tabWidget_3.addTab(self.tab_10, "")

        self.line_4 = QtWidgets.QFrame(self.page)
        self.line_4.setGeometry(QtCore.QRect(356, 10, 20, 511))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.label_75 = QtWidgets.QLabel(self.page)
        self.label_75.setGeometry(QtCore.QRect(386, 0, 61, 20))
        self.label_75.setWordWrap(True)
        self.label_75.setObjectName("label_75")

        self.pushButton_11 = QtWidgets.QPushButton(self.page)
        self.pushButton_11.setGeometry(QtCore.QRect(26, 500, 309, 23))
        self.pushButton_11.setObjectName("pushButton_11")

        self.stackedWidget.addWidget(self.page)

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")

        self.pushButton_305 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_305.setGeometry(QtCore.QRect(6, 514, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_305.setFont(font)
        self.pushButton_305.setObjectName("pushButton_305")

        self.pushButton_307 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_307.setGeometry(QtCore.QRect(416, 512, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_307.setFont(font)
        self.pushButton_307.setObjectName("pushButton_307")

        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(6, 18, 987, 485))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")

        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 968, 483))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")

        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_9.setGeometry(QtCore.QRect(8, 10, 951, 61))
        self.frame_9.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")

        self.comboBox_2 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setCurrentText("")
        self.comboBox_2.setMinimumContentsLength(7)
        self.comboBox_2.setModelColumn(22)
        self.comboBox_2.setObjectName("comboBox_2")

        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setGeometry(QtCore.QRect(50, 15, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")

        self.textEdit = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit.setGeometry(QtCore.QRect(290, 10, 619, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")

        self.btn_print_order_6 = QtWidgets.QPushButton(self.frame_9)
        self.btn_print_order_6.setGeometry(QtCore.QRect(914, 15, 31, 31))
        self.btn_print_order_6.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/x-square.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("x-square.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btn_print_order_6.setIcon(icon)
        self.btn_print_order_6.setObjectName("btn_print_order_6")

        self.pushButton_12 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.pushButton_12.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/caret-up-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setObjectName("pushButton_12")

        self.pushButton_13 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 35, 31, 16))
        self.pushButton_13.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pic/caret-down-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon2)
        self.pushButton_13.setObjectName("pushButton_13")

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.page_2)
        self.tabWidget.addTab(self.tab, "")

        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(15, 20, 36, 21))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(762, 20, 171, 22))
        self.comboBox.setObjectName("comboBox")

        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(666, 22, 96, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")

        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(956, 14, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setToolTipDuration(3000)
        self.pushButton_14.setText("")

        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("pic/floppy.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_14.setIcon(icon3)
        self.pushButton_14.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_14.setObjectName("pushButton_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(4)
        self.tabWidget_3.setCurrentIndex(2)
        self.comboBox_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        self.label_96.setText(_translate("MainWindow", "Количество"))
        self.label_97.setText(_translate("MainWindow", "Наименование изделия"))
        self.label_98.setText(_translate("MainWindow", "Нож КСША 40.00.004"))
        self.label_customer_13.setText(_translate("MainWindow", "1000"))
        self.label_99.setText(_translate("MainWindow", "1000"))
        self.label_100.setText(_translate("MainWindow", "1"))
        self.pushButton_10.setText(_translate("MainWindow", "КД"))
        self.label_101.setText(_translate("MainWindow", "Данные по заданию:"))
        self.label_192.setText(_translate("MainWindow", "Необходимо отметить элементы КД, которые входят в заказ."))
        self.label_209.setText(_translate("MainWindow", " Деталь 3"))
        self.label_customer_32.setText(_translate("MainWindow", "1000"))
        self.label_210.setText(_translate("MainWindow", "1000"))
        self.label_191.setText(_translate("MainWindow", "ДЕТ"))
        self.label_200.setText(_translate("MainWindow", "Сборочная единица"))
        self.label_customer_26.setText(_translate("MainWindow", "1000"))
        self.label_201.setText(_translate("MainWindow", "1000"))
        self.label_93.setText(_translate("MainWindow", "СБ"))
        self.label_206.setText(_translate("MainWindow", "Деталь 2"))
        self.label_customer_30.setText(_translate("MainWindow", "1000"))
        self.label_207.setText(_translate("MainWindow", "1000"))
        self.label_103.setText(_translate("MainWindow", "ДЕТ"))
        self.label_203.setText(_translate("MainWindow", "Деталь 1"))
        self.label_customer_28.setText(_translate("MainWindow", "1000"))
        self.label_204.setText(_translate("MainWindow", "1000"))
        self.label_102.setText(_translate("MainWindow", "ДЕТ"))
        self.label_212.setText(_translate("MainWindow", "Подсборочная единица"))
        self.label_customer_34.setText(_translate("MainWindow", "1000"))
        self.label_213.setText(_translate("MainWindow", "1000"))
        self.label_194.setText(_translate("MainWindow", "СБ"))
        self.label_215.setText(_translate("MainWindow", "Деталь 5"))
        self.label_customer_36.setText(_translate("MainWindow", "1000"))
        self.label_216.setText(_translate("MainWindow", "1000"))
        self.label_195.setText(_translate("MainWindow", "ДЕТ"))
        self.label_218.setText(_translate("MainWindow", "Деталь 4"))
        self.label_customer_38.setText(_translate("MainWindow", "1000"))
        self.label_219.setText(_translate("MainWindow", "1000"))
        self.label_196.setText(_translate("MainWindow", "ДЕТ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_11), _translate("MainWindow", "Привязка КД"))
        self.label_12.setText(_translate("MainWindow", "Кол. в запуск"))
        self.label_74.setToolTip(_translate("MainWindow", "Длина детали"))
        self.label_74.setText(_translate("MainWindow", "Масса детали               кг"))
        self.label_11.setText(_translate("MainWindow", "Наименование детали"))
        self.label_7.setText(_translate("MainWindow", "Нож КСША 40.00.004"))
        self.label_customer_10.setText(_translate("MainWindow", "1000"))
        self.label_5.setText(_translate("MainWindow", "1000"))
        self.label_9.setText(_translate("MainWindow", "Количество"))
        self.label_19.setText(_translate("MainWindow", "d, мм"))
        self.label_20.setToolTip(_translate("MainWindow", "Длина прутка"))
        self.label_20.setText(_translate("MainWindow", "L, мм"))
        self.label_21.setText(_translate("MainWindow", "Пруток"))
        self.pushButton_2.setText(_translate("MainWindow", "Сайт"))
        self.label_35.setText(_translate("MainWindow", "Выбор  материала:"))
        self.label_39.setText(_translate("MainWindow", "ГОСТ на прокат:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Круг"))
        self.label_22.setText(_translate("MainWindow", "Пруток"))
        self.label_23.setText(_translate("MainWindow", "s, мм"))
        self.label_24.setToolTip(_translate("MainWindow", "Длина прутка"))
        self.label_24.setText(_translate("MainWindow", "L, мм"))
        self.label_40.setText(_translate("MainWindow", "ГОСТ на прокат:"))
        self.pushButton_3.setText(_translate("MainWindow", "Сайт"))
        self.label_36.setText(_translate("MainWindow", "Выбор  материала:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "Шестигранник"))
        self.label_25.setText(_translate("MainWindow", "Труба"))
        self.label_26.setText(_translate("MainWindow", "D, мм"))
        self.label_27.setToolTip(_translate("MainWindow", "Длина прутка"))
        self.label_27.setText(_translate("MainWindow", "L, мм"))
        self.label_28.setText(_translate("MainWindow", "d, мм"))
        self.label_41.setText(_translate("MainWindow", "ГОСТ на прокат:"))
        self.pushButton_4.setText(_translate("MainWindow", "Сайт"))
        self.label_37.setText(_translate("MainWindow", "Выбор  материала:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("MainWindow", "Труба"))
        self.label_29.setText(_translate("MainWindow", "Пруток"))
        self.label_30.setText(_translate("MainWindow", "s, мм"))
        self.label_31.setToolTip(_translate("MainWindow", "Длина прутка"))
        self.label_31.setText(_translate("MainWindow", "L, мм"))
        self.label_42.setText(_translate("MainWindow", "ГОСТ на прокат:"))
        self.pushButton_5.setText(_translate("MainWindow", "Сайт"))
        self.label_38.setText(_translate("MainWindow", "Выбор  материала:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "Квадрат"))
        self.label_32.setText(_translate("MainWindow", "Толщина, мм"))
        self.label_33.setText(_translate("MainWindow", "Ширина, мм"))
        self.label_34.setText(_translate("MainWindow", "Длина, мм"))
        self.label_43.setText(_translate("MainWindow", "ГОСТ на прокат:"))
        self.pushButton_6.setText(_translate("MainWindow", "Сайт"))
        self.label_44.setText(_translate("MainWindow", "Выбор  материала:"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "Лист"))
        self.label_15.setText(_translate("MainWindow", "Выбор материала и формы:"))
        self.label_71.setToolTip(_translate("MainWindow", "Припуск на отрезку"))
        self.label_71.setText(_translate("MainWindow", "S отр, мм"))
        self.label_72.setToolTip(_translate("MainWindow", "Размер под зажим"))
        self.label_72.setText(_translate("MainWindow", "l заж, мм"))
        self.label_73.setToolTip(_translate("MainWindow", "Длина детали"))
        self.label_73.setText(_translate("MainWindow", "l дет, мм"))
        self.label_76.setToolTip(_translate("MainWindow", "Ширина реза пилы"))
        self.label_76.setText(_translate("MainWindow", "S отр_пилы, мм"))
        self.label_77.setToolTip(_translate("MainWindow", "Припуск на троцовку"))
        self.label_77.setText(_translate("MainWindow", "S торц, мм"))
        self.label_79.setText(_translate("MainWindow", "Число деталей в прутке = "))
        self.label_80.setText(_translate("MainWindow", "Число целых прутков в заказе = "))
        self.label_81.setText(_translate("MainWindow", "Размер дополнительного прутка = "))
        self.pushButton_7.setText(_translate("MainWindow", "Рассчитать"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "Одиночная"))
        self.label_52.setToolTip(_translate("MainWindow", "Длина детали"))
        self.label_52.setText(_translate("MainWindow", "l дет, мм"))
        self.label_53.setToolTip(_translate("MainWindow", "Ширина реза пилы"))
        self.label_53.setText(_translate("MainWindow", "S отр_пилы, мм"))
        self.label_54.setToolTip(_translate("MainWindow", "Припуск на отрезку"))
        self.label_54.setText(_translate("MainWindow", "S отр, мм"))
        self.label_55.setToolTip(_translate("MainWindow", "Припуск на троцовку"))
        self.label_55.setText(_translate("MainWindow", "S торц, мм"))
        self.label_63.setToolTip(_translate("MainWindow", "Припуск на торцовку комплексной заготовки"))
        self.label_63.setText(_translate("MainWindow", "S торц_кз, мм"))
        self.label_64.setToolTip(_translate("MainWindow", "Размер под зажим"))
        self.label_64.setText(_translate("MainWindow", "l заж, мм"))
        self.lineEdit_39.setText(_translate("MainWindow", "650"))
        self.label_65.setToolTip(_translate("MainWindow", "Максимальная длина комплексной заготовки"))
        self.label_65.setText(_translate("MainWindow", "l кз_max, мм"))
        self.label_51.setText(_translate("MainWindow", "Длина комплексной заготовки = "))
        self.label_66.setText(_translate("MainWindow", "Число деталей в комплексной заготовке = "))
        self.label_67.setText(_translate("MainWindow", "Число комплексных заготовок в прутке = "))
        self.label_68.setText(_translate("MainWindow", "Число деталей в прутке = "))
        self.label_69.setText(_translate("MainWindow", "Число целых прутков в заказе = "))
        self.label_70.setText(_translate("MainWindow", "Размер дополнительного прутка = "))
        self.pushButton.setText(_translate("MainWindow", "Рассчитать"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "Комплексная"))
        self.pushButton_8.setText(_translate("MainWindow", "Рассчитать"))
        self.label_57.setToolTip(_translate("MainWindow", "Суммарный припуск по длине"))
        self.label_57.setText(_translate("MainWindow", "S1+S2, мм"))
        self.label_58.setToolTip(_translate("MainWindow", "Длина детали"))
        self.label_58.setText(_translate("MainWindow", "a_дет, мм"))
        self.label_59.setToolTip(_translate("MainWindow", "Ширина детали"))
        self.label_59.setText(_translate("MainWindow", "b_дет, мм"))
        self.label_60.setToolTip(_translate("MainWindow", "Суммарный припуск по ширине"))
        self.label_60.setText(_translate("MainWindow", "h1+h2, мм"))
        self.label_78.setText(_translate("MainWindow", "Число целых листов = "))
        self.label_82.setText(_translate("MainWindow", "Число полос = "))
        self.label_83.setText(_translate("MainWindow", "Число заготовок в листе = "))
        self.label_61.setText(_translate("MainWindow", "Число заготовок в полосе = "))
        self.label_84.setText(_translate("MainWindow", "Ширина дополнительного листа = "))
        self.label_85.setText(_translate("MainWindow", "Длина дополнительного листа = "))
        self.checkBox.setText(_translate("MainWindow", "Длина полосы доп листа, мм"))
        self.radioButton_23.setToolTip(_translate("MainWindow", "ДЛИНА-ширина"))
        self.radioButton_23.setText(_translate("MainWindow", "Ab"))
        self.radioButton_24.setToolTip(_translate("MainWindow", "ДЛИНА-длина"))
        self.radioButton_24.setText(_translate("MainWindow", "Aa"))
        self.label_220.setText(_translate("MainWindow", "Ориентация заготовки в полосах:"))
        self.radioButton_25.setToolTip(_translate("MainWindow", "ДЛИНА-ширина"))
        self.radioButton_25.setText(_translate("MainWindow", "Ab"))
        self.radioButton_26.setToolTip(_translate("MainWindow", "ДЛИНА-длина"))
        self.radioButton_26.setText(_translate("MainWindow", "Aa"))
        self.label_221.setText(_translate("MainWindow", "Ориентация заготовки в полосах доп. листа:"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "Листовая"))
        self.label_75.setText(_translate("MainWindow", "Заготовка:"))
        self.pushButton_11.setText(_translate("MainWindow", "Разработать технологический паспорт"))
        self.pushButton_305.setText(_translate("MainWindow", "Назад"))
        self.pushButton_307.setText(_translate("MainWindow", "+"))
        self.label_18.setText(_translate("MainWindow", "1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Деталь №1"))
        self.label_13.setText(_translate("MainWindow", "Разработчик:"))
        self.pushButton_14.setToolTip(_translate("MainWindow", "Сохранить документ"))
