from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OrderDev(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1018, 721)
        MainWindow.setWindowTitle("Разработка задания")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(60, 20, 586, 20))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")

        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(40, 1, 10, 18))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")

        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(150, 1, 18, 18))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")

        self.label_text_date_of_task = QtWidgets.QLabel(self.centralwidget)
        self.label_text_date_of_task.setGeometry(QtCore.QRect(60, 0, 51, 16))
        self.label_text_date_of_task.setObjectName("label_3")
        self.label_text_date_of_task.setText("№ счёта")

        self.label_check_number = QtWidgets.QLabel(self.frame)
        self.label_check_number.setGeometry(QtCore.QRect(10, 2, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_check_number.setFont(font)
        self.label_check_number.setObjectName("label_4")
        self.label_check_number.setText("142")

        self.label_customer = QtWidgets.QLabel(self.frame)
        self.label_customer.setGeometry(QtCore.QRect(165, 2, 311, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer.setFont(font)
        self.label_customer.setObjectName("label_customer")
        self.label_customer.setText("ООО \"Белагро Бел\"")

        self.label_date_of_task = QtWidgets.QLabel(self.frame)
        self.label_date_of_task.setGeometry(QtCore.QRect(60, 2, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_date_of_task.setFont(font)
        self.label_date_of_task.setObjectName("date_of_task")
        self.label_date_of_task.setText("26.07.2024")

        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(140, 0, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_6.setText("Дата")

        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(290, 0, 171, 16))
        self.label_10.setObjectName("label_10")
        self.label_10.setText("Название организации заказчика")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(5, 55, 1006, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.frame_6 = QtWidgets.QFrame(self.tab_11)
        self.frame_6.setGeometry(QtCore.QRect(5, 20, 373, 51))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.label_96 = QtWidgets.QLabel(self.frame_6)
        self.label_96.setGeometry(QtCore.QRect(268, 0, 61, 16))
        self.label_96.setObjectName("label_96")
        self.label_96.setText("Количество")

        self.label_97 = QtWidgets.QLabel(self.frame_6)
        self.label_97.setGeometry(QtCore.QRect(38, 0, 121, 16))
        self.label_97.setObjectName("label_97")
        self.label_97.setText("Наименование изделия")

        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setGeometry(QtCore.QRect(28, 20, 301, 20))
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_7.setLineWidth(2)
        self.frame_7.setMidLineWidth(1)
        self.frame_7.setObjectName("frame_7")
        self.label_98 = QtWidgets.QLabel(self.frame_7)
        self.label_98.setGeometry(QtCore.QRect(10, 2, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_98.setFont(font)
        self.label_98.setObjectName("label_98")
        self.label_98.setText("Нож КСША 40.00.004")

        self.label_customer_13 = QtWidgets.QLabel(self.frame_7)
        self.label_customer_13.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_13.setFont(font)
        self.label_customer_13.setObjectName("label_customer_13")
        self.label_customer_13.setText("1000")

        self.line_10 = QtWidgets.QFrame(self.frame_7)
        self.line_10.setGeometry(QtCore.QRect(240, 1, 18, 18))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")

        self.label_99 = QtWidgets.QLabel(self.frame_7)
        self.label_99.setGeometry(QtCore.QRect(250, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_99.setFont(font)
        self.label_99.setObjectName("label_99")
        self.label_99.setText("1000")

        self.label_100 = QtWidgets.QLabel(self.frame_6)
        self.label_100.setGeometry(QtCore.QRect(6, 22, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_100.setFont(font)
        self.label_100.setObjectName("label_100")
        self.label_100.setText("1")

        self.pushButton_10 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_10.setGeometry(QtCore.QRect(336, 19, 26, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setText("КД")

        self.label_101 = QtWidgets.QLabel(self.tab_11)
        self.label_101.setGeometry(QtCore.QRect(20, 0, 106, 16))
        self.label_101.setObjectName("label_101")
        self.label_101.setText("Данные по заданию:")

        self.label_192 = QtWidgets.QLabel(self.tab_11)
        self.label_192.setGeometry(QtCore.QRect(514, 0, 323, 16))
        self.label_192.setObjectName("label_192")
        self.label_192.setText("Необходимо отметить элементы КД, которые входят в заказ.")

        self.scrollArea = QtWidgets.QScrollArea(self.tab_11)
        self.scrollArea.setGeometry(QtCore.QRect(385, 21, 611, 585))
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 592, 583))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        # Additional frames and labels can be added here following the same pattern

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.frame_5 = QtWidgets.QFrame(self.tab_11)
        self.frame_5.setGeometry(QtCore.QRect(610, 10, 381, 21))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.tabWidget.addTab(self.tab_11, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(500, 0, 71, 16))
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.label_12.setText("Кол. в запуск")

        self.line_6 = QtWidgets.QFrame(self.tab)
        self.line_6.setGeometry(QtCore.QRect(10, 44, 981, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")

        self.label_74 = QtWidgets.QLabel(self.tab)
        self.label_74.setGeometry(QtCore.QRect(832, 14, 156, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_74.setFont(font)
        self.label_74.setToolTipDuration(3000)
        self.label_74.setObjectName("label_74")
        self.label_74.setText("Масса детали               кг")

        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(160, 0, 121, 16))
        self.label_11.setObjectName("label_11")
        self.label_11.setText("Наименование детали")

        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(20, 20, 461, 20))
        self.frame_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setLineWidth(2)
        self.frame_3.setMidLineWidth(1)
        self.frame_3.setObjectName("frame_3")
        self.label_7 = QtWidgets.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(10, 2, 411, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_7.setText("Нож КСША 40.00.004")

        self.label_customer_10 = QtWidgets.QLabel(self.frame_3)
        self.label_customer_10.setGeometry(QtCore.QRect(950, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_customer_10.setFont(font)
        self.label_customer_10.setObjectName("label_customer_10")
        self.label_customer_10.setText("1000")

        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(410, 2, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_5.setText("1000")

        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(410, 0, 61, 16))
        self.label_9.setObjectName("label_9")
        self.label_9.setText("Количество")

        self.lineEdit_96 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_96.setGeometry(QtCore.QRect(500, 20, 71, 20))
        self.lineEdit_96.setText("")
        self.lineEdit_96.setObjectName("lineEdit_96")

        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(660, 40, 321, 21))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")

        self.stackedWidget = QtWidgets.QStackedWidget(self.tab)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 62, 993, 551))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.page)
        self.tabWidget_2.setGeometry(QtCore.QRect(4, 22, 351, 443))
        self.tabWidget_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(164, 0, 183, 213))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("pic/circle.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 73, 101, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(10, 78, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_19.setText("d, мм")

        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 103, 101, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(10, 108, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setToolTipDuration(3000)
        self.label_20.setObjectName("label_20")
        self.label_20.setText("L, мм")

        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(70, 53, 41, 16))
        self.label_21.setObjectName("label_21")
        self.label_21.setText("Пруток")

        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 302, 31, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setText("Сайт")

        self.label_35 = QtWidgets.QLabel(self.tab_3)
        self.label_35.setGeometry(QtCore.QRect(10, 282, 101, 16))
        self.label_35.setObjectName("label_35")
        self.label_35.setText("Выбор  материала:")

        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 302, 281, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_39 = QtWidgets.QLabel(self.tab_3)
        self.label_39.setGeometry(QtCore.QRect(10, 332, 91, 16))
        self.label_39.setObjectName("label_39")
        self.label_39.setText("ГОСТ на прокат:")

        self.tabWidget_2.addTab(self.tab_3, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_8 = QtWidgets.QLabel(self.tab_7)
        self.label_8.setGeometry(QtCore.QRect(170, 0, 179, 227))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("pic/hexagon.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.label_22 = QtWidgets.QLabel(self.tab_7)
        self.label_22.setGeometry(QtCore.QRect(78, 88, 41, 16))
        self.label_22.setObjectName("label_22")
        self.label_22.setText("Пруток")

        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_4.setGeometry(QtCore.QRect(58, 108, 101, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_23 = QtWidgets.QLabel(self.tab_7)
        self.label_23.setGeometry(QtCore.QRect(18, 113, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_23.setText("s, мм")

        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_5.setGeometry(QtCore.QRect(58, 138, 101, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_40 = QtWidgets.QLabel(self.tab_7)
        self.label_40.setGeometry(QtCore.QRect(10, 326, 91, 16))
        self.label_40.setObjectName("label_40")
        self.label_40.setText("ГОСТ на прокат:")

        self.pushButton_3 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_3.setGeometry(QtCore.QRect(300, 296, 31, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setText("Сайт")

        self.label_36 = QtWidgets.QLabel(self.tab_7)
        self.label_36.setGeometry(QtCore.QRect(10, 276, 101, 16))
        self.label_36.setObjectName("label_36")
        self.label_36.setText("Выбор  материала:")

        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_16 = QtWidgets.QLabel(self.tab_4)
        self.label_16.setGeometry(QtCore.QRect(176, 0, 171, 233))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("pic/pipe.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.label_25 = QtWidgets.QLabel(self.tab_4)
        self.label_25.setGeometry(QtCore.QRect(70, 38, 41, 16))
        self.label_25.setObjectName("label_25")
        self.label_25.setText("Труба")

        self.label_26 = QtWidgets.QLabel(self.tab_4)
        self.label_26.setGeometry(QtCore.QRect(10, 63, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_26.setText("D, мм")

        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(10, 123, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setToolTipDuration(3000)
        self.label_27.setObjectName("label_27")
        self.label_27.setText("L, мм")

        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(50, 58, 101, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")

        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(50, 118, 101, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")

        self.pushButton_4 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_4.setGeometry(QtCore.QRect(300, 300, 31, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setText("Сайт")

        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(10, 330, 91, 16))
        self.label_41.setObjectName("label_41")
        self.label_41.setText("ГОСТ на прокат:")

        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(192, 0, 155, 197))
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("pic/square.png"))
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(74, 49, 41, 16))
        self.label_29.setObjectName("label_29")
        self.label_29.setText("Пруток")

        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_9.setGeometry(QtCore.QRect(54, 99, 101, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")

        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_10.setGeometry(QtCore.QRect(54, 69, 101, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")

        self.label_30 = QtWidgets.QLabel(self.tab_5)
        self.label_30.setGeometry(QtCore.QRect(14, 74, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_30.setText("s, мм")

        self.label_31 = QtWidgets.QLabel(self.tab_5)
        self.label_31.setGeometry(QtCore.QRect(14, 104, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_31.setToolTipDuration(3000)
        self.label_31.setText("L, мм")

        self.label_42 = QtWidgets.QLabel(self.tab_5)
        self.label_42.setGeometry(QtCore.QRect(10, 288, 91, 16))
        self.label_42.setObjectName("label_42")
        self.label_42.setText("ГОСТ на прокат:")

        self.pushButton_5 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_5.setGeometry(QtCore.QRect(300, 258, 31, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setText("Сайт")

        self.label_38 = QtWidgets.QLabel(self.tab_5)
        self.label_38.setGeometry(QtCore.QRect(10, 238, 101, 16))
        self.label_38.setObjectName("label_38")
        self.label_38.setText("Выбор  материала:")

        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(16, 91, 71, 16))
        self.label_32.setToolTip("")
        self.label_32.setToolTipDuration(-1)
        self.label_32.setObjectName("label_32")
        self.label_32.setText("Толщина, мм")

        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(86, 86, 51, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")

        self.label_33 = QtWidgets.QLabel(self.tab_6)
        self.label_33.setGeometry(QtCore.QRect(16, 121, 61, 16))
        self.label_33.setToolTip("")
        self.label_33.setToolTipDuration(-1)
        self.label_33.setObjectName("label_33")
        self.label_33.setText("Ширина, мм")

        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(86, 116, 91, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")

        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_13.setGeometry(QtCore.QRect(86, 146, 91, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")

        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(16, 151, 61, 16))
        self.label_34.setToolTip("")
        self.label_34.setToolTipDuration(-1)
        self.label_34.setObjectName("label_34")
        self.label_34.setText("Длина, мм")

        self.label_43 = QtWidgets.QLabel(self.tab_6)
        self.label_43.setGeometry(QtCore.QRect(10, 304, 91, 16))
        self.label_43.setObjectName("label_43")
        self.label_43.setText("ГОСТ на прокат:")

        self.pushButton_6 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_6.setGeometry(QtCore.QRect(300, 274, 31, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setText("Сайт")

        self.label_44 = QtWidgets.QLabel(self.tab_6)
        self.label_44.setGeometry(QtCore.QRect(10, 254, 101, 16))
        self.label_44.setObjectName("label_44")
        self.label_44.setText("Выбор  материала:")

        self.tabWidget_2.addTab(self.tab_6, "")
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(18, 0, 141, 20))
        self.label_15.setWordWrap(True)
        self.label_15.setObjectName("label_15")
        self.label_15.setText("Выбор материала и формы:")

        self.tabWidget_3 = QtWidgets.QTabWidget(self.page)
        self.tabWidget_3.setGeometry(QtCore.QRect(376, 20, 613, 501))
        self.tabWidget_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.label_14 = QtWidgets.QLabel(self.tab_8)
        self.label_14.setGeometry(QtCore.QRect(80, 0, 521, 211))
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("pic/single_proc_2.png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_40.setGeometry(QtCore.QRect(110, 245, 51, 20))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.label_71 = QtWidgets.QLabel(self.tab_8)
        self.label_71.setGeometry(QtCore.QRect(10, 280, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_71.setFont(font)
        self.label_71.setToolTipDuration(3000)
        self.label_71.setObjectName("label_71")
        self.label_71.setText("Число деталей в прутке = ")

        self.label_72 = QtWidgets.QLabel(self.tab_8)
        self.label_72.setGeometry(QtCore.QRect(10, 340, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_72.setFont(font)
        self.label_72.setToolTipDuration(3000)
        self.label_72.setObjectName("label_72")
        self.label_72.setText("Число целых прутков в заказе = ")

        self.label_73 = QtWidgets.QLabel(self.tab_8)
        self.label_73.setGeometry(QtCore.QRect(10, 220, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_73.setFont(font)
        self.label_73.setToolTipDuration(3000)
        self.label_73.setObjectName("label_73")
        self.label_73.setText("Размер дополнительного прутка = ")

        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_43.setGeometry(QtCore.QRect(110, 215, 51, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")

        self.lineEdit_44 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_44.setGeometry(QtCore.QRect(110, 335, 51, 20))
        self.lineEdit_44.setObjectName("lineEdit_44")

        self.label_76 = QtWidgets.QLabel(self.tab_8)
        self.label_76.setGeometry(QtCore.QRect(10, 250, 98, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_76.setFont(font)
        self.label_76.setToolTipDuration(3000)
        self.label_76.setObjectName("label_76")
        self.label_76.setText("Число деталей в прутке = ")

        self.label_77 = QtWidgets.QLabel(self.tab_8)
        self.label_77.setGeometry(QtCore.QRect(10, 310, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_77.setFont(font)
        self.label_77.setToolTipDuration(3000)
        self.label_77.setObjectName("label_77")
        self.label_77.setText("Число целых прутков в заказе = ")

        self.lineEdit_45 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_45.setGeometry(QtCore.QRect(110, 305, 51, 20))
        self.lineEdit_45.setObjectName("lineEdit_45")

        self.lineEdit_46 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_46.setGeometry(QtCore.QRect(110, 275, 51, 20))
        self.lineEdit_46.setObjectName("lineEdit_46")

        self.label_79 = QtWidgets.QLabel(self.tab_8)
        self.label_79.setGeometry(QtCore.QRect(200, 220, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.label_79.setText("Число деталей в прутке = ")

        self.label_80 = QtWidgets.QLabel(self.tab_8)
        self.label_80.setGeometry(QtCore.QRect(200, 250, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_80.setFont(font)
        self.label_80.setObjectName("label_80")
        self.label_80.setText("Число целых прутков в заказе = ")

        self.label_81 = QtWidgets.QLabel(self.tab_8)
        self.label_81.setGeometry(QtCore.QRect(200, 280, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_81.setFont(font)
        self.label_81.setObjectName("label_81")
        self.label_81.setText("Размер дополнительного прутка = ")

        self.line_8 = QtWidgets.QFrame(self.tab_8)
        self.line_8.setGeometry(QtCore.QRect(170, 210, 20, 201))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")

        self.pushButton_7 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_7.setGeometry(QtCore.QRect(510, 435, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setText("Рассчитать")

        self.checkBox_22 = QtWidgets.QCheckBox(self.tab_8)
        self.checkBox_22.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_22.setText("")
        self.checkBox_22.setObjectName("checkBox_22")
        self.tabWidget_3.addTab(self.tab_8, "")

        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_50 = QtWidgets.QLabel(self.tab_9)
        self.label_50.setGeometry(QtCore.QRect(30, 0, 571, 211))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap("pic/complex_proc.png"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_28.setGeometry(QtCore.QRect(110, 210, 51, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.label_52 = QtWidgets.QLabel(self.tab_9)
        self.label_52.setGeometry(QtCore.QRect(10, 215, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_52.setFont(font)
        self.label_52.setToolTipDuration(3000)
        self.label_52.setObjectName("label_52")
        self.label_52.setText("l дет, мм")

        self.label_53 = QtWidgets.QLabel(self.tab_9)
        self.label_53.setGeometry(QtCore.QRect(10, 245, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setToolTipDuration(3000)
        self.label_53.setObjectName("label_53")
        self.label_53.setText("Ширина реза пилы")

        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_29.setGeometry(QtCore.QRect(110, 240, 51, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")

        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_30.setGeometry(QtCore.QRect(110, 270, 51, 20))
        self.lineEdit_30.setObjectName("lineEdit_30")

        self.label_54 = QtWidgets.QLabel(self.tab_9)
        self.label_54.setGeometry(QtCore.QRect(10, 275, 91, 16))
        self.label_54.setObjectName("label_54")
        self.label_54.setText("Припуск на отрезку")

        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_31.setGeometry(QtCore.QRect(110, 300, 51, 20))
        self.lineEdit_31.setObjectName("lineEdit_31")

        self.label_55 = QtWidgets.QLabel(self.tab_9)
        self.label_55.setGeometry(QtCore.QRect(10, 305, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setToolTipDuration(3000)
        self.label_55.setObjectName("label_55")
        self.label_55.setText("Припуск на троцовку")

        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_37.setGeometry(QtCore.QRect(110, 330, 51, 20))
        self.lineEdit_37.setObjectName("lineEdit_37")

        self.label_63 = QtWidgets.QLabel(self.tab_9)
        self.label_63.setGeometry(QtCore.QRect(10, 335, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_63.setFont(font)
        self.label_63.setToolTipDuration(3000)
        self.label_63.setObjectName("label_63")
        self.label_63.setText("Припуск на торцовку")

        self.label_64 = QtWidgets.QLabel(self.tab_9)
        self.label_64.setGeometry(QtCore.QRect(10, 365, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_64.setFont(font)
        self.label_64.setToolTipDuration(3000)
        self.label_64.setObjectName("label_64")
        self.label_64.setText("Размер под зажим")

        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_38.setGeometry(QtCore.QRect(110, 360, 51, 20))
        self.lineEdit_38.setObjectName("lineEdit_38")

        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_39.setGeometry(QtCore.QRect(110, 390, 51, 20))
        self.lineEdit_39.setObjectName("lineEdit_39")

        self.label_65 = QtWidgets.QLabel(self.tab_9)
        self.label_65.setGeometry(QtCore.QRect(10, 395, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.label_65.setFont(font)
        self.label_65.setToolTipDuration(3000)
        self.label_65.setObjectName("label_65")
        self.label_65.setText("l кз_max, мм")

        self.label_51 = QtWidgets.QLabel(self.tab_9)
        self.label_51.setGeometry(QtCore.QRect(200, 220, 251, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_51.setText("Длина комплексной заготовки = ")

        self.label_66 = QtWidgets.QLabel(self.tab_9)
        self.label_66.setGeometry(QtCore.QRect(200, 250, 321, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.label_66.setText("Число деталей в комплексной заготовке = ")

        self.label_67 = QtWidgets.QLabel(self.tab_9)
        self.label_67.setGeometry(QtCore.QRect(200, 280, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.label_67.setText("Число комплексных заготовок в прутке = ")

        self.label_68 = QtWidgets.QLabel(self.tab_9)
        self.label_68.setGeometry(QtCore.QRect(200, 310, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_68.setFont(font)
        self.label_68.setObjectName("label_68")
        self.label_68.setText("Число деталей в прутке = ")

        self.label_69 = QtWidgets.QLabel(self.tab_9)
        self.label_69.setGeometry(QtCore.QRect(200, 340, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_69.setText("Число целых прутков в заказе = ")

        self.label_70 = QtWidgets.QLabel(self.tab_9)
        self.label_70.setGeometry(QtCore.QRect(200, 370, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_70.setFont(font)
        self.label_70.setObjectName("label_70")
        self.label_70.setText("Размер дополнительного прутка = ")

        self.pushButton = QtWidgets.QPushButton(self.tab_9)
        self.pushButton.setGeometry(QtCore.QRect(510, 435, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("Рассчитать")

        self.checkBox_21 = QtWidgets.QCheckBox(self.tab_9)
        self.checkBox_21.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_21.setText("")
        self.checkBox_21.setObjectName("checkBox_21")
        self.tabWidget_3.addTab(self.tab_9, "")

        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_56 = QtWidgets.QLabel(self.tab_10)
        self.label_56.setGeometry(QtCore.QRect(270, 0, 331, 231))
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("pic/sheet_2.png"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_8.setGeometry(QtCore.QRect(510, 435, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setText("Рассчитать")

        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_32.setGeometry(QtCore.QRect(140, 40, 51, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.label_57 = QtWidgets.QLabel(self.tab_10)
        self.label_57.setGeometry(QtCore.QRect(40, 75, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setToolTipDuration(3000)
        self.label_57.setObjectName("label_57")
        self.label_57.setText("S1+S2, мм")

        self.label_58 = QtWidgets.QLabel(self.tab_10)
        self.label_58.setGeometry(QtCore.QRect(40, 15, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setToolTipDuration(3000)
        self.label_58.setObjectName("label_58")
        self.label_58.setText("Длина детали")

        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_33.setGeometry(QtCore.QRect(140, 10, 51, 20))
        self.lineEdit_33.setObjectName("lineEdit_33")

        self.label_59 = QtWidgets.QLabel(self.tab_10)
        self.label_59.setGeometry(QtCore.QRect(40, 45, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_59.setFont(font)
        self.label_59.setToolTipDuration(3000)
        self.label_59.setObjectName("label_59")
        self.label_59.setText("Ширина детали")

        self.label_60 = QtWidgets.QLabel(self.tab_10)
        self.label_60.setGeometry(QtCore.QRect(40, 105, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_60.setFont(font)
        self.label_60.setToolTipDuration(3000)
        self.label_60.setObjectName("label_60")
        self.label_60.setText("Суммарный припуск по ширине")

        self.lineEdit_34 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_34.setGeometry(QtCore.QRect(140, 100, 51, 20))
        self.lineEdit_34.setObjectName("lineEdit_34")

        self.lineEdit_35 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_35.setGeometry(QtCore.QRect(140, 70, 51, 20))
        self.lineEdit_35.setObjectName("lineEdit_35")

        self.line_9 = QtWidgets.QFrame(self.tab_10)
        self.line_9.setGeometry(QtCore.QRect(10, 240, 581, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")

        self.label_78 = QtWidgets.QLabel(self.tab_10)
        self.label_78.setGeometry(QtCore.QRect(20, 350, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_78.setFont(font)
        self.label_78.setObjectName("label_78")
        self.label_78.setText("Число целых листов = ")

        self.label_82 = QtWidgets.QLabel(self.tab_10)
        self.label_82.setGeometry(QtCore.QRect(20, 290, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.label_82.setText("Число полос = ")

        self.label_83 = QtWidgets.QLabel(self.tab_10)
        self.label_83.setGeometry(QtCore.QRect(20, 320, 201, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_83.setFont(font)
        self.label_83.setObjectName("label_83")
        self.label_83.setText("Число заготовок в листе = ")

        self.label_61 = QtWidgets.QLabel(self.tab_10)
        self.label_61.setGeometry(QtCore.QRect(20, 260, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_61.setText("Число заготовок в полосе = ")

        self.label_84 = QtWidgets.QLabel(self.tab_10)
        self.label_84.setGeometry(QtCore.QRect(20, 380, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.label_84.setText("Ширина дополнительного листа = ")

        self.label_85 = QtWidgets.QLabel(self.tab_10)
        self.label_85.setGeometry(QtCore.QRect(20, 410, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_85.setFont(font)
        self.label_85.setObjectName("label_85")
        self.label_85.setText("Длина дополнительного листа = ")

        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_36.setGeometry(QtCore.QRect(220, 170, 51, 20))
        self.lineEdit_36.setObjectName("lineEdit_36")

        self.checkBox = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox.setGeometry(QtCore.QRect(20, 175, 191, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox.setText("Длина полосы доп листа, мм")

        self.frame_35 = QtWidgets.QFrame(self.tab_10)
        self.frame_35.setGeometry(QtCore.QRect(30, 120, 181, 41))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.radioButton_23 = QtWidgets.QRadioButton(self.frame_35)
        self.radioButton_23.setGeometry(QtCore.QRect(100, 20, 41, 17))
        self.radioButton_23.setToolTipDuration(3000)
        self.radioButton_23.setObjectName("radioButton_23")
        self.radioButton_23.setText("Ab")

        self.radioButton_24 = QtWidgets.QRadioButton(self.frame_35)
        self.radioButton_24.setGeometry(QtCore.QRect(20, 20, 41, 17))
        self.radioButton_24.setToolTipDuration(3000)
        self.radioButton_24.setObjectName("radioButton_24")
        self.radioButton_24.setText("Aa")

        self.label_220 = QtWidgets.QLabel(self.frame_35)
        self.label_220.setGeometry(QtCore.QRect(0, 0, 181, 16))
        self.label_220.setObjectName("label_220")
        self.label_220.setText("Ориентация заготовки в полосах:")

        self.frame_36 = QtWidgets.QFrame(self.tab_10)
        self.frame_36.setGeometry(QtCore.QRect(30, 200, 241, 41))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.radioButton_25 = QtWidgets.QRadioButton(self.frame_36)
        self.radioButton_25.setGeometry(QtCore.QRect(100, 20, 41, 17))
        self.radioButton_25.setToolTipDuration(3000)
        self.radioButton_25.setObjectName("radioButton_25")
        self.radioButton_25.setText("Ab")

        self.radioButton_26 = QtWidgets.QRadioButton(self.frame_36)
        self.radioButton_26.setGeometry(QtCore.QRect(20, 20, 41, 17))
        self.radioButton_26.setToolTipDuration(3000)
        self.radioButton_26.setObjectName("radioButton_26")
        self.radioButton_26.setText("Aa")

        self.label_221 = QtWidgets.QLabel(self.frame_36)
        self.label_221.setGeometry(QtCore.QRect(0, 0, 241, 16))
        self.label_221.setObjectName("label_221")
        self.label_221.setText("Ориентация заготовки в полосах доп. листа:")

        self.checkBox_23 = QtWidgets.QCheckBox(self.tab_10)
        self.checkBox_23.setGeometry(QtCore.QRect(8, 8, 16, 17))
        self.checkBox_23.setText("")
        self.checkBox_23.setObjectName("checkBox_23")
        self.tabWidget_3.addTab(self.tab_10, "")

        self.line_4 = QtWidgets.QFrame(self.page)
        self.line_4.setGeometry(QtCore.QRect(356, 10, 20, 511))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_75 = QtWidgets.QLabel(self.page)
        self.label_75.setGeometry(QtCore.QRect(386, 0, 61, 20))
        self.label_75.setWordWrap(True)
        self.label_75.setObjectName("label_75")
        self.label_75.setText("Заготовка:")

        self.pushButton_11 = QtWidgets.QPushButton(self.page)
        self.pushButton_11.setGeometry(QtCore.QRect(26, 500, 309, 23))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.setText("Разработать технологический паспорт")

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_305 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_305.setGeometry(QtCore.QRect(6, 514, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_305.setFont(font)
        self.pushButton_305.setObjectName("pushButton_305")
        self.pushButton_305.setText("Назад")
        self.pushButton_305 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_305.setGeometry(QtCore.QRect(6, 514, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_305.setFont(font)
        self.pushButton_305.setObjectName("pushButton_305")
        self.pushButton_305.setText("Назад")

        self.pushButton_307 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_307.setGeometry(QtCore.QRect(416, 512, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_307.setFont(font)
        self.pushButton_307.setObjectName("pushButton_307")
        self.pushButton_307.setText("+")

        self.scrollArea_2 = QtWidgets.QScrollArea(self.page_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(6, 18, 987, 485))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 968, 483))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_9.setGeometry(QtCore.QRect(8, 10, 951, 61))
        self.frame_9.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 10, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setCurrentText("")
        self.comboBox_2.setMinimumContentsLength(7)
        self.comboBox_2.setModelColumn(22)
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setGeometry(QtCore.QRect(50, 15, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.label_18.setText("1")

        self.textEdit = QtWidgets.QTextEdit(self.frame_9)
        self.textEdit.setGeometry(QtCore.QRect(290, 10, 619, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.btn_print_order_6 = QtWidgets.QPushButton(self.frame_9)
        self.btn_print_order_6.setGeometry(QtCore.QRect(914, 15, 31, 31))
        self.btn_print_order_6.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/x-square.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("x-square.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.btn_print_order_6.setIcon(icon)
        self.btn_print_order_6.setObjectName("btn_print_order_6")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 10, 31, 16))
        self.pushButton_12.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/caret-up-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 35, 31, 16))
        self.pushButton_13.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/caret-down-fill.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_13.setIcon(icon2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.page_2)
        self.tabWidget.addTab(self.tab, "")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(15, 20, 36, 21))
        self.pushButton_9.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(762, 20, 171, 22))
        self.comboBox.setObjectName("comboBox")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(666, 22, 96, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_13.setText("Разработчик:")

        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(956, 14, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setToolTipDuration(3000)
        self.pushButton_14.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/floppy.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton_14.setIcon(icon3)
        self.pushButton_14.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_14.setObjectName("pushButton_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        # self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(4)
        self.tabWidget_3.setCurrentIndex(2)
        self.comboBox_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)