# Generated by Django 5.1.4 on 2024-12-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_number', models.IntegerField()),
                ('change_date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
    ]
