from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc

class Ui_DesignDocumentFillingForm(object):
    def setupUi(self, DesignDocumentFillingForm):
        DesignDocumentFillingForm.setObjectName("DesignDocumentFillingForm")
        DesignDocumentFillingForm.resize(1027, 791)

        self.centralwidget = QtWidgets.QWidget(DesignDocumentFillingForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")

        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_2.setObjectName("widget_2")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.lineEditProductName = QtWidgets.QLineEdit(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditProductName.setFont(font)
        self.lineEditProductName.setObjectName("lineEditProductName")
        self.horizontalLayout.addWidget(self.lineEditProductName)

        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.BtnUnit = QtWidgets.QPushButton(self.widget_2)
        self.BtnUnit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/utils/icons/plus-square-dotted.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnUnit.setIcon(icon)
        self.BtnUnit.setObjectName("BtnUnit")
        self.horizontalLayout.addWidget(self.BtnUnit)

        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)

        self.BtnAddDetail = QtWidgets.QPushButton(self.widget_2)
        self.BtnAddDetail.setText("")
        self.BtnAddDetail.setIcon(icon)
        self.BtnAddDetail.setObjectName("BtnAddDetail")
        self.horizontalLayout.addWidget(self.BtnAddDetail)

        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.widget_2)

        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")

        self.tabWidget = QtWidgets.QTabWidget(self.widget_3)
        self.tabWidget.setObjectName("tabWidget")

        self.tab_unit = QtWidgets.QWidget()
        self.tab_unit.setObjectName("tab_unit")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_unit)
        self.gridLayout_9.setObjectName("gridLayout_9")

        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)

        self.tabWidget.addTab(self.tab_unit, "")
        self.tab_detail = QtWidgets.QWidget()
        self.tab_detail.setObjectName("tab_detail")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_detail)
        self.gridLayout_7.setObjectName("gridLayout_7")

        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelBelongingToAnAssemblyUnit_2 = QtWidgets.QLabel(self.tab_detail)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelBelongingToAnAssemblyUnit_2.setFont(font)
        self.labelBelongingToAnAssemblyUnit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBelongingToAnAssemblyUnit_2.setWordWrap(True)
        self.labelBelongingToAnAssemblyUnit_2.setObjectName("labelBelongingToAnAssemblyUnit_2")
        self.gridLayout_6.addWidget(self.labelBelongingToAnAssemblyUnit_2, 1, 0, 1, 1)
        self.radioButtonUnit_1_2 = QtWidgets.QRadioButton(self.tab_detail)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonUnit_1_2.setFont(font)
        self.radioButtonUnit_1_2.setObjectName("radioButtonUnit_1_2")
        self.gridLayout_6.addWidget(self.radioButtonUnit_1_2, 3, 0, 1, 1)
        self.lineEditDetailName = QtWidgets.QLineEdit(self.tab_detail)
        self.lineEditDetailName.setObjectName("lineEditDetailName")
        self.gridLayout_6.addWidget(self.lineEditDetailName, 1, 3, 1, 1)
        self.radioButtonUnit_2_2 = QtWidgets.QRadioButton(self.tab_detail)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonUnit_2_2.setFont(font)
        self.radioButtonUnit_2_2.setObjectName("radioButtonUnit_2_2")
        self.gridLayout_6.addWidget(self.radioButtonUnit_2_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem, 4, 0, 1, 1)
        self.BtnOpenDesignFile_2 = QtWidgets.QPushButton(self.tab_detail)
        self.BtnOpenDesignFile_2.setToolTipDuration(3000)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/utils/icons/folder2-open.svg"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.BtnOpenDesignFile_2.setIcon(icon1)
        self.BtnOpenDesignFile_2.setIconSize(QtCore.QSize(20, 20))
        self.BtnOpenDesignFile_2.setObjectName("BtnOpenDesignFile_2")
        self.gridLayout_6.addWidget(self.BtnOpenDesignFile_2, 1, 2, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_detail)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tab.sizePolicy().hasHeightForWidth())
        self.tab.setSizePolicy(sizePolicy)
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_11.setContentsMargins(9, -1, -1, -1)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.BtnAddSheet_2 = QtWidgets.QPushButton(self.tab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/utils/icons/plus-square-dotted.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnAddSheet_2.setIcon(icon2)
        self.BtnAddSheet_2.setObjectName("BtnAddSheet_2")
        self.gridLayout_11.addWidget(self.BtnAddSheet_2, 3, 6, 1, 1)
        self.labelMass_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.labelMass_2.setFont(font)
        self.labelMass_2.setToolTipDuration(3000)
        self.labelMass_2.setObjectName("labelMass_2")
        self.gridLayout_11.addWidget(self.labelMass_2, 3, 0, 1, 1)
        self.BtnRotateLeft_2 = QtWidgets.QPushButton(self.tab)
        self.BtnRotateLeft_2.setToolTipDuration(3000)
        self.BtnRotateLeft_2.setAutoFillBackground(False)
        self.BtnRotateLeft_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/utils/icons/icons8_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnRotateLeft_2.setIcon(icon3)
        self.BtnRotateLeft_2.setIconSize(QtCore.QSize(25, 25))
        self.BtnRotateLeft_2.setObjectName("BtnRotateLeft_2")
        self.gridLayout_11.addWidget(self.BtnRotateLeft_2, 3, 3, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.tab)
        self.pushButton_9.setToolTipDuration(3000)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/utils/icons/icons8_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_11.addWidget(self.pushButton_9, 3, 4, 1, 1)
        self.lineEditMass_3 = QtWidgets.QLineEdit(self.tab)
        self.lineEditMass_3.setText("")
        self.lineEditMass_3.setObjectName("lineEditMass_3")
        self.gridLayout_11.addWidget(self.lineEditMass_3, 3, 1, 1, 1)
        self.BtnDeleteSheet_2 = QtWidgets.QPushButton(self.tab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/utils/icons/x-square.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnDeleteSheet_2.setIcon(icon5)
        self.BtnDeleteSheet_2.setObjectName("BtnDeleteSheet_2")
        self.gridLayout_11.addWidget(self.BtnDeleteSheet_2, 3, 7, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 3, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setText("")
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_11.addWidget(self.label_3, 0, 0, 1, 8)
        self.tabWidget_2.addTab(self.tab, "")
        self.gridLayout_6.addWidget(self.tabWidget_2, 2, 2, 3, 2)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_detail, "")
        self.tab_struct = QtWidgets.QWidget()
        self.tab_struct.setObjectName("tab_struct")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_struct)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LbDocumentName = QtWidgets.QLabel(self.tab_struct)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.LbDocumentName.setFont(font)
        self.LbDocumentName.setObjectName("LbDocumentName")
        self.gridLayout_4.addWidget(self.LbDocumentName, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_struct, "")
        self.tab_tags = QtWidgets.QWidget()
        self.tab_tags.setObjectName("tab_tags")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_tags)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.BtnAddTag = QtWidgets.QPushButton(self.tab_tags)
        self.BtnAddTag.setMaximumSize(QtCore.QSize(120, 16777215))
        self.BtnAddTag.setIcon(icon2)
        self.BtnAddTag.setObjectName("BtnAddTag")
        self.gridLayout_3.addWidget(self.BtnAddTag, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_tags)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 959, 547))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.lineEditTag_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditTag_1.setText("")
        self.lineEditTag_1.setObjectName("lineEditTag_1")
        self.gridLayout_10.addWidget(self.lineEditTag_1, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem4, 1, 0, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_tags, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 70))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textEditComents = QtWidgets.QTextEdit(self.widget)
        self.textEditComents.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEditComents.setObjectName("textEditComents")
        self.horizontalLayout_5.addWidget(self.textEditComents)
        self.BtnSave = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnSave.sizePolicy().hasHeightForWidth())
        self.BtnSave.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnSave.setFont(font)
        self.BtnSave.setToolTipDuration(3000)
        self.BtnSave.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/utils/icons/floppy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnSave.setIcon(icon6)
        self.BtnSave.setIconSize(QtCore.QSize(30, 30))
        self.BtnSave.setObjectName("BtnSave")
        self.horizontalLayout_5.addWidget(self.BtnSave)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        DesignDocumentFillingForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(DesignDocumentFillingForm)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DesignDocumentFillingForm)

    def retranslateUi(self, DesignDocumentFillingForm):
        _translate = QtCore.QCoreApplication.translate
        DesignDocumentFillingForm.setWindowTitle(_translate("DesignDocumentFillingForm", "MainWindow"))
        self.lineEditProductName.setPlaceholderText(_translate("DesignDocumentFillingForm", "Наименование изделия"))
        self.label.setText(_translate("DesignDocumentFillingForm", "Сборочная единица"))
        self.label_2.setText(_translate("DesignDocumentFillingForm", "Деталь"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_unit), _translate("DesignDocumentFillingForm", "Сборочная единица"))
        self.labelBelongingToAnAssemblyUnit_2.setText(_translate("DesignDocumentFillingForm", "Принадлежность к сборочной единице:"))
        self.radioButtonUnit_1_2.setText(_translate("DesignDocumentFillingForm", "Сборочная единица 2"))
        self.radioButtonUnit_2_2.setText(_translate("DesignDocumentFillingForm", "Сборочная единица 1"))
        self.BtnOpenDesignFile_2.setToolTip(_translate("DesignDocumentFillingForm", "Расположение файла изображения конструкторского документа"))
        self.BtnOpenDesignFile_2.setText(_translate("DesignDocumentFillingForm", "Файл чертежа"))
        self.BtnAddSheet_2.setText(_translate("DesignDocumentFillingForm", "Добавить лист"))
        self.labelMass_2.setToolTip(_translate("DesignDocumentFillingForm", "Длина детали"))
        self.labelMass_2.setText(_translate("DesignDocumentFillingForm", "Масса детали, кг"))
        self.BtnRotateLeft_2.setToolTip(_translate("DesignDocumentFillingForm", "Повернуть изображение влево"))
        self.pushButton_9.setToolTip(_translate("DesignDocumentFillingForm", "Повернуть изображение вправо"))
        self.BtnDeleteSheet_2.setText(_translate("DesignDocumentFillingForm", "Удалить лист"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("DesignDocumentFillingForm", "Чертёж 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_detail), _translate("DesignDocumentFillingForm", "Деталь"))
        self.LbDocumentName.setText(_translate("DesignDocumentFillingForm", "СБ Сборочная единица"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_struct), _translate("DesignDocumentFillingForm", "Структура"))
        self.BtnAddTag.setText(_translate("DesignDocumentFillingForm", "Добавить тег"))
        self.lineEditTag_1.setPlaceholderText(_translate("DesignDocumentFillingForm", "Тег 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tags), _translate("DesignDocumentFillingForm", "Теги"))
        self.textEditComents.setPlaceholderText(_translate("DesignDocumentFillingForm", "Комментарии"))
        self.BtnSave.setToolTip(_translate("DesignDocumentFillingForm", "Сохранить документ"))