# Generated by Django 5.1.4 on 2024-12-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='RodBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank_length', models.FloatField()),
                ('part_length', models.FloatField()),
                ('complex_blank', models.BooleanField(default=False)),
                ('total_bars', models.IntegerField()),
                ('extra_length', models.FloatField(blank=True, null=True)),
                ('usage_rate', models.FloatField()),
                ('rod_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.rodform')),
            ],
        ),
        migrations.CreateModel(
            name='SheetBlank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_length', models.FloatField()),
                ('part_width', models.FloatField()),
                ('total_sheets', models.IntegerField()),
                ('extra_length', models.FloatField(blank=True, null=True)),
                ('extra_width', models.FloatField(blank=True, null=True)),
                ('usage_rate', models.FloatField()),
                ('sheet_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.sheetform')),
            ],
        ),
    ]
