# Generated by Django 5.1.4 on 2025-03-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='invoice_number',
            field=models.CharField(max_length=100),
        ),
    ]
