# Generated by Django 5.1.4 on 2025-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_task_status_alter_task_invoice_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskCounter',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('opened', 'Opened')], default='new', max_length=20),
        ),
    ]
