from PyQt5 import QtCore, QtGui, QtWidgets
import resources_rc

class Ui_DesignDocumentFillingForm(object):
    def setupUi(self, DesignDocumentFillingForm):
        DesignDocumentFillingForm.setObjectName("DesignDocumentFillingForm")
        DesignDocumentFillingForm.resize(1027, 791)

        self.centralwidget = QtWidgets.QWidget(DesignDocumentFillingForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)  # Отступы слева, сверху, справа и снизу
        self.verticalLayout_3.setSpacing(0)  # Расстояние между виджетами внутри макета

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)  # Отступы слева, сверху, справа и снизу
        self.verticalLayout.setSpacing(0)  # Расстояние между виджетами внутри макета

        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget_2.setObjectName("widget_2")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(10, 0, 0, 0)  # Отступы слева, сверху, справа и снизу
        self.verticalLayout_4.setSpacing(0)  # Расстояние между виджетами внутри макета

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 15, 10, 0)  # Отступы слева, сверху, справа и снизу
        self.horizontalLayout.setSpacing(0)  # Расстояние между виджетами внутри макета

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout")

        self.lineEditProductName = QtWidgets.QLineEdit(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditProductName.setFont(font)
        self.lineEditProductName.setObjectName("lineEditProductName")
        self.horizontalLayout.addWidget(self.lineEditProductName)

        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)

        # self.lineEditItemName = QtWidgets.QLineEdit(self.widget_2)
        # self.lineEditItemName.setObjectName("lineEditDetailName")
        # self.lineEditItemName.setPlaceholderText("Наименование элемента")
        # self.horizontalLayout.addWidget(self.lineEditItemName)

        # self.label = QtWidgets.QLabel(self.widget_2)
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # self.label.setFont(font)
        # self.label.setObjectName("label")
        # self.horizontalLayout_2.addWidget(self.label)

        # self.BtnEditTabName = QtWidgets.QPushButton(self.widget_2)
        # self.BtnEditTabName.setText("Изменить название вкладки")
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/utils/icons/plus-square-dotted.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.BtnUnit.setIcon(icon)
        # self.BtnEditTabName.setObjectName("move_left_button")
        # self.horizontalLayout.addWidget(self.BtnEditTabName)

        # self.BtnAddAssemblyUnit = QtWidgets.QPushButton(self.widget_2)
        # self.BtnAddAssemblyUnit.setText("+ СБ")
        # icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(":/utils/icons/plus-square-dotted.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.BtnDeleteTab.setIcon(icon)
        # self.BtnAddAssemblyUnit.setObjectName("BtnAddAssemblyUnit")
        # self.horizontalLayout.addWidget(self.BtnAddAssemblyUnit)

        # self.label_2 = QtWidgets.QLabel(self.widget_2)
        # font = QtGui.QFont()
        # font.setPointSize(12)
        # self.label_2.setFont(font)
        # self.label_2.setObjectName("label_2")
        # self.horizontalLayout_2.addWidget(self.label_2)

        # self.BtnAddDetail = QtWidgets.QPushButton(self.widget_2)
        # self.BtnAddDetail.setText("+ Дет")
        # self.BtnAddDetail.setIcon(icon)
        # self.BtnAddDetail.setObjectName("BtnAddDetail")
        # self.horizontalLayout.addWidget(self.BtnAddDetail)

        # self.BtnDelCurrentTab = QtWidgets.QPushButton(self.widget_2)
        # self.BtnDelCurrentTab.setText("Удалить")
        # self.BtnDelCurrentTab.setIcon(icon)
        # self.BtnDelCurrentTab.setObjectName("BtnDelCurrentTab")
        # self.horizontalLayout.addWidget(self.BtnDelCurrentTab)

        # spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.horizontalLayout_2.addItem(spacerItem1)

        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget_2)

        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")

        # self.tabWidget = QtWidgets.QTabWidget(self.widget_3)
        # self.tabWidget.setObjectName("tabWidget")

        # self.tab_struct = QtWidgets.QWidget()
        # self.tab_struct.setObjectName("tab_struct")
        # self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_struct)
        #
        # self.gridLayout_5.setObjectName("gridLayout_5")
        # self.gridLayout_4 = QtWidgets.QGridLayout()
        # self.gridLayout_4.setObjectName("gridLayout_4")
        # self.LbDocumentName = QtWidgets.QLabel(self.tab_struct)
        # font = QtGui.QFont()
        # font.setPointSize(10)
        # self.LbDocumentName.setFont(font)
        # self.LbDocumentName.setObjectName("LbDocumentName")
        # self.gridLayout_4.addWidget(self.LbDocumentName, 0, 0, 1, 1)
        # spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        # self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        # self.tabWidget.addTab(self.tab_struct, "")

        # self.tab_tags = QtWidgets.QWidget()
        # self.tab_tags.setObjectName("tab_tags")
        # self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_tags)
        # self.gridLayout_3.setObjectName("gridLayout_3")
        # self.BtnAddTag = QtWidgets.QPushButton(self.tab_tags)
        # self.BtnAddTag.setMaximumSize(QtCore.QSize(120, 16777215))
        # icon2 = QtGui.QIcon()
        # icon2.addPixmap(QtGui.QPixmap(":/utils/icons/plus-square-dotted.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        # self.BtnAddTag.setIcon(icon2)
        # self.BtnAddTag.setObjectName("BtnAddTag")
        # self.gridLayout_3.addWidget(self.BtnAddTag, 1, 0, 1, 1)
        # self.gridLayout_2 = QtWidgets.QGridLayout()
        # self.gridLayout_2.setObjectName("gridLayout_2")
        # self.scrollArea = QtWidgets.QScrollArea(self.tab_tags)
        # self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        # self.scrollArea.setWidgetResizable(True)
        # self.scrollArea.setObjectName("scrollArea")
        # self.scrollAreaWidgetContents = QtWidgets.QWidget()
        # self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 959, 547))
        # self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        # self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        # self.gridLayout_10.setObjectName("gridLayout_10")
        # self.lineEditTag_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        # self.lineEditTag_1.setText("")
        # self.lineEditTag_1.setObjectName("lineEditTag_1")
        # self.gridLayout_10.addWidget(self.lineEditTag_1, 0, 0, 1, 1)
        # spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        # self.gridLayout_10.addItem(spacerItem4, 1, 0, 1, 2)
        # self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        # self.gridLayout_2.addWidget(self.scrollArea, 2, 0, 1, 1)
        # self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        # self.tabWidget.addTab(self.tab_tags, "")

        # self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.widget_3)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 70))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 70))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, -1, 10, -1)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textEditComents = QtWidgets.QTextEdit(self.widget)
        self.textEditComents.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEditComents.setObjectName("textEditComents")
        self.horizontalLayout_5.addWidget(self.textEditComents)
        self.BtnSave = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BtnSave.sizePolicy().hasHeightForWidth())
        self.BtnSave.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.BtnSave.setFont(font)
        self.BtnSave.setToolTipDuration(3000)
        self.BtnSave.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/utils/icons/floppy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BtnSave.setIcon(icon6)
        self.BtnSave.setIconSize(QtCore.QSize(30, 30))
        self.BtnSave.setObjectName("BtnSave")
        self.horizontalLayout_5.addWidget(self.BtnSave)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.widget)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        DesignDocumentFillingForm.setCentralWidget(self.centralwidget)


        self.retranslateUi(DesignDocumentFillingForm)
        # self.tabWidget.setCurrentIndex(1)
        # self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DesignDocumentFillingForm)

    def retranslateUi(self, DesignDocumentFillingForm):
        _translate = QtCore.QCoreApplication.translate
        DesignDocumentFillingForm.setWindowTitle(_translate("DesignDocumentFillingForm", "MainWindow"))
        self.lineEditProductName.setPlaceholderText(_translate("DesignDocumentFillingForm", "Наименование изделия"))
        # self.label.setText(_translate("DesignDocumentFillingForm", "Сборочная единица"))
        # self.label_2.setText(_translate("DesignDocumentFillingForm", "Деталь"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_unit), _translate("DesignDocumentFillingForm", "Сборочная единица"))
        # self.checkBoxBelongingToAnAssemblyUnit.setText(_translate("DesignDocumentFillingForm", "Принадлежность к сборочной единице:"))
        # self.radioButtonUnit_1_2.setText(_translate("DesignDocumentFillingForm", "Сборочная единица 2"))
        # self.radioButtonUnit_2_2.setText(_translate("DesignDocumentFillingForm", "Сборочная единица 1"))
        # self.BtnOpenDesignFile_2.setToolTip(_translate("DesignDocumentFillingForm", "Расположение файла изображения конструкторского документа"))
        # self.BtnOpenDesignFile_2.setText(_translate("DesignDocumentFillingForm", "Файл чертежа"))
        # self.BtnAddSheet_2.setText(_translate("DesignDocumentFillingForm", "Добавить лист"))
        # self.labelMass_2.setToolTip(_translate("DesignDocumentFillingForm", "Длина детали"))
        # self.labelMass_2.setText(_translate("DesignDocumentFillingForm", "Масса детали, кг"))
        # self.BtnRotateLeft_2.setToolTip(_translate("DesignDocumentFillingForm", "Повернуть изображение влево"))
        # self.pushButton_9.setToolTip(_translate("DesignDocumentFillingForm", "Повернуть изображение вправо"))
        # self.BtnDeleteSheet_2.setText(_translate("DesignDocumentFillingForm", "Удалить лист"))
        # self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("DesignDocumentFillingForm", "Лист 1"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_detail), _translate("DesignDocumentFillingForm", "Деталь"))
        # self.LbDocumentName.setText(_translate("DesignDocumentFillingForm", "СБ Сборочная единица"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_struct), _translate("DesignDocumentFillingForm", "Структура"))
        # self.BtnAddTag.setText(_translate("DesignDocumentFillingForm", "Добавить тег"))
        # self.lineEditTag_1.setPlaceholderText(_translate("DesignDocumentFillingForm", "Тег 1"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tags), _translate("DesignDocumentFillingForm", "Теги"))
        self.textEditComents.setPlaceholderText(_translate("DesignDocumentFillingForm", "Комментарии"))
        self.BtnSave.setToolTip(_translate("DesignDocumentFillingForm", "Сохранить документ"))