# Generated by Django 5.1.4 on 2024-12-27 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='drawings/')),
                ('mass', models.FloatField()),
                ('assembly_unit', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity_in_task', models.IntegerField()),
                ('quantity_to_produce', models.IntegerField()),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.drawing')),
                ('rod_blank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.rodform')),
                ('sheet_blank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.sheetform')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.task')),
            ],
        ),
    ]
