# Generated by Django 5.1.4 on 2025-03-06 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(default='Untitled', max_length=255)),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(default='Untitled', max_length=255, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.drawing', verbose_name='Родительский чертеж')),
                ('main_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='products.maindocument')),
            ],
            options={
                'verbose_name': 'Чертеж',
                'verbose_name_plural': 'Чертежи',
            },
        ),
        migrations.CreateModel(
            name='DrawingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='drawings/')),
                ('is_actual', models.BooleanField(default=True, verbose_name='Актуальность')),
                ('mass', models.FloatField(blank=True, null=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='products.drawing')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity_in_task', models.IntegerField()),
                ('quantity_to_produce', models.IntegerField(blank=True, null=True)),
                ('drawing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.maindocument')),
                ('rod_blank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.rodform')),
                ('sheet_blank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.sheetform')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.task')),
            ],
        ),
        migrations.AddField(
            model_name='maindocument',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='main_documents', to='products.tag'),
        ),
        migrations.CreateModel(
            name='TaskProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.task')),
            ],
        ),
    ]
