# Generated by Django 5.1.4 on 2024-12-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='drawing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.drawing'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_to_produce',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
