# Generated by Django 5.1.4 on 2025-01-16 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_drawing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='file',
        ),
        migrations.CreateModel(
            name='DrawingSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='drawings/')),
                ('sheet_number', models.PositiveIntegerField()),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='products.drawing')),
            ],
        ),
    ]
