# Generated by Django 5.1.4 on 2025-01-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_drawing_file_drawingsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingsheet',
            name='is_actual',
            field=models.BooleanField(default=True, verbose_name='Актуальность'),
        ),
    ]
