# Generated by Django 5.1.4 on 2025-01-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_drawingsheet_is_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='drawings', to='products.tag'),
        ),
    ]
