# Generated by Django 5.1.4 on 2025-01-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_tag_drawing_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='assembly_unit',
            field=models.BooleanField(default=False, verbose_name='СБ'),
        ),
    ]
