# Generated by Django 5.1.4 on 2025-01-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_drawing_assembly_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='doc_name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
