# Generated by Django 5.1.4 on 2025-01-19 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_drawing_doc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='tags',
        ),
        migrations.CreateModel(
            name='MainDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_name', models.CharField(default='Untitled', max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='main_documents', to='products.tag')),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='main_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='products.maindocument'),
        ),
        migrations.AlterField(
            model_name='product',
            name='drawing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.maindocument'),
        ),
    ]
