# Generated by Django 5.1.4 on 2025-01-24 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_drawing_comment_remove_drawing_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawing',
            options={'verbose_name': 'Чертеж', 'verbose_name_plural': 'Чертежи'},
        ),
        migrations.AddField(
            model_name='drawing',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.drawing', verbose_name='Родительский чертеж'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='main_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='products.maindocument'),
        ),
    ]
