# Generated by Django 5.1.4 on 2025-01-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_drawing_options_drawing_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='doc_name',
            field=models.CharField(default='Untitled', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
