# Generated by Django 5.1.4 on 2025-01-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_drawing_doc_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='assembly_unit',
        ),
    ]
