# Generated by Django 5.1.4 on 2025-01-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_drawing_assembly_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawingsheet',
            name='sheet_number',
        ),
    ]
