# Generated by Django 5.1.4 on 2025-01-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_drawingsheet_sheet_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='mass',
        ),
        migrations.AddField(
            model_name='drawingsheet',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
