# Generated by Django 5.1.4 on 2025-02-03 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_drawing_mass_drawingsheet_mass'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='maindocument',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
